### ISSUE TITLE
@ng-bootstrap not found. I've istalled as README.md, put in the app.models.ts (as found on angular's tutorial (version 2) ) and browser returns to me an error 404

### ISSUE THREAD

**Issue by arturcesarmelo** [ng-bootstrap/ng-bootstrap#1003]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Link to minimally-working plunker that reproduces the issue:

You can fork a plunker from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.
Please note that we can _not_ act on bug reports without a minimal reproduction scenario in plunker. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular:

ng-bootstrap:

Bootstrap:

**Comment by jnizet** [comment]
@arturcesarmelo you've put all your problem description in the title of the issue, rather than reading carefully and following the template that you should follow for issues.

In particular, read these lines:

> the issues forum is NOT for support requests. It is for bugs and feature requests only.

> Please note that we can not act on bug reports without a minimal reproduction scenario in plunker

So I'll close your issue, which should be posted on StackOverflow, not here, since it's most certainly not an issue with ng-bootstrap, but rather an issue with your code/setup.

Note that, even on StackOverflow, you will have to post all the necessary information  needed to understand the problem (the code, and a reproduction in a plunkr), otherwise your question will be closed too.
