### ISSUE TITLE
Passing data from my component to modal

### ISSUE THREAD

**Issue by elmoromourad** [ng-bootstrap/ng-bootstrap#1014]
I want to create a custom modal (edit user modal) with a form, I would like to pass my object from the main component `company.component.ts` to `edit.modal.ts`, edit data and pass it again to the main component.
What's the best way to do it please ?

**Comment by pkozlowski-opensource** [comment]
I'm sorry but your question is not clear at all and as such not actionable. You _might_ be looking for what is described in this SO issue: http://stackoverflow.com/questions/40381862/angular-2-selector-with-template-content/40383481. Or you might check the "Components as content" demo from https://ng-bootstrap.github.io/#/components/modal but this is just stabbing in the dark...

In any case we are not handling support questions here, here is why: https://github.com/ng-bootstrap/ng-bootstrap#getting-help

Closing as a support request that doesn't belong here.

**Comment by elmoromourad** [comment]
I have already made a basic modal and it works well.
I want to create a custom modal (with form). The problem is that there is no documentation about it.
How to pass data from my component to modal component ?

**Comment by pkozlowski-opensource** [comment]
@elmoromourad did you have a look at the references I've provided? More specifically at  the "Components as content" demo from https://ng-bootstrap.github.io/#/components/modal ??? Since this demo shows _exactly_ how to pass data to the component used as content (hint: look for `componentInstance` after opening modal). Here is the life example: http://plnkr.co/edit/qLs104OWdiijEL9GGdEH?p=preview

Once again, if you need help / thing that something is missing please provide a minimal plunker with what you are trying to achieve (you can start with the one I've just linked). Unfortunately your problem description is very vague  so it is impossible to help more...
