### ISSUE TITLE
Modal windows - append to body feature

### ISSUE THREAD

**Issue by shnmkhk** [ng-bootstrap/ng-bootstrap#1018]
### Bug description:

Support for modal append-to-body.

### Link to minimally-working plunker that reproduces the issue:

We had to explicitly add **&lt;template ngbModalContainer&gt;&lt;/template&gt;** to the parent container incase a modal window is to be opened up. 

The modal overlay/ backdrop occupies full window as expected, if the parent container is body/ rootElement in the page; If in case the modal window opening is triggered at nth depth (n > 1) we will be ending up at backdrop getting only to the container not to the entire window. In angular 1 the feature to add modal to body is by default and adds to parent, if specified which is not the case in angular 2.

![a](https://cloud.githubusercontent.com/assets/169433/20140026/e39a5648-a6ae-11e6-8809-e5217f87e840.PNG)

Please allow us to add modal component to body at every nth depth, by passing **appendTo: 'body'** property while supplying NgbModalOptions

**Comment by shnmkhk** [comment]
Please give me a pointer to add this feature sooner possible
@scttcper

**Comment by pkozlowski-opensource** [comment]
@shnmkhk I'm sorry but it is not very clear what issue you are raising here? Are you saying that all modal and backdrop elements should be inserted as direct children of the `<body>` element instead of being siblings of `<template ngbModalContainer></template>`? If so, I agree that we should do this but I don't think I see much point in having the `appendTo: 'body'` option - IMO we should append to `<body>` by default.

**Comment by shnmkhk** [comment]
Yes @pkozlowski-opensource I mean to add a feature how it was doing earlier in Angular 1, adding window, backdrop to the body tag by default. It was giving an option called appendTo property in Angular 1 modal options definition. We don't see such option in Angular 2 counter part

**Comment by morriq** [comment]
Hello, how are things going here? Do we have some workaround for that?

**Comment by katesowles** [comment]
Any updates?
