### ISSUE TITLE
Allow search input box inside a dropdown

### ISSUE THREAD

**Issue by ASHFAQPATWARI** [ng-bootstrap/ng-bootstrap#1030]
Can we have a property which when applied to any element insde dropdown, does not close the dropdwon. This way we can implement search inside dropdown.

If there is already a way around to do this, please point me in that direction.

**Comment by pkozlowski-opensource** [comment]
Before tackling the issue of inputs inside dropdowns let's observe that Bootstrap's uses `<a>` elements for each menu item: http://v4-alpha.getbootstrap.com/components/dropdowns/. HTML5 spec doesn't allow nesting of `<input>` elements inside `<a>` (http://stackoverflow.com/a/6393863/1418796, https://www.w3.org/TR/2011/WD-html5-20110113/text-level-semantics.html#the-a-element) so what you are asking for is not really possible in Bootstrap's version of the dropdown widget.

Please note that _some_ browsers _might_ render inputs inside `<a>` but you are really hacking here. If you decide to go down the slippery hacking path you could always wrap your `<input>` inside say, a `<div>` and stop propagation of `click` events: http://plnkr.co/edit/o1HVN8ofyADZTsCdK89S?p=preview (this kind of workish, instead in Chrome).

I'm going to close this one since:
* what you are asking for here is really hackish and can be achieved in a hackish way :-)
* we've got already issues that track legitimate use-cases in this area:  #1022

Side note: it _sounds_ for me like you might need a popover instead of a dropdown...
