### ISSUE TITLE
When having a date-picker inside a modal, when I select a date the modal closes.

### ISSUE THREAD

**Issue by ypalaniappan** [ng-bootstrap/ng-bootstrap#1042]
When having a date-picker inside a modal, when I select a date the modal closes.

Example to reproduce issue:
http://plnkr.co/edit/ATyV4MJ2vvoDgCc9W5Wn?p=preview

**Comment by PEsteves8** [comment]
I had this same issue. I tried to tell @pkozlowski-opensource on @angular gitter channel, but he's probably not available at the moment.

I think it's because on one of the last updates, a click event preventDefault was removed to allow dropdowns to properly close on modals. I'm not sure though.

Anyway, what happens is that clicking the datePicker is equivalent to clicking the backdrop. A quick workaround for now is to use the option { backdrop: 'static' } which will always prevent the modal from closing on datePicker click, although with the caveat that it also stops users from closing the modal by clicking outside of it.

I assume it's the same problem as #1040
