### ISSUE TITLE
ngbPopover not showing up

### ISSUE THREAD

**Issue by yanis84** [ng-bootstrap/ng-bootstrap#1054]
This issue relates to this StackOverflow question :
<a href="http://stackoverflow.com/questions/39506128/ngbpopover-not-showing-up">Question</a>

There is a supposed working plunk here :
<a href="plnkr.co/edit/BoTsvDAhIETBkU64JvLk?p=preview">Plunk</a>

Yet the plunk does not work on my browser ? Why is that?

**Comment by pkozlowski-opensource** [comment]
Your plunker was broken due to the configuration issue - you need to import our module as `NgbModule.forRoot()` instead of simply `NgbModule`, see: https://ng-bootstrap.github.io/#/getting-started

Here is a working plunk: http://plnkr.co/edit/BoTsvDAhIETBkU64JvLk?p=preview

Closing as a support request.
