### ISSUE TITLE
TemplateRef creation documenation

### ISSUE THREAD

**Issue by alex321** [ng-bootstrap/ng-bootstrap#1084]
I think it might be good to update/create a plunkr for DatePickerConfig to show how to create a TemplateRef.

The problem I found is that if you want to create the TemplateRef, you need a Component (which is understandable since you might want the template to contain some functions that could be exposed from the component's class object). 

However, it is not obvious where to put the actual Template `string` in isolation and trying to achieve that in a service led me to https://github.com/angular/angular/issues/9293. 

Thanks in advance and pardon me if I am raising unnecessary issues.

**Comment by pkozlowski-opensource** [comment]
You really can't create `TemplateRef`s from string in Angular 2 (well, technically you _can_ but it is would require using private APIs and would kill AoT compilation). As such this is something we really don't want to document.

I guess that what you are after are reusable datepickers / global cell template for all datepicker instances. If so this is not something that is super-nice today, basically you've got 2 options:
* wrap a datepicker + `<template>` in a reusable `@Component`
* create component that represents a cell so you've got less typing when providing content of a cell in a `<template>`

If I understand your use-case correctly I agree that things could be improved but unfortunately we don't have great technical means of doing so... We could accept cell components instead of just `TemplateRef`s but this is tricky as well.

I'm going to keep this one open as a feature request but don't hold your breath - it won't be top priority for now.

**Comment by alex321** [comment]
I think you've understood me correctly though I wasn't clear. I basically wanted to provide a common template (or a list of common templates i.e. themese) that can be used in other projects that we have. 

Hence, I thought a service would fit quite well, but I got stuck on how to create a `TemplateRef` in isolation (hence the reference to the issue about `ViewContainerRef` in services). My best attempt was to create a Component that needs to be created using `ViewContainerRef` in the main `App` Component`. It is okay but could be better, hence why I raised the issue. I raised in part to help others and in part to track the other issue that if resolved in a convenient way would solve this problem.
