### ISSUE TITLE
NgbRadioGroup breaks, when including bootstrap.js

### ISSUE THREAD

**Issue by c1rus** [ng-bootstrap/ng-bootstrap#1101]
NgbRadioGroup stops working, when you include bootstrap.js in page. I think it is because of data-toggle attribute here:

https://github.com/ng-bootstrap/ng-bootstrap/blob/991c88080eb50aa0c9d9ddaea9fb1b5bd7e85ccd/src/buttons/radio.ts#L16

Example: http://plnkr.co/edit/sC6zUk1wBgpKyv5pYLHh?p=preview

Angular: 2.0.0

ng-bootstrap: 1.0.0-alpha.14

Bootstrap: 4.0.0-alpha.5

**Comment by alex321** [comment]
@c1rus I don't think that you should be using both in the page as I imagine there would be conflicts in general.

**Comment by pkozlowski-opensource** [comment]
We can't remove the mentioned `data-toggle` attribute due to https://github.com/twbs/bootstrap/issues/20359 and this should be solved on Bootstrap's side via https://github.com/twbs/bootstrap/issues/18874

But as @alex321 there is not point of using Bootstrap's JS with this library (only CSS is needed). More than this - the whole point of this library is to _replace_ `bootstrap.js `. As such using `bootstrap.js ` and this library goes against the very reason of this library existence...

Going to close this one as the proper solution should come from Bootstrap's CSS and the described scenario is not the one we want to support.

**Comment by c1rus** [comment]
agrh, i was struggling with this for few hours. It makes sense, maybe there should be some kind of warning in docs.

Thx for the answer and great job.

**Comment by mb2140** [comment]
Using the latest Bootstrap Alpha 6 I'm still running into this issue with DD buttons.  They are working correctly when using bootstrap.js but not after I remove it (see Plunker below)

http://plnkr.co/edit/jDzEBalSiWqIfEmwR3qm?p=preview
