### ISSUE TITLE
pagination: page set to 1 when collectionSize is retrieved asynchronously

### ISSUE THREAD

**Issue by Puigcerber** [ng-bootstrap/ng-bootstrap#1111]
### Bug description:

The current page is reset to 1 when trying to get the collection size asynchronously from the server.

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/JuiaEdM54AmmBDUzW7uC?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.2.4

ng-bootstrap: 1.0.0-alpha.14

Bootstrap: 4.0.0-alpha.5

**Comment by alex321** [comment]
@Puigcerber This isn't really a bug. In your example, the initial `collectionSize` is essentially 0 (before the value comes back). So there are 0 pages and you are requesting `page` 4. This is an invalid state so defaulting to 1 makes sense. 

@pkozlowski-opensource I imagine it would be worth documenting that. 

There are other possible solutions e.g. if `page` requested is greater than `pageCount` then we could give the last page and otherwise we default to one (e.g. for negative values). However, I believe the current implementation is better, simpler and more sensible. If you have better ideas on what the default behaviour should be then please share them and they would be considered.

**Comment by wesleycho** [comment]
This has been reported in UI Bootstrap in the past as well.

I wonder if there is something we can do better here, as it is a little more troublesome to work with.

**Comment by Puigcerber** [comment]
Not trying to update the pages when there isn't a `collectionSize` could be an easy fix.

```
ngOnChanges(changes: SimpleChanges): void {
    if (this.collectionSize) {
      this._updatePages(this.page);
    }
  }
```

But this of course breaks the "edge cases" tests.

```
it('should handle edge "collectionSize" values', () => {
    const html = '<ngb-pagination [collectionSize]="collectionSize"></ngb-pagination>';
    const fixture = createTestComponent(html);

    fixture.componentInstance.collectionSize = 0;
    fixture.detectChanges();
    expectPages(fixture.nativeElement, ['-« Previous', '-» Next']);

    fixture.componentInstance.collectionSize = NaN;
    fixture.detectChanges();
    expectPages(fixture.nativeElement, ['-« Previous', '-» Next']);

    fixture.componentInstance.collectionSize = null;
    fixture.detectChanges();
    expectPages(fixture.nativeElement, ['-« Previous', '-» Next']);
});
```

As the component is create with some default values and therefore the previous rendered element stays.

**Comment by pkozlowski-opensource** [comment]
IMO this works as expected and I'm not sure how we could "fix" it on the library size. We need to do auto-corrections of displayed pages otherwise we could get into the inconsistent state.

In your particular case just adjust page when async data are ready: http://plnkr.co/edit/at6VSAIUVwj0HrizMTxm?p=preview

The only possible "fix" I can think of is to leave page `undefined` when the collection size is not known / invalid but I also appreciate that this must send us into other corner cases. 

I'm going to go ahead and close this one for now but happy to re-open if anyone had a better idea on how to tackle this / similar cases.

**Comment by Puigcerber** [comment]
The only problem I see with this approach is that the `pageChange` event is fired with a value of 1 and in my particular use case resets the page value. Thanks anyway!

**Comment by Puigcerber** [comment]
I forgot to add that with this workaround we can't use the `async` pipe as the `page` needs to be assigned inside of the `subscribe` method.
