### ISSUE TITLE
NgbModule.forRoot() breaks 'traditional' style radio buttons

### ISSUE THREAD

**Issue by GeorgeA93** [ng-bootstrap/ng-bootstrap#1125]
### Bug description:

I am attempting to use 'traditional' style radio buttons, i.e the radio's you can see [here](http://v4-alpha.getbootstrap.com/components/forms/#radios)

The plunker below shows that these radio's do not work when NgbModule.forRoot() has been called.

You can still interact with the radios, however they do not show the initial value of the model.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.0.0

ng-bootstrap: 1.0.0-alpha.14

Bootstrap: 4.0.0-alpha.5

**Comment by alex321** [comment]
This is caused by the fact that `ngbRadioGroup` is the one notifying all the inputs about the change. There is no `ngbRadioGroup` on the with the default usage hence it breaks the functionality.  

@pkozlowski-opensource I think we should introduce a selector `[ngbRadioButton]` for that instead of using `input[type=button]` or only apply it to descendants of `ngbRadioGroup` as it doesn't make sense to override default angular functionality. It's a deal breaker for the whole library if it interferes with standard behaviours. Could we patch that soon as it seems necessary and potentially look into incorporating #1095 ?

**Comment by pkozlowski-opensource** [comment]
@alex321 you are right, we should probably have a more fine-grained selector... I'm going to look into this issue and your PR tomorrow.

**Comment by alex321** [comment]
@pkozlowski-opensource I had a look around and as far as I am aware, we are doing what we should be. Do you think that this might be related to angular in any way? 

Here's a brief summary that explains my confusion (I am basing it on GeorgeA93's plunker):
I changed the selector for the buttons from `input[type=radio]` to `ngbButton` so that I leave Angular to handle the default radios. Then I used `choiceControl.registerOnChange`  but that didn't fire when I change either the default buttons or the `ngbButton`.

However, if I use `choiceControl.setValue()`, it does fire as expected. And then both buttons respond as expected. Hence, I am confused how the two should know that a change has occurred.

**Comment by maxisam** [comment]
This is a nasty one. I spent 2 days for this, since I didn't know it is possible. 

I love this library, but I think if we find a component that can break the default usage, we should remove it from the whole package temporary.  Btw, It is not a BAN to that component. 

https://github.com/qdouble/angular-webpack2-starter/issues/247

**Comment by bprgit** [comment]
We have also spent some time with this issue. 

Is there a work around for this issue and/or an ETA on when a fix may be available?

**Comment by maxisam** [comment]
My work around is pretty simple, exclude ngbRadioButton component. 

Here it is, save you some time.
```
import {
    NgbAccordionModule,
    NgbAlertModule,
    // NgbButtonsModule,
    NgbCarouselModule,
    NgbCollapseModule,
    NgbDatepickerModule,
    NgbDropdownModule,
    NgbModalModule,
    NgbPaginationModule,
    NgbPopoverModule,
    NgbProgressbarModule,
    NgbRatingModule,
    NgbTabsetModule,
    NgbTimepickerModule,
    NgbTooltipModule,
    NgbTypeaheadModule
} from '@ng-bootstrap/ng-bootstrap';
import { ModuleWithProviders, NgModule } from '@angular/core';
const NGB_MODULES = [
    NgbAccordionModule, NgbAlertModule, NgbCarouselModule, NgbCollapseModule, NgbDatepickerModule,
    NgbDropdownModule, NgbModalModule, NgbPaginationModule, NgbPopoverModule, NgbProgressbarModule, NgbRatingModule,
    NgbTabsetModule, NgbTimepickerModule, NgbTooltipModule, NgbTypeaheadModule
];

@NgModule({
    imports: [
        NgbAlertModule.forRoot(), NgbCollapseModule.forRoot(), NgbProgressbarModule.forRoot(),
        NgbTooltipModule.forRoot(), NgbTypeaheadModule.forRoot(), NgbAccordionModule.forRoot(), NgbCarouselModule.forRoot(),
        NgbDatepickerModule.forRoot(), NgbDropdownModule.forRoot(), NgbModalModule.forRoot(), NgbPaginationModule.forRoot(),
        NgbPopoverModule.forRoot(), NgbProgressbarModule.forRoot(), NgbRatingModule.forRoot(), NgbTabsetModule.forRoot(),
        NgbTimepickerModule.forRoot(), NgbTooltipModule.forRoot()
    ],
    exports: NGB_MODULES
})
export class CNgbRootModule {
}

// tslint:disable-next-line:max-classes-per-file
@NgModule({ imports: NGB_MODULES, exports: NGB_MODULES })
export class CNgbModule {
    static forRoot(): ModuleWithProviders { return { ngModule: CNgbRootModule }; }
}

```

**Comment by bprgit** [comment]
Thanks, worked a treat.

**Comment by GoNode5** [comment]
@pkozlowski-opensource  DzmitryShylovich ask why you don't prefix?
https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/buttons/radio.ts#L76

**Comment by wesleycho** [comment]
Looks like the culprit is that the provider needs to be provided into the module, not just the directive - see [here](http://plnkr.co/edit/Zk74D6KrgIJVpW48JnCl?p=preview) for a working implementation.

I'll file a PR shortly.

**Comment by Ludevik** [comment]
I have spent also quite some time with similar issue. In my case i tried to disable the form group containing the radio buttons. As soon as i import NgbModule, the disabling of the radio buttons breaks. When i remove the import, the radio buttons are disabled.

[Plunk](http://plnkr.co/edit/L5h3OBXWS8a7NMtsj8a9?p=preview)

The plunker shows also the problem with setting the value.

**Comment by changLiuUNSW** [comment]
Really nasty! We have spent about 1 week and finally find out this culprit.
Is there any ETA for this issue?

**Comment by changLiuUNSW** [comment]
@maxisam 
```
I love this library, but I think if we find a component that can break the default usage, we should remove it from the whole package temporary. Btw, It is not a BAN to that component. lol
```
Totally agreed.
@pkozlowski-opensource  Can we remove the whole component temporarily?

**Comment by pkozlowski-opensource** [comment]
@changLiuUNSW we will remove default matching on radios before beta (hopefully or of 2-3 next releases). For now you can just skip importing this particular module in your app.

**Comment by jinwyp** [comment]
..... I came here for setting default value for radio？  Now that mean we need choose side for using angular4 or ng bootstrap ？ LOL

**Comment by changLiuUNSW** [comment]
@jinwyp So the whole component should be excluded until the issue is fixed

**Comment by mraiguo** [comment]
when I update to 1.0.0-alpha.27,It was suddenly able to run, But not for a while 。I wanna know I , is this  fixed？
