### ISSUE TITLE
ngb-pagination should use consistent width

### ISSUE THREAD

**Issue by rightisleft** [ng-bootstrap/ng-bootstrap#1138]
This is an edge case that only shows up in single pages apps, and not traditional bootstrap:

Currently when you transition from single digit page values, to multi digit page values, the dynamic width of the box causes the <nav> width to expand to accommodate the extra digits. 

Example:
1,2,3,4,5 needs to supper half as many digits as 11,12,13,14,15 

https://vid.me/c7GE

This creates a weird user experience where the box seemingly expands in sizes as they progress through the pages.  This is less intense on traditional web pages which have page reloads, but is hugely noticeable on Single Page Apps, and thusly ng-bootstrap. 

Fix:
Calculate the max width of the display box when compared to the range.

**Comment by pkozlowski-opensource** [comment]
This would be Bootstrap's CSS issue and since this library just builds on top of this CSS this is not something we want to fix here. You've got several options:
* open an issue in the upstream project: https://github.com/twbs/bootstrap
* override Bootstrap's CSS and create your own theme with fixed with for pagination cells
* override pagination CSS in your component

Going to close this one as it is not something to be fixed in this project.
