### ISSUE TITLE
Pagination should have disabled state

### ISSUE THREAD

**Issue by paynoattn** [ng-bootstrap/ng-bootstrap#1153]
### Bug description:
When using the pagination component, you'd expect the pagination component to have a disabled input and state for when the pagination component should be disabled from user input.

In bootstrap styles, there are existing styles for adding a disabled state to pagination from user state, and we are using this for ellipsis, but there should be also be an input that can allow the user to disable the pagination from user input entirely (i.e., waiting on XHR to come back from server) except with an ```*ngHide="myVar"```.

I'm working on a pull request for this now.

**Comment by paynoattn** [comment]
See #1155.

**Comment by thbt** [comment]
It makes sense to disable ellipsis and previous/next links because they should not be clickable or focusable, but I think it's bad UX to disable an entire pagination component, either you remove it from DOM when you are waiting for a response, or you cancel it and fire another request.

Is this feature really needed ?
