### ISSUE TITLE
How can i Trigger the Modal Via data-* Attributes

### ISSUE THREAD

**Issue by yagobski** [ng-bootstrap/ng-bootstrap#1162]
In bootstrap we can do like this  data-toggle="modal" and data-target="#modalID" to any element.

Example
```
<!-- Buttons -->
<button type="button" data-toggle="modal" data-target="#myModal">Open Modal</button>

<!-- Links -->
<a data-toggle="modal" href="#myModal">Open Modal</a>

<!-- Other elements -->
<p data-toggle="modal" data-target="#myModal">Open Modal</p>
```

Why with ng-bootstrap this is not working

**Comment by pkozlowski-opensource** [comment]
ng-bootstrap is _not_ aiming at re-creating identical APIs as Bootstrap has. The reason is simple: we believe that you can have much better APIs based on what is possible and natural in the Angular World. As such you shouldn't be consulting Bootstrap's APIs but rather ours: https://ng-bootstrap.github.io/#/components/modal

In the feature please ask support requests on a dedicated forum: https://github.com/ng-bootstrap/ng-bootstrap#getting-help
