### ISSUE TITLE
Ellipsis showed between the first and the second page when visiting the fourth page

### ISSUE THREAD

**Issue by dbsima** [ng-bootstrap/ng-bootstrap#1166]
### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/OTUONXeZSAEN0HRztpwb?p=preview

Click on the fourth page.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.0.0

ng-bootstrap: 1.0.0-alpha.15

Bootstrap: 4.0.0-alpha.5
![ss](https://cloud.githubusercontent.com/assets/1548356/21524895/c6d8443e-cd19-11e6-8c3a-c8057e0d40f8.png)

**Comment by pkozlowski-opensource** [comment]
I believe that it works as expected. You are saying: show me 5 pages and rotate. We do display `1` and `12` always. Dropping ellipsis between `1` and `2` would mean that all of the sudden we would be displaying 6 pages instead of 5.

I understand that it might look odd but I'm not sure it will be easy to come up with another consistent behaviour. We could:
* stop showing `1` and `12`
* stop showing elipsis when there is continuity (then again, we are not respecting 5 pages).

Also you can drop `[rotate]="true"`.

All in all it is a corner case and I'm not sure what would be the best way of changing it (not even sure if we want to change it at all). @maxokorokov WDYT?

**Comment by maxokorokov** [comment]
Well yes, it is kinda working as expected for now, because we didn't take much time discussing corner cases. @pkozlowski-opensource, both your bullet points are implemented in the ui-bootstrap though:

- there is a `boundary-links-numbers` option in the ui bootstrap to toggle `1` and `12`
- 5 page rotation is not respected


Dropping boundary number looks strange to me personally: `... 2 3 [4] 5 6 ... 12`
So __If__ we want to do something with it, I would probably just drop the ellipsis:

```
// for 12 pages
1  2 [3] 4  5  ...  12
1  2  3 [4] 5  6  ...  12   <--- 5-page rotation not respected
1 ... 3  4 [5] 6  7  ...  12

// for 7 pages for instance, 5-page rotation would never respected
1  2 [3] 4  5  6  7
1  2  3 [4] 5  6  7
1  2  3  4 [5] 6  7
```
