### ISSUE TITLE
DatePicker custom footer template

### ISSUE THREAD

**Issue by jehugaleahsa** [ng-bootstrap/ng-bootstrap#1197]
### Issue description:
There used to be a nice feature to turn a button group under the calendar for selecting Today, clearing the current value or closing the calendar control, which was useful when working with an input. Is there any possibility of these buttons being re-added? Is there a temporary work around to add these myself?

### Version of Angular, ng-bootstrap, and Bootstrap:
Angular: 2.3.1
ng-bootstrap: 1.0.0-alpha.16
Bootstrap: 4.0.0-alpha.5

**Comment by pkozlowski-opensource** [comment]
We just don't want to add a separate config option for each and every button that could be added to the footer - this would quickly "explode" public API.

What we would like to do instead is to provide people with ability to provide a template that would be inserted as a custom footer.

**Comment by jehugaleahsa** [comment]
Totally agree.

**Comment by skendrot** [comment]
This issue is very specific to "Close, Clear, Today Buttons". If other issues which are more broad like ["Add html content to bottom of DatePicker"](https://github.com/ng-bootstrap/ng-bootstrap/issues/1387) are going to be closed as duplicates of this, can the title of this please be changed or close this issue and open a new issue which addresses the more broad request like #1387. Or, reopen #1387 as it is requesting a generic way to add content to the bottom of the DatePicker.

**Comment by wesleycho** [comment]
Is this specific to the popup, or for the datepicker itself? Implementation-wise, would it make sense to allow users to provide a TemplateRef and bind to `footer` or something like that?

**Comment by skendrot** [comment]
I would want this if I used the popup, or placed the picker directly in my page

**Comment by jehugaleahsa** [comment]
I was referring specifically to the popup.

**Comment by skendrot** [comment]
Although I suppose if I placed it on my page I would have a little more control already of what's "on the bottom". Currently I am using jquery to add the content to the bottom of the picker

**Comment by martinmakesitwork** [comment]
Hey guys, I really need this feature. Is there a workaround available?
