### ISSUE TITLE
alpha.18 datepicker is incompatible with Angular 4.0.0-beta.2

### ISSUE THREAD

**Issue by alanpurple** [ng-bootstrap/ng-bootstrap#1202]
http://plnkr.co/edit/QnqHUryS3vlu24FwrZoL?p=preview

**Comment by pkozlowski-opensource** [comment]
@alanpurple I'm not sure what is exactly "not working" based on the attached plunker (or rather, what is the problem with material).

In the plunker I can see an error thrown when the model is undefined. This happens in Angular 4.0.x only and it seems like this is a breaking change on the Angular side. I'm going to confirm with the core team if this change was intentional or not (and if it was intentional we are going to fix it here). Is this what you are reporting here?

**Comment by alanpurple** [comment]
@pkozlowski-opensource 
those errors are not shown without angular-material

**Comment by pkozlowski-opensource** [comment]
> those errors are not thrown without angular-material, even with angular 4.0.0

@alanpurple are you sure? Asking since I've got a plunk that suggest otherwise: http://plnkr.co/edit/dPJ4QsRPsX6ZLtfXrEdl?p=preview (errors thrown even if material not used)

**Comment by alanpurple** [comment]
@pkozlowski-opensource 
ok, that, I never seen in my analysis

my bad, sorry

**Comment by pkozlowski-opensource** [comment]
@maxokorokov there is indeed change from 2.x.y to 4.x.y in the way changes are delivered  (see http://plnkr.co/edit/cyWm42UGEaJaaeDK95Eh?p=preview).

Having said this `currentValue` is `undefined` in _both_ cases so I'm not sure how it can work in 2.4.2....

**Comment by pkozlowski-opensource** [comment]
This is the reference to the Angular commit that breaks things for us: https://github.com/angular/angular/commit/465516b

Funnily enough it says in the [changelog](https://github.com/angular/angular/blob/master/CHANGELOG.md#breaking-changes): 

> SimpleChange now takes an additional argument that defines whether this is the first change or not. This is a low profile API and we don't expect anyone to be affected by this change. If you are impacted by this change please file an issue.

It would be good to dig to the bottom of it and eventually open an issue on the Angular side.

**Comment by Kamshak** [comment]
I was going to open a new bug report but it seems it's the same issue as this. Getting the same error if using 4.0.0-beta.3 with the Datepicker popup. 

Details:

### Bug description:
When using the Datepicker in a popup, it does not work when using model driven forms (i.e. FormGroup, FormBuilder) instead of ngModel. It seems that in ngOnChanges previousValue is accessed even if firstChange is set to true. 

Error:  

``` 
TypeError: Cannot read property 'year' of undefined
    at NgbDatepickerNavigationSelect.ngOnChanges (VM1176 ng-bootstrap.js:3250)
    at proxyClass.Wrapper_NgbDatepickerNavigationSelect.ngDoCheck (VM3407 wrapper.ngfactory.js:64)
    at View_NgbDatepickerNavigation_1.detectChangesInternal (VM3435 component.ngfactory.js:58)
    at View_NgbDatepickerNavigation_1.AppView.detectChanges (VM3490 core.umd.js:12718)
    at View_NgbDatepickerNavigation_1.DebugAppView.detectChanges (VM3490 core.umd.js:12864)
    at ViewContainer.detectChangesInNestedViews (VM3490 core.umd.js:12975)
    at proxyClass.View_NgbDatepickerNavigation_0.detectChangesInternal (VM3435 component.ngfactory.js:192)
    at proxyClass.AppView.detectChanges (VM3490 core.umd.js:12718)
    at proxyClass.DebugAppView.detectChanges (VM3490 core.umd.js:12864)
    at proxyClass.AppView.internalDetectChanges (VM3490 core.umd.js:12702)
```

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/7z6zTDbYPHUQHO8SmTUR?p=preview

### Version of Angular, UIBS, and Bootstrap

Angular: 4.0.0-beta.3

UIBS: 1.0.0-alpha.18

Bootstrap: 4.0.0-alpha.6

**Comment by pkozlowski-opensource** [comment]
I've discussed this breaking change with the rest of the Angular team and:
* yes, this is a breaking change; 
* it is unlikely that it is going to get reverted.

As the result we are going to work-around it here. A fix should land in the next release.
