### ISSUE TITLE
ngb-pagination: variable for collectionSize not working

### ISSUE THREAD

**Issue by yfindeis** [ng-bootstrap/ng-bootstrap#1219]
### Bug description:
If a variable is used for the attribute collectionSize, then only one page is displayed.

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/RsHCRmBZfezcpiv0ch5j?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.0.0

ng-bootstrap: 1.0.0-alpha.18

Bootstrap: 4.0.0-alpha.6

**Comment by pkozlowski-opensource** [comment]
For me the plunk works as expected. The `collectionSize` arguments says how many items that are in collection. Then `pageSize` (10 by default) controls of how many items are representing one page. In your case you've got 3/10 which is 1 when you round it. See what happens if you bump it up to 30: http://plnkr.co/edit/ADGtMRQClwEvifmUZeID?p=preview

I would suggest going again over docs at https://ng-bootstrap.github.io/#/components/pagination as I've got the impression that you are misinterpreting existing inputs and their functionality.

**Comment by yfindeis** [comment]
Oh, you're right. This was a misunderstandings of mine.
