### ISSUE TITLE
Tabs within tabs disappears and then reappears over and over

### ISSUE THREAD

**Issue by acSpock** [ng-bootstrap/ng-bootstrap#1234]
### Bug description:

When I use tabs inside tabs, the inner tab set disappears and then reappears over and over. I was able to get it working on plnkr but in my app this isn't working. 

Here's the plnkr that works with tabs within tabs

http://plnkr.co/edit/y9BRIxptjnaT7O4ChqmT?p=preview

NOTE: My app works when I take out the inner tab set.

### Link to minimally-working plunker that reproduces the issue:

I can't reproduce this in plnkr and was hoping to get some insight from the devs so I made a gif of the event here: http://www.giphy.com/gifs/l0Ex1KNmr1TQvTQ0U

Also when I inspect the dom it looks like the inner tabset is being created and then deleted and then being created and so forth.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.3.1

ng-bootstrap: 1.0.0-alpha.18

Bootstrap: 4.0.0-alpha.6

**Comment by pkozlowski-opensource** [comment]
This is due to a bug in Angular: 2.3.1. The mentioned bug seems to be fixed in 2.4.2. Compare those 2 plunks:
* 2.3.1: http://plnkr.co/edit/PoQeDoN8G8Pt9Ewh27xs?p=preview
* 2.4.2: http://plnkr.co/edit/EUgQbPt7m881VprvkItm?p=preview

Closing as this is due to the upstream bug which is already fixed. Upgrade your Angular version.

**Comment by acSpock** [comment]
Thanks for responding @pkozlowski-opensource
