### ISSUE TITLE
Dropdowns no longer work

### ISSUE THREAD

**Issue by bautistaaa** [ng-bootstrap/ng-bootstrap#1237]
### Bug description:
I just upgraded my app to angular 2.4.4
Everything seems to work but dropdowns and I do not get any errors at all. If I downgrade my app back to 2.4.1 things work as expected
### Link to minimally-working plunker that reproduces the issue:
Tried to fork your plkr but not sure how to upgrade to 2.4.4

I am literally just pasting the example from the site as follows into an empty html file.
`    <div ngbDropdown class="d-inline-block">
      <button class="btn btn-outline-primary" id="dropdownMenu1" ngbDropdownToggle>Toggle dropdown</button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenu1">
        <button class="dropdown-item">Action - 1</button>
        <button class="dropdown-item">Another Action</button>
        <button class="dropdown-item">Something else is here</button>
      </div>
    </div>`

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.4.4

ng-bootstrap: 1.0.0-alpha.18

Bootstrap: Bootstrap v4.0.0-alpha.6

**Comment by pkozlowski-opensource** [comment]
You can easily change Angular version in the `config.js` file in a plunk that can be forked from our demo page (https://ng-bootstrap.github.io/#/components/dropdown).

I just forked one plunk and it seems to be working perfectly fine: http://plnkr.co/edit/l4fO91D0f5FU9QEpUQmy?p=preview

If you can modify the above plunk to expose the issue we will investigate. Otherwise it is not actionable and will be closed.

**Comment by bautistaaa** [comment]
oh awesome never knew that. seems to be an issue on my end then. will close for now unless i can get it to replicate on plr thanks!

**Comment by redBaronNc** [comment]
Hello, I am having the same issue here, do you remember what was the problem causing it on your end bautistaaa?

**Comment by redBaronNc** [comment]
Oh it seems it was because I was using an older version of Bootstrap css files. Never mind :-)
