### ISSUE TITLE
View and model inconsistent - datepicker-input

### ISSUE THREAD

**Issue by sjcetx** [ng-bootstrap/ng-bootstrap#1278]
If the datepicker input model contains a `day: null` with a valid year and month the input placeholder is replaced with _year_-_month_-01 but the model is not changed to reflect the day displayed.
In my opinion either the date should not be displayed in the input box unless all three elements are valid or the model should also contain the default day of 1.

http://plnkr.co/edit/9sKNZOQVPbdOtRCDyypv?p=preview

ng-bootstrap@1.0.0-alpha.19
bootstrap@4.0.0-alpha.6
angular 2.3.1

**Comment by pkozlowski-opensource** [comment]
Agreed, current behavior is not not consistent. @maxokorokov this is due to https://github.com/ng-bootstrap/ng-bootstrap/blob/92674a6699cbf184aa726ae07e89274652184c82/src/datepicker/ngb-date.ts#L3

What is the reasoning for having `1` as a default value for a day?

**Comment by pkozlowski-opensource** [comment]
@maxokorokov I've sent #1279 but I fully understand that things need cleaning up deeper in the code as well. Based on this issue and previous discussions we should probably introduce a separate data structure that holds only year and month instead of trying to re-use `NgbDate` for things that don't represent valid dates.

**Comment by sjcetx** [comment]
Thanks for the quick fix!
