### ISSUE TITLE
Plans on merging with https://github.com/valor-software/ng2-bootstrap

### ISSUE THREAD

**Issue by vlodko** [ng-bootstrap/ng-bootstrap#1296]
You all are doing a great job, but it would much better if you can combine your efforts and create a single Angular 2 Bootstrap project.

What's your plans on that? Are there any discussions on possible merging ng-bootstrap and ng2-bootstrap?
We are in the point of choosing UI framework for our Angular 2 application and it's pretty hard to pick one.
Thanks in advance.

**Comment by Foxandxss** [comment]
There is none for the time being. The only common thing between both projects is the end goal (bs widgets) but everything else is different.

This project is made by one core team and a bunch of smart people. The goal is to make Angular better by forcing it to its limits and by doing that, improving the framework at the same time that this library is built.

The other goal they have (can't se we, my last commit was at least 3-4 months back) is to have the components fully tested. I can assure you that working with a datepicker can be the most painsome thing in the world and I can see that one of the projects has no tests for the datepicker.

Also, this team has been working on bootstrap components since 2012.

That being said, doors are open for collaborations.

I am closing this because this issue comes once per month.

**Comment by vlodko** [comment]
@Foxandxss thanks for reply!
I got your point.
