### ISSUE TITLE
Responsiveness nowhere to be found.

### ISSUE THREAD

**Issue by iSDP** [ng-bootstrap/ng-bootstrap#1317]
### Bug description:

Bootstrap is not responsive, the navbar doesn't collapse on smaller screens, and a multitude of things are not working as intended, mainly sibling stuff and whatnot.

Code can be found here: [Repository](https://github.com/iSDP/PostroutePlanner)

Image showing the problem: ![](https://i.imgur.com/7SMBmd2.png)

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.3.1

ng-bootstrap: current

Bootstrap: v4-alpha6

**Comment by jnizet** [comment]
It seems you submitted an issue of your application on ng-bootstrap instead of submitting it on your own project :-)

Bootstrap allows creating responsive apps, and so does ng-bootstrap, but this of course requires carefully crafted code: it won't happen automagically. 
Regarding the only concrete problem you're mentioning, the navbar, you can have a look at our demo (https://ng-bootstrap.github.io) to see that it can be made responsive and collapsible, by following the bootstrap documentation, and using the ngbCollapse directive.
See https://github.com/ng-bootstrap/ng-bootstrap/blob/master/demo/src/app/app.component.html for the source code.

**Comment by iSDP** [comment]
I've submitted an issue here, and shown an example of my own application.

I've followed the navbar example, which is seemingly not working :(

**Comment by jnizet** [comment]
It's working fine in our demo. So it must be a problem on your side, and not a bug of ng-bootstrap. To ask for support, post a question, with the relevant explanations **and code** (not just a link to your repo), and preferrably, a plunkr reproducing the issue, on StackOverflow. Github issues are for ng-bootstrap issues, not for support requests.

**Comment by JohnGalt1717** [comment]
Where's this demo of a responsive navbar that drops to a button and then expands/contracts when tapped on? It's not in the .io demos that I can find.
