### ISSUE TITLE
NgbModal dose not close If change the route page

### ISSUE THREAD

**Issue by purely-smile** [ng-bootstrap/ng-bootstrap#1318]
ng-bootstarp version:1.0.0-alpha.20

I think its a bug 。the modal only valid on current page. not other pages

**Comment by ASHFAQPATWARI** [comment]
@purely-smile You can always close the popup in ngOnDestroy event of your component.

**Comment by pkozlowski-opensource** [comment]
Based on experience with angular-ui/bootstrap we don't want to close modals automatically on route change. The reason is that some users want the opposite behaviour: blocking route change till the modal is open. Given 2 different use-cases we want to leave to the users the decission when and how a modal is opened and closed.

Closing as won't fix.

**Comment by purely-smile** [comment]
I understand, thank you

**Comment by zilions** [comment]
In my opinion, this would still be a great global setting. Hence, still leaving it to the users to decide. Your use case is valid, although some projects would still want modals to be closed on all route changes.

**Comment by jnizet** [comment]
Isn't it extremely unusual to change route while a modal is displayed?

 - if the route is changed because the user clicks on some link or button in the modal, then I find it quite natural to have that link or button close the modal first
 - if the route is changed because the user clicks on some link or button outside of the modal, then the backdrop will intercept the click and close the modal
 - it could be some background job changing the route without user interaction, but that's quite unusual, isn't it?

What scenario do you have in mind?

**Comment by kohoutjosef** [comment]
> it could be some background job changing the route without user interaction, but that's quite unusual, isn't it?

It can be for example automatic logout after idle.

**Comment by zilions** [comment]
@kohoutjosef - That's a very good example.

Here are some scenarios for why this is needed

- Models contain anchor links or buttons that go to another route. The modal will not close unless we link it to a function to first close the modal then go to the route. This is undesirable as it will have to be used multiple times for all instances.
- As @kohoutjosef states above, if a user has a modal open and leaves their device, many apps will have an automatic logout after an idle period. They'll then return to their device to see the login screen behind a modal that has nothing to do with that particular route. Sure, during this route change we can destroy the modal, but what if the app has many other redirects that are similar.

I think those two cases above are enough to argue this point.

**Comment by kohoutjosef** [comment]
Any chance to re-evaluate this issue?

**Comment by kohoutjosef** [comment]
Any chance to re-evaluate this issue?
