### ISSUE TITLE
template has been deprecated, need to change over to ng-template

### ISSUE THREAD

**Issue by wesleycho** [ng-bootstrap/ng-bootstrap#1337]
I took a peek at Angular 4.0.0-rc.1, and noticed messages that the `template` tag has been deprecated in favor of `ng-template` - this is a breaking change that will need to be scheduled sometime after Angular 4 goes live.

**Comment by somombo** [comment]
Hi there, 
I'd like to talk about some changes we can make in the meantime.

It seems a good a time as any, to discuss what seems to me to be over usage of `<template>`
through the ng-bootstrap project. 

I think it's not a very good sign, especially when even `ng-bootstrap` users are forced to use it, as is the case with `ngbSlide`. I think its possible to refactor this project in a manner that's more [idomatic to angular](https://angular.io/docs/ts/latest/guide/structural-directives.html#!#prefer-asterisk). 

Its often hard to follow `template` code and I'm not sure why it's being used so often where there are simpler and more conventional ways of expressing things.

 For example in places where there is:

```html
<template ngFor [ngForOf]="parts" let-part let-isOdd="odd">
```
 one could simply use,
```html
<ng-container *ngFor="let part of parts; let isOdd=odd">
```

And instead of `<template [ngIf]="seconds">`, the directive `<ng-container *ngIf="seconds">` should be used instead. 

Also, I think in alot of cases its also possible to do away with `<template [ngTemplateOutlet]="...">` in favor of somehow making use of `<ng-content>` or `<ng-container>` [(which is already officially encouraged in angular docs)](https://angular.io/docs/ts/latest/guide/structural-directives.html#!#ng-container).

I think this is an important step as each of the latter cases are already supported by both angular 2 and angular 4(+); whereas `<template>` is ng2 only and `<ng-template>` will be in ng4 only. So `template` (or even `ng-template`) should only be used as a last resort. And even if it is used for under-the-hood mechanics, I think front facing API shouldn't require one to use `<template>` as is the case in the carousel component.

In this spirit, I have put together a refactor of the carousel component with the above things in mind. I've removed `<template ngbSlide>` in favor of  `<ngb-slide>`  and gotten rid of the `template` throughout the carousel code. 

See https://github.com/somombo/ng-bootstrap/commit/39de0b6da559f9a467d35603d506aeb2ceece989

It is working (demo looks fine and gulp tests have passed)

Since it is refactored in a way that it should "just" work with both angular 2 and 4, my hope is that (even though this is a breaking change) we may discuss considering this (or a revised version) for PR without having to wait for stable angular 4 to go live. I thought I'd try talking about this with the carousel component before trying to potentially contribute code for refactoring some of the other components.

I'm open to all suggestions.
What do y'all think?
Thanks!

**Comment by somombo** [comment]
> @pkozlowski-opensource **in https://github.com/ng-bootstrap/ng-bootstrap/issues/1344#issuecomment-283048437:** 
you seem to be implying that there is a problem with using `<template>` / `<ng-template>` and I wholeheartedly disagree - usage of `<template>` / `<ng-template>` was / is conscious design decision that was discussed at length with Misko and material teams.


I just wanted to point out that  you mention the material team, as an example, I presume, of an authority that exemplifies the best practices for building  good quality angular libraries.. Yet there is not one single line of non-spec code in the [angular material 2](https://github.com/angular/material2)  lib where they use `<template>` ...  let alone using it to the extent that it's been used in this project.

If _even they_ were able to get by in that project without using `<template>` even once, why is it that this project could not? Are they solving the performance issues you mentioned in some sort of novel way that this project has not explored or thought about yet?

**Comment by pkozlowski-opensource** [comment]
Another update: number of logs for this case was trimmed down significantly on the Angular side via https://github.com/angular/angular/pull/15364 and once again, this is only debug-time warning.

We can't rename all the `<template>` occurrences to `<ng-template>` before we decide to require Angular 4.0.0 as a minimal version. IMO it is too soon to drop 2.3.x support so here is the plan: let's wait a couple of weeks till Bootstrap 4.beta is released and then we can cut a beta that bumps up Bootstrap and Angular dependencies.

For now there is no point of loosing sleep over this warning - we are aware of why it is logged and got a plan of update to 4.0.x

**Comment by pkozlowski-opensource** [comment]
Plan for the complete switch to Angular 4 here: #1439
