### ISSUE TITLE
Modals broken after upgrading to alpha-21

### ISSUE THREAD

**Issue by SlimDogs** [ng-bootstrap/ng-bootstrap#1389]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:

After version upgrade modals appear in the root of the whole page and ignore the `<template ngbModalContainer></template>` which is in the root component template file...

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.0

ng-bootstrap: "1.0.0-alpha.21"

Bootstrap: 4-alpha.6

**Comment by pkozlowski-opensource** [comment]
This is intentional, please consult the CHANGELOG: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CHANGELOG.md#100-alpha21-2017-03-15

You can use the new `container` option if you want modals to be attached to a particular element within DOM.

Closing as works as expected. Happy to re-open if you believe that some of your previous use-cases are not covered after 1.0.0-alpha.21

**Comment by SlimDogs** [comment]
Missed that... Sorry, thanks for the answer :)
