### ISSUE TITLE
Pagination: replace icons with text (suggestion)

### ISSUE THREAD

**Issue by thbt** [ng-bootstrap/ng-bootstrap#1427]
This is just a suggestion : replacing the pagination's boundary and direction links icons with text (First/Last and Previous/Next) could improve the UX design of this library. The idea is to clearly separate them from the page numbers.
Another thing to consider is to drop the First and Last links, as they are already present when using ellipses.

Here is a few blog post about pagination best practices for UX design : 
- [https://uxplanet.org/pagination-best-practices-76fbd3f5a78d](https://uxplanet.org/pagination-best-practices-76fbd3f5a78d) - items n°5 and 6
- [http://uxmovement.com/navigation/avoid-the-pains-of-pagination/](http://uxmovement.com/navigation/avoid-the-pains-of-pagination/)

**Comment by pkozlowski-opensource** [comment]
I'm reading through the linked articles (which seem like a copy of one another, btw) but based on my understanding those articles do _not_ advocate usage of text in place of symbols. Here are the relevant sections, IMO:

> In most cases, Previous and Next links are very useful for users. But, in order to create a decent pagination control, you should clearly separate them from the page numbers and give them sufficient distance or unique styling so that they can't be mistaken as a page; this is particularly pertinent if you use arrows instead of text for Previous and Next.

What is really says is that prev / next controls shell be _visually distinctive_, but not necessarily textual!  I kind of agree with this but:
* it would be more of an issue on the Bootstrap side
* users can configure pagination without prev / next controls and provide their own with whatever look & feel
* if anything we should rather think of allowing users to provide a template for each page cell.

Then the next relevant section would be:

> Some paginations have first and last links that allow users to skip to the first or last page. This is unnecessary and ususally confuses users. Sometimes the first and last links are displayed using double arrowheads, which users will often mistakenly click thinking it’s the single arrowhead link that takes them to the next page. Labeling the links “first” and “last” also causes clicking errors because of its proximity to the “next” and “previous” link.

This section just says _not_ to use first / last at all and clearly states that using text instead of symbols doesn't help at all. Once again, I don't think we are concerned since users can opt-out of those controls.

The final argument _against_ changing _defaults_ is that users can already change symbols to any text they like by translating templates. If anything, we should think of ways of providing custom templates for page cells (this is a long-term goal, not something to look into now).

Closing given all the above.
