### ISSUE TITLE
Popover shown event is raised when item is not visible and not exist in DOM

### ISSUE THREAD

**Issue by ste4net** [ng-bootstrap/ng-bootstrap#1440]
### Popover shown event is raised when item is not yet visible

[plnkr](http://plnkr.co/edit/W0MGSEidfYRAP8XQd6La?p=preview)

Angular: 2.4.8 
ng-bootstrap: 1.0.0-alpha.22
Bootstrap: 3.3.7

I was trying to use (only) one popover for an array of items. The idea was to place it near the last button pressed (i have a list of buttons). There is no way to modify the _elementRef or move the object to another place this is why i start looking to shown event, trying to directly access the DOM object.
But the event is fired when the item is not visible (it is not present in DOM).

**Comment by pkozlowski-opensource** [comment]
> But the event is fired when the item is not visible (it is not present in DOM).

That's not the case as you can [see here](https://github.com/ng-bootstrap/ng-bootstrap/blob/7d1dd9775a0807c90795c10eaea0f4182bb3b1b9/src/popover/popover.ts#L121) (emitting events is the last thing in the open method). BUT at the time you query the DOM the change detection didn't run yet, so classes are not set, so you can't query for them.

You can see that you can query the DOM if you use an element name instead: http://plnkr.co/edit/JX2PfxqczNiHoUNVsGDN?p=preview

> I was trying to use (only) one popover for an array of items. 

Why? Are there any particular reasons to do so? Quite frankly your code looks a bit hackish to me so maybe you should start by exposing a real-life use-case?

In any case this is a support request since events are emitted at the right time (the last point in time where it is technically possible)

**Comment by ste4net** [comment]
Sorry i was playing trying to use only one popover visible per time in a dyinamic list of buttons. Doing this i found issues and i guess it was related to shown event time. Plnkr was just to make a test with event.
Thank you i have to ask support for a better approach.
