### ISSUE TITLE
Popover: instance.open(ctx) : Context lost?

### ISSUE THREAD

**Issue by OClement** [ng-bootstrap/ng-bootstrap#1445]
### Bug description:
I am not exactly sure if this is a misunderstanding of what the context param is for or a bug, but have a feeling it's a bug from the look of it.

When passing context object to the `open` method, it seems to be ignored.
I would expect to be able to use { prop: 'value'} as context and have 'value' displayed in the <template>{{prop}}</template>

Am I wrong to think so, or missing something?

See Plunk for Use Case
Note: In my case, I want to pass the templateRef as an @Input to the component that will trigger the popover, but the same happens when used "normally". 

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/Ceesn5Z7ccZbtu1eaBh8?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:
Angular:
Plunk: 2.0.0
Local Project: 4.0.1

ng-bootstrap:
Plunk: Alpha 11
Local Project: Alpha 21

Bootstrap:
4-alpha.6

**Comment by pkozlowski-opensource** [comment]
You need to have the `let-name="name"` on the popover's template level, here is a plunk forked from our [demo page](http://plnkr.co/edit/4fD9a0jVbxMlVMSvzgO9?p=preview): http://plnkr.co/edit/4fD9a0jVbxMlVMSvzgO9?p=preview

You might also want to check the tests in the commit that introduced this feature: 87d569b99b1f66c32d375249f4a4ae475dbd572f

I won't fix your plunk since it is using a version from _before_ the context was introduced (available from 1.0.0-alpha.16). Why not forking plunks from our demo page?

Closing as a support request.

**Comment by OClement** [comment]
It does work indeed, thanks!

Sorry for the issue turning out to not being a bug

**Comment by pkozlowski-opensource** [comment]
> Sorry for the issue turning out to not being a bug

No worries @OClement , glad it worked for you!
