### ISSUE TITLE
Attempt to use a destroyed view: detectChanges

### ISSUE THREAD

**Issue by dennis82m** [ng-bootstrap/ng-bootstrap#1447]
I'm facing an issue after closing the active modal by using `NgbActiveModal.close()` which actually works fine. But if I want to reopen the modal I get the following error:

Attempt to use a destroyed view: detectChanges

which points to the `<template ngbModalContainer></template>`

**Comment by pkozlowski-opensource** [comment]
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

Also you must be running an older version of the library as the `ngbModalContainer` was [removed recently](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CHANGELOG.md#100-alpha21-2017-03-15).

As is (without live reproduce scenario in a plunker) this issue is not actionable and will be closed.

**Comment by pkozlowski-opensource** [comment]
Feel free to re-open if / when you've got a minimal reproduce scenario in a plunker or similar.
