### ISSUE TITLE
modal not working with angular 4

### ISSUE THREAD

**Issue by faisalloe** [ng-bootstrap/ng-bootstrap#1453]
just upgrade my project to latest version of angular, notice ng-modal is not getting displayed. do we know when this is going to get fix ?

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.0.1

ng-bootstrap:1.0.0-alpha.22

Bootstrap:3.3.7

**Comment by pkozlowski-opensource** [comment]
* please follow our issue template when submitting bug reports: https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug
* work perfectly fine for me here: http://plnkr.co/edit/LITQXFzZE7ETnTSH9nSP?p=preview
* we support only Bootstrap 4 only (that is, it won't work with 3.3.7)

I _suspect_ that you are using an incompatible Bootstrap CSS version but impossible to say more without a minimal reproduce scenario in a plunker. Without it this issue is not actionable and will be closed.

**Comment by faisalloe** [comment]
sorry i confirmed wtih bootstrap 4 it works, bootstrap still in alpha version i don't want to use it yet. do you know what bootstrap version less then 4 modal with angular4 may work ?

**Comment by pkozlowski-opensource** [comment]
> bootstrap still in alpha version i don't want to use it yet

I would reconsider. See: https://github.com/ng-bootstrap/ng-bootstrap/wiki/Why-Bootstrap-4-only%3F

> do you know what bootstrap version less then 4 modal with angular4 may work ?

None. You might have to downgrade to ng-bootstrap alpha.17 as _some_ things _might_ work with Bootstrap 3 (https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CHANGELOG.md#100-alpha17-2017-01-09)

Going to close this one as a problem is well identified and as stated above we don't support Bootstrap 3.x (note that even Bootstrap itself don't support it any more, that is, there are no fixes nor new features happening for this version....)
