### ISSUE TITLE
How to pass a binding variable to a modal?

### ISSUE THREAD

**Issue by jrmcdona** [ng-bootstrap/ng-bootstrap#1460]
I am trying to create a modal that starts out with a spinner while a service is updating a database.
Once the service completes, I will stop the spinner and display a dynamic message about the object that was updated by the service.

I have the modal working.   But not of my variable values seem to update.    I don't seem to think the binding is automatic.  

I am using the standard component modal.  Just trying not to pass hard coded strings to the modal.

Anyway to solve this?

**Comment by wesleycho** [comment]
Can you whip up a Plunker demonstrating your basic scenario?

One thing that I have found that sometimes needs to be done from personal experience is having to utilize `ChangeDetectorRef.prototype.markForCheck` if updates were started from a different component. This has to do with how [change detection works](https://blog.thoughtram.io/angular/2016/02/22/angular-2-change-detection-explained.html) in Angular, since the component that the modal is attached to is likely on a different part of the component tree from the one that initiated the service call.

**Comment by rugarcialopez** [comment]
@jrmcdona Have you solved your issue??I have the same issue

**Comment by pkozlowski-opensource** [comment]
I'm going to close this one as we haven't heard from @jrmcdona and I'm clear what the real problem is without a minimal reproduce scenario.
