### ISSUE TITLE
Datepicker's initial invalid property is 'true' on non-required input

### ISSUE THREAD

**Issue by critchie** [ng-bootstrap/ng-bootstrap#1504]
### Bug description:
The Datepicker invalid property is initially set to true on an input not marked with 'required'.  This keeps me from creating a form where the Datepicker is an optional value in the form.  In the plnkr I would expect the Submit button to enable once a value is entered into the Event Name field but it remains disabled.  I have to enter a valid value in the Datepicker field as well.

I would expect the Datepicker to work like other inputs that are not marked as required.  That is, if the input is not marked as required then the initial state should be invalid=false (and valid=true).

### Link to minimally-working plunker that reproduces the issue:
https://embed.plnkr.co/z0VPswkNSjerqQQ4ckB1/

### Version of Angular, ng-bootstrap, and Bootstrap:
See plnkr.

**Comment by pkozlowski-opensource** [comment]
It is because you are initialising the datepicker field with with an empty string (`''`) which is definitively not valid date (as expected by the datepicker), thus the field is marked as invalid. Try initialising the field with `null` / `undefined` and you are going to see that it works as expected.

Going to close this one as "works as expected".

**Comment by critchie** [comment]
Perfect.  Thanks.
