### ISSUE TITLE
Build with Closure compiler 

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/ng-bootstrap#1596]
This issue is here to track all the necessary changes in this library to make it work with the closure compiler with the least pain possible. 

My current understanding is that require changes, so far, boil down to "stringifying" property access in some objects.

**Comment by dmitrysteblyuk** [comment]
I'm currently using ng-bootstrap with closure compiling. I found some issues with Modal, Dropdown, Datepicker components and util/positioning.
I had to add some externs because of those issues (like accessing components inputs or object properties using quotes syntax whereas those properties where defined without quotes). Here they are:

var NgbModalRef = function () {};
NgbModalRef.prototype.componentInstance;

var NgbDropdown = function () {};
NgbDropdown.prototype.toggleElement;

// util/positioning.js

var shiftWidth = function () {};
shiftWidth.prototype.left;
shiftWidth.prototype.center;
shiftWidth.prototype.right;

var shiftHeight = function () {};
shiftWidth.prototype.top;
shiftWidth.prototype.center;
shiftWidth.prototype.bottom;

var NgbDatepicker = function () {};
NgbDatepicker.prototype.dayTemplate;
NgbDatepicker.prototype.displayMonths;
NgbDatepicker.prototype.firstDayOfWeek;
NgbDatepicker.prototype.markDisabled;
NgbDatepicker.prototype.minDate;
NgbDatepicker.prototype.maxDate;
NgbDatepicker.prototype.navigation;
NgbDatepicker.prototype.outsideDays;
NgbDatepicker.prototype.showNavigation;
NgbDatepicker.prototype.showWeekdays;
NgbDatepicker.prototype.showWeekNumbers;

var NgbDatepickerInput = function () {};
NgbDatepickerInput.prototype.dayTemplate;
NgbDatepickerInput.prototype.displayMonths;
NgbDatepickerInput.prototype.firstDayOfWeek;
NgbDatepickerInput.prototype.markDisabled;
NgbDatepickerInput.prototype.minDate;
NgbDatepickerInput.prototype.maxDate;
NgbDatepickerInput.prototype.navigation;
NgbDatepickerInput.prototype.outsideDays;
NgbDatepickerInput.prototype.showNavigation;
NgbDatepickerInput.prototype.showWeekdays;
NgbDatepickerInput.prototype.showWeekNumbers;

**Comment by dmitrysteblyuk** [comment]
Moreover there's a bug with compiling NgTemplateOutlet in angular. I'm filing an issue now. Because of this bug I also added following externs:

var context = function () {};
context.prototype.date;
context.prototype.selected;
context.prototype.disabled;
context.prototype.currentMonth;

var date = function () {};
date.prototype.day;
date.prototype.year;
date.prototype.month;

**Comment by pkozlowski-opensource** [comment]
So it turns out that the support for closure compiler is trickier than expected due to combination of 2 Angular issues around `ngTemplateOutlet`:
* angular/angular#14292
* angular/angular#13407

angular/angular#14292 is fixed now but not released yet. We will have to bump up Angular dependency to have proper closure compiler support.

**Comment by aitboudad** [comment]
for the build part I suggest you to use https://github.com/dherges/ng-packagr

**Comment by pkozlowski-opensource** [comment]
Closing in favour of #1474 - we are going to migrate to Angular CLI and follow whatever CLI mandates for building libraries output.
