### ISSUE TITLE
Allow component routing for NgbTabset

### ISSUE THREAD

**Issue by tilowestermann** [ng-bootstrap/ng-bootstrap#1632]
### Bug description:

I'd like to load different components using the tab set. These components should be accessed by their URL. 
Currently, I see two ways of achieving this:
1. Provide a link with a `routerLink` in the `ngbTabTitle` template
2. Use the `tabChange` event and tell the router to navigate.

[Option 1](https://stackoverflow.com/a/41592058/184245) has the drawback that routing only happens if the title is clicked (not the tab)

[Option 2](https://stackoverflow.com/a/44717581/184245) doesn't allow for copying the link when hovering it

While both options may achieve the desired result, I think there should be a better way (e.g., without adding an empty `ngbTabContent` template).

### Link to minimally-working plunker that reproduces the issue:

See links provided for Option 1 and 2.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.x

ng-bootstrap: 1.0.0-alpha.26

Bootstrap: v4.0.0-alpha.6

**Comment by chuckconway** [comment]
I second this issue.

**Comment by suchinb** [comment]
I am still facing the issue, I am using routerLink in ngb-tab tag, But when I click it does not navigate , but If I use the simple buttons it navigates, 

<ngb-tab title="Simple" [routerLink]="['./nestedChild1']">

**Comment by chuckconway** [comment]
I'm not sure if this will help, but I create a post on StackOverflow how I got tab navigation working. 

https://stackoverflow.com/questions/42446434/how-can-i-access-the-select-method-from-ngbtabset-in-the-component-in-angular2/44940187#44940187

**Comment by masiorama** [comment]
Is it going to be handled in the next future? I'm trying to achieve the same result and none of the two options proposed by the opener are perfect. 
Thanks in advance.

**Comment by divdavem** [comment]
For info, I have opened PR #2603 to implement this feature request.
What do you think about it?

**Comment by dries-2002** [comment]
I've run into the same problem, and instead of trying to get the ngb-tabset to behave like a navbar, I refactored it into a navbar. This effectively solves the routing problem.

The key is to create a wrapper component, and to define the tabs as children in the routing. Don't forget to add the `<router-outlet>` tag in the wrapper component.

**Comment by kashpatel** [comment]
For anyone who come looking for solution on how to make routing works with ng-bootstrap tabs. I have made an example app to demonstrate that. I used secondary router outlet for to render tab component.

See the demo here:
https://stackblitz.com/edit/ng-bootstrap-routable-tabs

And code here:
https://github.com/kashpatel/ng-bootstrap-routable-tabs

**Comment by rtvalluri** [comment]
Quick fix :

Incase you are using ng-template for routerlink like below : 

`<ngb-tabset #tabset="ngbTabset">`
       `    <ngb-tab id="tab1">`
           `<ng-template ngbTabTitle>`
                `<a class="btn-link" [routerLink]="['./nestedRoute1']">Tab1</a>`
            `</ng-template>`
        `</ngb-tab>`
        `<ngb-tab id="tab2">`
          `  <ng-template ngbTabTitle>`
              `  <a class="btn-link" [routerLink]="['./nestedRoute2']">Tab2</a>`
            `</ng-template>`
        `</ngb-tab>`
    `</ngb-tabset>`

And facing problem like routing only happens if the title is clicked (not the tab), try removing padding for the outer anchor tag and make the inner anchor tag i.e btn-link in the above code as inline-block and provide padding to it.

Thus any click on the tab will correspond to inner anchor tag with router link.

**Comment by maxokorokov** [comment]
Since version `5.2.0` there is a new `NgbNav` set of directives that **should** fix this issue. `NgbNav` is meant to replace the `NgbTabset` component (completely deprecated in version `6.0.0`) as a more flexible alternative.

I suggest you migrate to it → https://ng-bootstrap.github.io/#/components/nav/overview

**Comment by BrunoElo** [comment]
Please I need a demo of how the `NgbNav` works because I can't seem to understand how to make the router-outlet show the contents. Thanks

**Comment by andresxz32** [comment]
I add a solution that worked for me based on what was commented by  @rtvalluri 
<--HTML FILE -->
<ngb-tabset [activeId]="activeTab()" #tabset="ngbTabset">
        <ngb-tab id="tab1">
          <ng-template ngbTabTitle>
            <div class="divLink" [ngClass]="{'text-dark': activeTab() === 'tab1'}" [routerLink]="['campaigns']">
              <i class="mdi mdi-shopping"></i>
              {{'shared.sidebar.campaigns'
              | translate}}
            </div>
          </ng-template>
        </ngb-tab>
        <ngb-tab id="tab2">
          <ng-template ngbTabTitle>
            <div class="divLink" [ngClass]="{'text-dark': activeTab() === 'tab2'}" [routerLink]="['notifications']">
              <i class="mdi mdi-bell"></i>
              {{'shared.sidebar.notifications' | translate}}
            </div>
          </ng-template>
        </ngb-tab>
      </ngb-tabset>

<router-outlet></router-outlet>

<--TS OR CSS FILE -->
  styles: [`
  ::ng-deep .nav-link { width: 140px; padding: 0;height: 40px; }
  .divLink { height: 100%;display: flex;justify-content: center;align-items: center;}`
  ]
