### ISSUE TITLE
Datepicker not clickable when used at the same page with Highcharts

### ISSUE THREAD

**Issue by aliosss** [ng-bootstrap/ng-bootstrap#1654]
### Bug description:
Hello,
I ran into a weird issue that days are not clickable when I used ng-bootstrap datepicker with Highcharts on the same page. 
I did some investigation to find the root cause but no luck. Maybe you have an idea?

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/KHyB5oP7lLGPjC1dG97j?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.1.2

ng-bootstrap: 1.0.0-alpha.27

Bootstrap: 4.0.0-alpha.6

**Comment by maxokorokov** [comment]
Hey @aliosss,

You would not want to use highcharts or any other external library this way. What you're doing is starting it inside the angular zone, so all event handlers would trigger angular change detection.

Check the number of change detections that are triggered and try uncommenting lines with:
http://plnkr.co/edit/VyOeKxtMVVAvFZvid6RH?p=preview

So I would suggest you find a proper wrapper for highcarts for angular or use it outside the angular zone.

P.S. I think there is also a small issue introduced in alpha.26-27 that triggers datepicker DOM nodes recreation. Though, it should be fixed with the next ng-bootstrap release. But your problem will go away if you just use highcharts properly

**Comment by Nelladel** [comment]
Apologies for re-opening a thread, but I opened a Stack Overflow question about this very same issue just yesterday: 

https://stackoverflow.com/questions/45021000/angular-3rd-party-library-interaction

Could you tell me if it's exactly the issue you were encountering? 

I'll read up on zone-control while using highcharts! Thanks a lot!

**Comment by pkozlowski-opensource** [comment]
@Nelladel as others commented on the SO thread there is _nothing_ we can do without a _minimal_ reproduce scenario in a plunker. Take time to isolate the problem, we can't help otherwise (and I doubt anyone could).

**Comment by Nelladel** [comment]
@pkozlowski-opensource From @maxokorokov 's answer given to @aliosss , I have modified my code and it is now working properly. I understand the difficulty of just receiving a question without too much information, but I was really bashing my head against the wall here (don't really have a firm grip on zone-handling). Apologies.

Thank you all. :)

**Comment by aliosss** [comment]
@Nelladel It seems you are having the same issue I had. The only difference is that, I was using Highcharts without an angular wrapper and you are using angular2-highcharts. 

I would expect angular2-higcharts to properly handle zone, but it seems high number of change detections problem even gets worse. I opened an issue a couple of days ago https://github.com/gevgeny/angular2-highcharts/issues/208 . Although this specific problem occurs because of 2 issues (datepicker DOM nodes recreation issue as @maxokorokov mentioned and high number of change detections), number of change detections should be taken care of in order to get a decent performance.
