### ISSUE TITLE
Dropdown Component (may be others) don't work in web worker

### ISSUE THREAD

**Issue by varghesep** [ng-bootstrap/ng-bootstrap#1666]
### Bug description:

I have an Angular 4 app that uses ```platform-webworker-dynamic``` to run it in a worker thread. The app uses a ```ng-bootstrap Ngbdropdown```. I can click the drop down and see the drop down menu, but when I click anywhere on the browser, I see the message:  

```products.html:6 ERROR TypeError: this._toggleElement.contains is not a function
    at NgbDropdown._isEventFromToggle (ng-bootstrap.js:3494)
    at NgbDropdown.closeFromOutsideClick (ng-bootstrap.js:3477)
    at Object.eval [as handleEvent] (products.html:6)
    at handleEvent (core.umd.js:12079)
    at callWithDebugContext (core.umd.js:13540)
    at Object.debugHandleEvent [as handleEvent] (core.umd.js:13128)
    at dispatchEvent (core.umd.js:8691)
    at Array.eval (core.umd.js:9302)
    at NamedEventEmitter.dispatchEvent (platform-webworker.umd.js:1926)
    at WebWorkerRendererFactory2._dispatchEvent (platform-webworker.umd.js:2032)
```

### Link to minimally-working plunker that reproduces the issue:

Use this [example ](https://github.com/kaikcreator/angular-cli-web-worker)app to create an app.

Use the following code in ```ng-bootstrap.js``` to log the ```ngbDropdownToggle``` element.

```Object.defineProperty(NgbDropdown.prototype, "toggleElement", {
/**
* @internal
*/
set: function (toggleElement) { this._toggleElement = toggleElement; console.log(toggleElement); },
enumerable: true,
configurable: true
});
```

When I uses ```platform-browser-dynamic``` single threaded app, I see the following button element:

![image](https://user-images.githubusercontent.com/12233474/27984739-ea0e34ac-63a2-11e7-9c85-65c345c39d9e.png)

When I use ```platform-webworker-dynamic```, I see the following node:

![image](https://user-images.githubusercontent.com/12233474/27984836-83b86602-63a5-11e7-9a16-ac79bfedeb08.png)

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.2.5
ng-bootstrap: 1.0.0-alpha.27
Bootstrap: Bootstrap 4.0.0-alpha.6

UPDATE:

I assume the reason why the ```_toggleElement``` is not a button when ```platform-webworker-dynamic``` is used is due to the Angular components will not have access to the DOM in the web worker mode.

**Comment by pkozlowski-opensource** [comment]
WebWorker support poses a completely new set of challenges and at the moment we are not testing in the web worker environment.  We might come back to the topic post 1.0 but don't expect anything to happen here before 1.0 (unless someone from the community steps in and helps out, of course).

**Comment by AnimaMundi** [comment]
I'd imagine the issue with this is calling methods directly on DOM objects.

```
isEventFrom($event) { return this._elementRef.nativeElement.contains($event.target); }
```

This would have been easy to fix with Angular 2 as the `invokeElementMethod` method could be used from the renderer, but this is deprecated now and no longer guaranteed to work in Web Workers. The current advice from the Angular team is to create your own "mini-renderer" to handle these cases in different environments.

https://github.com/angular/angular/issues/13818
https://github.com/angular/angular/issues/15008#issuecomment-285141070

The Angular team themselves even say that their support for Webworkers is still experimental, having said that I would like to work on this anyway.

Personally, I'm not a fan of listening to DOM events globally on the document in order to implement 'click outside to close' functionality. `'(document:click)': 'closeFromClick($event)'`. I think global event handlers (global anything for that matter) should be avoided.

My suggestion would be to implement native Angular event handlers using the `(click)="onMenuClicked()"` syntax on the individual elements that we are concerned about. To close the dropdown from clicking outside of it, an invisible backdrop could be created behind (underneath?) the dropdown and add an event handler there.

@pkozlowski-opensource any thoughts on this? If you agree with this approach, I'd be happy to make a pull request.

**Comment by pkozlowski-opensource** [comment]
@AnimaMundi sorry for the late response, somehow I've missed your comment!

I agree that current "global" (document-level) event handlers are problematic (not only for web-worker) but also for other reasons (ex. perf - see: #900 and associated issues). So I would be keen on working on a better "close on outside clicks" system. Inserting an invisible backdrop would be one way of doing this, an alternative is present in the PR #1863.

Having said this all, I think that the web-worker story is kind of lost cause for dropdowns (and other widgets) as we need access to the native DOM api for other reasons (positioning, "append to body", ...). Given this and the fact that web-worker story is not finished on the Angular side, I'm going to call it a day and state that **we've got no intention of supporting web-workers for ng-bootstrap** until new technical information surface.

I'm going to close this issue based on the above explanations but would love to work with you @AnimaMundi on getting rid of the global event handlers and having a better "click outside" story. Let's move this particular discussion to #900

**Comment by rolaveric** [comment]
I've managed to refactor the dropdown component to work with `platform-webworker`.
The key problems were:
1. `nativeElement.parentNode` will be undefined in a Worker
2. `nativeElement.contains()` will be undefined in a Worker
3. `$event.target` will be undefined in a Worker
4. Pretty much everything in `util/positioning` won't work in a Worker

My solutions were:
1. Use `ElementRef` from `[ngbDropdown]`, as it's generally the parent anyway (but I assume this is a regression for some use cases?)
2. I created a `DomAccessor` (not attached to the name - best I could think of) service that lets you call `contains(hostElement, targetElement)`, which can then be overridden with DI on a per-platform basis. So `platform-browser` uses `hostElement.contains(targetElement)`, but `platform-webworker` will message the UI thread to call the same `platform-browser` service, and then return the result, via a promise.
3. Rather than using `host` property on the `@Directive()`, I used `@HostListener()` which lets you pass in an array of the specific properties you want pulled from the event. eg. `@HostListener('document:click', ['$event', '$event.target'])`, where the second param will be a "render store object" that can be used by `Renderer2` and passed as a reference across the UI-Worker divide.
4. Everything in `util/positioning.ts` I wrapped up into an injectable service that can be overridden per platform - same deal as `DomAccessor`. So on `platform-browser` it's exactly the same. On `platform-webworker`, it messages a service on the UI that then talks to the `platform-browser` version.

I'm working on getting a minimalist demo published on github, separate from my other work.
Hoping I can use it for testing other UI components, and maybe act as a template for others who want to try out `platform-webworker`.

Question is: Do you want a PR?
I think all the changes, with the exception of the `DomAccessor`, are totally benign to introduce to the codebase without ever having to mention `platform-webworker` - let devs add in those extra pieces if they're really keen.
Though I get it if you don't want to make changes purely to support `platform-webworker` - a totally experimental feature of Angular with almost no support.
But adding support in UI component libraries, like ng-bootstrap, would definitely help it gain traction.
