### ISSUE TITLE
Prepare for Bootstrap v4 beta

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/ng-bootstrap#1679]
Bootstrap v4 beta seems to be round the corner and we need to asses impact on the existing widgets as well as the documentation site.

### Widgets (tested with https://github.com/twbs/bootstrap/commit/b14c5cc4b8c23c5630d2520cab7e5d8ef1556049)
* [x] - accordion => update to the new cards markup
* [x] - alert
* [x] - buttons
* [x] - carousel
* [x] - collaps
* [x] - datepicker
  * `btn-secondary` => `btn-light`?
* [x] - dropdown
  * [ ] - `dropup` is no longer the thing as poper.js is used for positioning
  * needs to use positioning service?
* [x] - modal
* [x] - pagination
* [x] - popover
  *  [x] `popover-title` => `popover-header`
  *  [x] `popover-content` => `popover-body`
  *  [x] add `arrow` element
  *  [x] positioning is off for the `top` and `left` cases 
* [x] - progresssbar
* [x] - rating
* [x] - tabset
* [x] - timepicker
* [x] - tooltip
* [x] - typeahead

### Demo
* [x] - update responsive classes
* [x] - component doc pages
  * [x] `API` / `Examples` titles need class update when selected
  * [x] there is not enough "breathing room" in example cards (margins) => probably card structure change

### Cleanup
* [x] remove temporary reference to the Bootstrap CSS from RawGit

**Comment by samuelsiau** [comment]
- datepicker
--positioning? please
- dropdown
-- positioning. YES please
- popover
-- positioning. Yes please
-- clickoutside and close?

**Comment by jnizet** [comment]
I'm reading the doc of Bootstrap v4-beta, and noticed that there are more types of alerts than before, that we should support too: 

 - primary
 - secondary
 - light
 - dark

**Comment by jnizet** [comment]
I'm also wondering if we should use popper.js to position our tooltips and popovers like bootstrap now does. I have no idea if it's possible or if it's a good idea, but I guess it could make our job simpler, and make the behavior of our components similar to the behavior of bootstrap's native components.

**Comment by jnizet** [comment]
I could help, at least for the alert thing. Is there a branch I can base my changes on, which would at least change the bootstrap dependency?

**Comment by pkozlowski-opensource** [comment]
> I'm reading the doc of Bootstrap v4-beta, and noticed that there are more types of alerts than before

I don't think that we've got much to do (maybe besides updating docs), as we are ready to support many types: 
https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/alert/alert.ts#L35

To be tested of course and update / amend if needed.

> I'm also wondering if we should use popper.js to position our tooltips and popovers like bootstrap now does. I have no idea if it's possible or if it's a good idea, but I guess it could make our job simpler, and make the behavior of our components similar to the behavior of bootstrap's native components.

I don't think so. I had a look a poper.js at some point and it does way too much + is very much DOM-centric. But I'm also open to be convinced other way around!

> I could help, at least for the alert thing. Is there a branch I can base my changes on, which would at least change the bootstrap dependency?

There is a beta-compatibility branch: https://github.com/ng-bootstrap/ng-bootstrap/tree/bootstrap4_beta

The only remaining thing is to have dropdowns fixed, I've got PR in the works.

What would help the most, at this point is bumping up Bootstrap depenency version in https://github.com/ng-bootstrap/ng-bootstrap/tree/bootstrap4_beta and reviewing the demo site to make sure that everything is in order. Also this PR needs review: https://github.com/ng-bootstrap/ng-bootstrap/pull/1733

**Comment by jnizet** [comment]
I went through all the demos, and, besides dropdowns that are broken, I found two issues:

 - a minor vertical spacing issue for which I submitted the PR #1742 
 - a more serious issue with the custom validation demo of the timepicker. Bootstrap apparently completely changed how validation works. A CSS class must now be added on the inputs themselves, and the has-danger, has-success and form-control-feedback classes have disappeared. I have no clear idea how we can apply custom validation classes to inputs inside the template of the timepicker with this new way of doing.

**Comment by pkozlowski-opensource** [comment]
Good catch on timepciker @jnizet ! Would you have free cycles to dig a bit deeper into timepickers? I'm just opening a PR for dropdowns and will start merging your PRs soon!

**Comment by jnizet** [comment]
I submitted an additional PR that displays green/red validation feedback, in the timepicker, typeahead and rating demos.

But to add the appropriate border to the timepicker input fields, I don't see any nice solution. I also have the feeling that the painting isn't really dry on the bootstrap side, because we lost many functionalities with that change: no icons anymore, no color applied to labels anymore, no warning state anymore. 

- we can't AFAIK add CSS rules for the inputs of the timepicker in the demo, since due to isolation, the rules wouldn't apply. Even if we could, we would have to duplicate bootstrap CSS
- we could add a global css rule to the demo css. But once again, we would have to duplicate bootstrap CSS.
- to avoid duplicating bootstrap css, we would need to add .is-invalid to the inputs, in the timepicker component itself. But we can't make that choice on behalf of the user: maybe it should be set when the control is invalid. Maybe it should be set when it's invalid and touched. Or when it's invalid and dirty. 

So my guess is that the least ugly solution, if bootstrap doesn't let us reuse the old .has-danger classes, would be to add an input to the timepicker. Something like

    <ngb-timepicker [invalidWhen]="ctrl.dirty && !ctrl.valid" .../>

that would add the .is-invalid bootstrap class to the inputs based on a condition chosen by the user. But then we should do the same for .is-valid.

**Comment by pkozlowski-opensource** [comment]
@jnizet I'm going to merge your PR and cut first beta. All your points about Bootstrap 4 validation are ... valid but AFAIK there is more work in the pipe for subsequent betas. Let's see how things evolve on the Bootstrap side and then decide.
