### ISSUE TITLE
Reactive form demos of checkbox and radio buttons don't open in plnkr

### ISSUE THREAD

**Issue by jnizet** [ng-bootstrap/ng-bootstrap#1714]
The two reactive forms demos of the buttons module don't open in plunkr. They result in a 404.

The datepicker range demo opens in plunkr, but throws an exception.

**Comment by maxokorokov** [comment]
```typescript
export const DEMO_SNIPPETS = {
  'radioReactive': {
    'code': require('!!prismjs-loader?lang=typescript!./radio-reactive/buttons-radio-reactive'),
    'markup': require('!!prismjs-loader?lang=markup!./radio-reactive/buttons-radio-reactive.html')}
};
```

Haven't been digging into how Plnkr generator works, but in the example above to avoid 404 → `radioReacive` key should become `radio-reactive`. However in this case in the plunkr it will try to use `NgbdButtonsRadio-reactive` component, because too much dashes in the name (?)

So my guess is the solution would be either fixing plnkr generation or renaming demos to `buttons-radioreactive` and `buttons-checkboxreactive`
