### ISSUE TITLE
Support for old version of Bootstrap CSS(3.0.0)

### ISSUE THREAD

**Issue by gnranjith** [ng-bootstrap/ng-bootstrap#1818]
### Description:
I am writing this post for suggesting the support of Bootstrap CSS version of 3.0.0. If this is done then the app will be supporting more older versions of browsers when compared to Bootstrap 4.

For this support we will need to change few classes in the source code of ng-bootstrap. Please suggest your views about this.

**Comment by pkozlowski-opensource** [comment]
Sorry, we are not going to support Bootstrap 3, here is why: https://github.com/ng-bootstrap/ng-bootstrap/wiki/Why-Bootstrap-4-only%3F

**Comment by gnranjith** [comment]
@pkozlowski-opensource Thanks for the quick turnaround. I appreciate your help!

**Comment by gnranjith** [comment]
@pkozlowski-opensource I am planning to work on converting the code to be bootstrap 3.0 compliant. I know this is a very general question but could you please let me know how I can publish it as a separate NPM package similarly like how ng-bootstrap is done?

**Comment by pkozlowski-opensource** [comment]
@gnranjith if you are serious about adding Bootstrap 3 support I would rather prefer that you contribute to this repository instead of forking and further fragmenting community around Bootstrap widgets for Angular. Be warned though, it is a lot of work, from my experience (in the order of several man / years for the initial code and maintenance).

**Comment by gnranjith** [comment]
I sent out a mail to below mail ID pkozlowski.opensource@gmail.com

Could you please revert back?
