### ISSUE TITLE
ng-bootstrap Datepicker, The calander image do i need to add  manually. we are not supposed to do that due to some security constraints, is there a possibility like as an glyphicons.

### ISSUE THREAD

**Issue by when-cut** [ng-bootstrap/ng-bootstrap#1862]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Link to minimally-working plunker that reproduces the issue:

You can fork a plunker from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.
Please note that we can _not_ act on bug reports without a minimal reproduction scenario in plunker. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular:

ng-bootstrap:

Bootstrap:

**Comment by pkozlowski-opensource** [comment]
Not sure what you mean by "we are not supposed to do that due to some security constraints" but it s is by design that you need (or I would rather say - can) add calendar image yourself. This is by design as we believe that users should be free to use whatever image / text they want.

In the future please follow the issue template we've got here.
