### ISSUE TITLE
Can I use bootstrap's grid system in ng-bootstrap?

### ISSUE THREAD

**Issue by Lsy-kg** [ng-bootstrap/ng-bootstrap#1873]
please answer me, thanks!

**Comment by pkozlowski-opensource** [comment]
Of course. ng-bootstrap just builds on top / uses Bootstrap's CSS so you can use all the features of the original CSS. ng-bootstrap just replaces JS part of Bootstrap. You still use original CSS.

**Comment by ZackAfro** [comment]
Hi, Just to make sure I understand correctly, must I still add standard Bootstrap to my application as well in order to use like the Grid system and useful classes like the margin and padding classes or is this included already in ng-bootstrap? Because in the documentation I see the do not recommend adding standard bootstrap, but I cant find an grid css in ng-bootstrap.

**Comment by mendeza** [comment]
Hi Neil. Yes, you should add [standard Bootstrap](https://github.com/twbs/bootstrap) to your application. In fact, you **must** do so to use their CSS. However, you must **not** use their jQuery code. That part is replaced by ng-bootstrap. This is the entire raison d'être of the ng-bootstrap project.

**Comment by ZackAfro** [comment]
Okay cool, I figured so. Thanks. Wasn't very clearly stated anywhere.

**Comment by BekirUzun** [comment]
I was getting an error while I trying to build an Electron - Angular and NG Bootstrap app. 
```
Error: Unresolved node modules: jquery, popper.js
    at D:\Code\electron\project\node_modules\electron-builder\node_modules\app-builder-lib\src\util\packageDependencies.ts:112:21
```
I resolved that issue by adding CSS only version of Bootstrap from here: https://github.com/fyockm/bootstrap-css-only
