### ISSUE TITLE
Dynamically deleting a tab, reload the app

### ISSUE THREAD

**Issue by natcohen** [ng-bootstrap/ng-bootstrap#1909]
### Bug description:
Deleting a tab, reloads the app. Try the plunker below and close a tab, the app will reload (tested in Chrome)

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/CBAO8VtehUprqcVzClmV

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.4.6

ng-bootstrap: 1.0.0 beta5

Bootstrap: v4beta

**Comment by pkozlowski-opensource** [comment]
Yeh... So what is going on here is that your `<span>` with the close button ends up in a link `<a>` tag with an empty `href`. When you click on a span the link tag picks up a click and since we've got an empty `href` a page gets reloaded.

No, the problem wouldn't exist if not an empty `href`, but we are forced to have it due to Bootstrap's markup / CSS. I'm not sure we can fix it and at present I don't see any good solution on the library side. For now I would suggest calling `preventDefault()` on your `<span>`: http://plnkr.co/edit/gIv38E9mcTjUYFSVl2RF?p=preview

**Comment by natcohen** [comment]
@pkozlowski-opensource thanks for the workaround!

**Comment by maxokorokov** [comment]
Since version `5.2.0` there is a new `NgbNav` set of directives that fix this issue. `NgbNav` is meant to replace the `NgbTabset` component (completely deprecated in version `6.0.0`) as a more flexible alternative.

I suggest you migrate to it → https://ng-bootstrap.github.io/#/components/nav/overview
