### ISSUE TITLE
popover positioned incorrectly when contents include innerHtml with an image

### ISSUE THREAD

**Issue by Neowizard** [ng-bootstrap/ng-bootstrap#2018]
### Bug description:
I have a popover component with innerHtml as its popover content and that inner HTML includes a picture.

When I first trigger it, the position of the popover element is incorrect. it looks as if the positioning does not take the size of the image into consideration.
If I close and reopen the popover, its position will now be correct. The positioning remains correct even if I add more images to the inner HTML and reopen the popover (as long as I don't reload the page).

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/t2x1vqb1aRczaXNu1Dg7?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:
Angular: 4.4.6
ng-bootstrap: 1.0.0-beta.5
Bootstrap: 4.0.0-beta.2

**Comment by bastienmoulia** [comment]
You could specify the size of the image with attributes `width` and `height` if you know it.

**Comment by Neowizard** [comment]
This workaround works (thanks, I'll use that), but I still think this should be fixed since the component shows inconsistent behavior between the first open and subsequent reopens.

**Comment by pkozlowski-opensource** [comment]
> I still think this should be fixed since the component shows inconsistent behavior between the first open and subsequent reopens.

I'm not sure _how_ it could be fixed since for the first open an image is not fetched so a browser doesn't know its dimensions. As a browser doesn't know image dimensions we don't know popover dimensions, so we can't position it properly.

For subsequent opens a image was previously fetched by a browser so image dimensions are known etc.

What we are dealing with here is a timing of a network request for an image. What you are expecting is sth like "re-position popover after all images were fetched". I'm not sure we want to go down this path...

IMO a solution proposed by @bastienmoulia (thnx!) is the best we can get here.

**Comment by Neowizard** [comment]
I think there might be a better (albeit incomplete) solution. When the placement is set to 'bottom' there is no problem, since the popover expands downwards. If it would expand upwards when placement was set to 'top', I think it would display correctly.

**Comment by pkozlowski-opensource** [comment]
> I think there might be a better (albeit incomplete) solution. When the placement is set to 'bottom' there is no problem, since the popover expands downwards. If it would expand upwards when placement was set to 'top', I think it would display correctly.

We can't make those assumptions as we need to take clipping to the viewport into account. 

I'm going to close this issue as I don't think we can have a meaningful "fix" here. Your best option is to add dimension to an image as suggested by @bastienmoulia

**Comment by lqclester** [comment]
try container="body" , I  worked
