### ISSUE TITLE
Date-picker with multiple months does not print unavailable dates

### ISSUE THREAD

**Issue by TheGlockZentix** [ng-bootstrap/ng-bootstrap#2035]
Date-picker with multiple months does not print unavailable dates.
See picture below:
https://i.imgur.com/u79v1RH.png

**Comment by pkozlowski-opensource** [comment]
Yep, looks like a bug to me - I can't even force it to explicitly display: http://plnkr.co/edit/OxbizKp0Zq02zhImem9u?p=preview

cc @maxokorokov

**Comment by bastienmoulia** [comment]
Due to `[outsideDays]="(displayMonths === 1 ? outsideDays : 'hidden')"` from https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/datepicker/datepicker.ts#L126.

What is the correct behavior:
1.  Hide days outside of the month like actually
2.  Show days outside of the month (in grey)
3.  Hide days between the 2 month and show days before and after (in grey)

**Comment by pkozlowski-opensource** [comment]
Hmm, good questions @bastienmoulia ! I would say (1) or (3), but I will let @maxokorokov to decide.

**Comment by maxokorokov** [comment]
it is related to `[outsideDays]`, true.
Please see my comment here: https://github.com/ng-bootstrap/ng-bootstrap/pull/1158#issuecomment-307787860
