### ISSUE TITLE
Extensibility of NgbPopover hurt by input name for content

### ISSUE THREAD

**Issue by karptonite** [ng-bootstrap/ng-bootstrap#2057]
### Bug description:
NgbPopover is described as "extensible". However, naming the input for the popover template `ngbPopover`, the same as the selector, makes it difficult (impossible?) to pass a template reference to the extended directive, without actually applying the parent directive to the element. Unless I'm missing something.

### Link to minimally-working plunker that reproduces the issue:
In this plunk, I extend the NgbPopover directive and overwritten the `open()` method in my subclass (so that it logs to the console, but does not open). But when open is triggered (by mousing over), not only is the `open` of the child class executed, so is the `open` of the parent.
http://plnkr.co/edit/eL07tAuTshs1v3JKTLri?p=preview

If the input for the popover content was given a different name, the directive could then be extended without this conflict.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5.1.2

ng-bootstrap: beta 8

Bootstrap: 4 beta 2

**Comment by pkozlowski-opensource** [comment]
> If the input for the popover content was given a different name, the directive could then be extended without this conflict.

But this would hurt API / usability for a default case! Now people would have to write sth like `<button ngbPopover [ngbPopoverContent]="exp">` instead of just `<button [ngbPopover]="exp">`.

I think that you can easily solve this on your end by creating a dedicated `@Input` on your extended directive and forwarding it to the original input, sth like: http://plnkr.co/edit/HEJ2ldpc1K6hl2wIqpIn?p=preview

Closing as won't fix / support request.

**Comment by karptonite** [comment]
@pkozlowski-opensource Thanks for the suggestion. I was going to object that in that case, the `@Input` wouldn't work quite correctly, because  the popup content wouldn't change if the input changed, but it appears that that is not a feature that is supported anyway: http://plnkr.co/edit/eL07tAuTshs1v3JKTLri?p=preview
