### ISSUE TITLE
Datepicker popup does not open

### ISSUE THREAD

**Issue by pierre-hilt** [ng-bootstrap/ng-bootstrap#2088]
### Bug description:
In our project, we namespace bootstrap classes:
.vendor {
  @import "bootstrap";
}

Because styles are applied to host datepicker, it is not specific enough to be applied.

Popup is not displayed anymore when button is clicked.

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/Ku31syqyG8U6ALV68Ui1?p=info

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5

ng-bootstrap: latest

Bootstrap: beta 3

**Comment by ExFlo** [comment]
Hi
This issue will be solved by #2013, but the underlying issue is that we sometimes customize the bootstrap CSS that we are using in component, directly in the components, and the CSS apply depends in the order of the CSS in the page (<style is put after the css file so this works). Well this works only when the priority of the CSS in the CSS file is not higher of our customization. In fact adding this wrapping of the CSS of bootstrap boost the priority for this one instead of our own customization. 

Adding the show class will work for the display because we will use the display block of bootstrap to show the datepicker, but I think a more interesting way of handling our CSS and customization that allow also a wrapping of it would be better. 

Creating a theme with scss file will allow customization of the theme and wrapping of it more easily, and we will not see our theme being override by some other CSS when the intention is not to do so.
BR
