### ISSUE TITLE
Typeahead doesn't cancel when pressing Enter (on the original input element)

### ISSUE THREAD

**Issue by SimonStiph** [ng-bootstrap/ng-bootstrap#2112]
### Bug description:
I've read all of the closed issues (723, 1244), and this does not seem to have been resolved for this particular case. If the user types into an input, and a long-running async HTTP call has yet to return, and the user finishes typing and presses ENTER, the pop-up will still display after ENTER has already been pressed (and the user is happy with his input).

I've read the code in fix #47797d3. The ESC key cancels a running request, but pressing ENTER on the original input element (not in the Typeahead component) can still result in an unneeded popup.

This can probably be resolved by cancelling a request after ENTER has been pressed (as it does with ESC). 

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/CpoKY1LtHj1IMN9mb5Z5?p=preview
(If you type 'Linux' quickly and press ENTER before the pop-up arrives, the pop-up will still arrive.)

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5.2

ng-bootstrap: 1.0.0-beta.9

Bootstrap: 4.0.0-beta.3

**Comment by pkozlowski-opensource** [comment]
Your analysis is correct, although I'm not sure what the expected behaviour here... 

My reasoning is the following:  pressing ENTER without results window displayed should be equivalent to pressing ENTER on any normal input element.  If we take it as a starting point, it is not expected that users will press ENTER to indicate that "is happy with his input" - this would rather mean that a user wants to submit a form. Which, in a way, indicates that he is happy with the input as well :-)

OK, I think that you are right, we should probably cancel all running requests when ENTER is pressed on a closed result window.

A fix should be rather straightforward, but it needs testing to make sure that we are not breaking outer use-cases.
