### ISSUE TITLE
Tooltip _unregisterListenersFn error

### ISSUE THREAD

**Issue by jrmlstf** [ng-bootstrap/ng-bootstrap#2128]
### Bug description:

I'm using NgbTooltip with a variable translated string (with NgxTranslate but according to my tests it has no impact on the error) :

```html
<button class="btn btn-lg btn-hidden"
        placement="top"
        ngbTooltip="{{ bookmarkId ? 'UNFOLLOW' : 'FOLLOW' | translate }}"
        (click)="toggle()"
        *ngIf="!bookmarkId">
  <i class="icon" [ngClass]="{'icon-star text-color-yellow': bookmarkId, 'icon-star_border': !bookmarkId}"></i>
</button>
```

Which throw this error :
`
ERROR TypeError: this._unregisterListenersFn is not a function
    at NgbTooltip.ngOnDestroy (tooltip.js:141)
    at callProviderLifecycles (core.js:12697)
    at callElementProvidersLifecycles (core.js:12658)
    at callLifecycleHooksChildrenFirst (core.js:12641)
    at destroyView (core.js:14007)
    at callViewAction (core.js:14158)
    at execComponentViewsAction (core.js:14070)
    at destroyView (core.js:14006)
    at callWithDebugContext (core.js:15041)
    at Object.debugDestroyView [as destroyView] (core.js:14592)
`

Thanks for your help !

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular CLI: 1.6.4
Node: 8.9.4
OS: darwin x64
Angular: 5.2.0
@angular/cli: 1.6.4
@angular-devkit/build-optimizer: 0.0.37
@angular-devkit/core: 0.0.24
@angular-devkit/schematics: 0.0.45
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.4
@schematics/angular: 0.1.12
typescript: 2.4.2

ng-bootstrap: 1.0.0-beta.6

Bootstrap: 4.0.0-beta.2

**Comment by pkozlowski-opensource** [comment]
> Thanks for your help !

Sure, just _please_ provide a reproduce scenario, otherwise it is not actionable and will be closed: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#you-think-youve-found-a-bug

> with NgxTranslate but according to my tests it has no impact on the error)

We won't know for sure till we've got a minimal reproduce scenario...

**Comment by pkozlowski-opensource** [comment]
Closing since we haven't heard back with the reproduce scenario - happy to re-open if / when we've got one.

**Comment by bygrace1986** [comment]
@pkozlowski-opensource I just ran into the same issue. My scenario is that I attach a custom structural directive to an element that also has the tooltip directive on it. The structural directive has multiple parameters and evaluates whether to create or destroy the view when each parameter is set. This can cause the view to be created and destroyed quickly. It is quick enough that `ngOnInit` has not had time to run on the tooltip directive before `ngOnDestroy` has run. So `_unregisterListenersFn` is undefined and I get the error `this._unregisterListenersFn is not a function`. Just wraping the `_unregisterListenersFn` in a null check should do the trick.

Here is a working (or rather not working) example: https://stackblitz.com/edit/acl-directive

**Comment by pkozlowski-opensource** [comment]
@bygrace1986 this sounds like a bug in the Angular itself - we should never have this type of "race condition" and `ngOnInit` should _always_ run before destroy.

Could you please create a new issue here with your reproduce scenario so I can investigate, isolate problem in Angular and try to fix it?

**Comment by bygrace1986** [comment]
@pkozlowski-opensource Oh, is that not by design?

I first ran into this late last year with my own code in different scenarios, I found it mentioned by others and even blogged about (https://www.bennadel.com/blog/3356-ngoninit-may-not-get-called-before-ngondestroy-is-called-in-angular-4-4-6.htm). Though I don't think many people run into it.

The docs weren't explicit on the scenario. They say about `ngOnInit` that it "Initialize the directive/component after Angular first displays the data-bound properties and sets the directive/component's input properties." So I figured that a component could be destroyed right after construction but before any lifecycle events were invoked. It does say "You can count on Angular to call the ngOnInit() method _soon_ after creating the component. That's where the heavy initialization logic belongs." (https://angular.io/guide/lifecycle-hooks#oninit). I figured it wasn't "soon" enough to count on in `ngOnDestroy`.

**Comment by pkozlowski-opensource** [comment]
@bygrace1986 I presume that what is going on here is that destroy is called before initial change detection (initial CD is needed before `ngOnInit` to set `@Input`s). But I would like to isolate it further to confirm.

If my intuition is correct we should rather explicitly invoke change detection on a tooltip window rather than have a check around `_unregisterListenersFn`. Well, at least this is my current thinking, to be confirmed.

**Comment by bygrace1986** [comment]
@pkozlowski-opensource OK, so do you still want me to open a separate issue?

**Comment by pkozlowski-opensource** [comment]
> OK, so do you still want me to open a separate issue?

Yes, please.

> And would it be on ngBootstrap or angular?

Please open it here, in this repo. I will try to isolate it and if I can blame Angular I will open a separate issue in there. 

Thnx!

**Comment by bygrace1986** [comment]
@pkozlowski-opensource created here: #2199
