### ISSUE TITLE
Need right / left side modal 

### ISSUE THREAD

**Issue by lakshmajim** [ng-bootstrap/ng-bootstrap#2246]
### Feature description:
How can we have right side/ left side modal as demonstrated [here](https://codepen.io/bootpen/pen/jbbaRa).

I have tried with amending a custom class name to modal dialog with **NgbModal** service (class was added to DOM tree), it is not working for me. Am I missed anything here. 

### Link to minimally-working plunker that reproduces the issue:
[sample](http://plnkr.co/edit/IoJtnWx8cnQY1QoY4PXl?p=preview)

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5.2.2

ng-bootstrap: 1.0.0

Bootstrap: 4.0.0

**Comment by pkozlowski-opensource** [comment]
You could probably add a custom CSS class(s) on a modal window using the `windowClass` option: https://ng-bootstrap.github.io/#/components/modal/api

Since Bootstrap 4 itself doesn't have css / markup to support this option, we are not planning on adding it here. 

Closing as a suport request: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help
