### ISSUE TITLE
Window Scroll not working/Reset  on tabChange 

### ISSUE THREAD

**Issue by Asifislam110** [ng-bootstrap/ng-bootstrap#2260]
I have created a sample angular 2 app, where i have used ngb-tabset(for creating tab views).

I encountered the problem when i click on  button to navigate next the tab window scroll  does not reset.
it is still bottom of the page.

I tired " window.scrollTo(0,0)" but did not work

Can someone help me for this issue.

**Comment by pkozlowski-opensource** [comment]
Please use our issue template when reporting potential bugs, otherwise it is not actionable and will be closed: https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

**Comment by Asifislam110** [comment]
Thanks for your reply.
here is my plunkr url
 http://plnkr.co/edit/DYnF85V8V2MGVbCVwwoH?p=preview
I have added button on each tab when i click on button, tab data or controll it should be focus or move top of the tab/page.

**Comment by pkozlowski-opensource** [comment]
> I have added button on each tab when i click on button, tab data or control it should be focus or move top of the tab/page.

Current implantation of the tabset don't automatically scroll selected tab content into view. I don't think we want to add automatic scrolling since it can be easily done on the user land, ex.: 
 http://plnkr.co/edit/6LLCEOptQJhgO4VM6LcM?p=preview

Few notes about the sample code in the plunker:
* you want to scroll the whole tabset into view, not an individual tab
* this is just an example, do _not_ it in your production code as-is (!)

Closing as a support request.

**Comment by Asifislam110** [comment]
Thanks @pkozlowski-opensource 
It worked for me 
Thanks
