### ISSUE TITLE
Separate Tab Header and Separate Tab Body Content

### ISSUE THREAD

**Issue by naveen305** [ng-bootstrap/ng-bootstrap#2264]
Hi ,
Need help / solution to create a separate tab header and separate body content.

Much Appreciated.

Thanks,
NK

**Comment by pkozlowski-opensource** [comment]
Sorry, I'm not clear at all what you are asking for... Maybe you should start by asking a support question using an appropriate channel? https://github.com/ng-bootstrap/ng-bootstrap#getting-help

**Comment by naveen305** [comment]
Thanks for the comment.

How can I use tabs like bootstrap. For Ex : Tab header and Tab Content should be calling separatly


And How can i write initial tab should be closed. When I click it should be open.


Thanks again
NK

**Comment by pkozlowski-opensource** [comment]
I see, you want to just have nav portion of tabs (https://getbootstrap.com/docs/4.0/components/navs/#base-nav). Marking as a feature request as it makes sense and would improve flexibility of the tabset. Don't hold your breath, though - this won't be the top priority (unless there is strong community demand, of course).

**Comment by maxokorokov** [comment]
Since version `5.2.0` there is a new `NgbNav` set of directives that fix this issue. `NgbNav` is meant to replace the `NgbTabset` component (completely deprecated in version `6.0.0`) as a more flexible alternative.

I suggest you migrate to it → https://ng-bootstrap.github.io/#/components/nav/overview
