### ISSUE TITLE
Typehead "focus" automatically triggered in IE11 if placeholder contains an accent

### ISSUE THREAD

**Issue by FrenchTastic** [ng-bootstrap/ng-bootstrap#2339]
Hi, I've a strange behavior in IE 11.
It seems a little bit silly, but it is real ^^.

### Bug description:
In Internet Explorer 11, with the latest version 1.1.2 (and even with 1.0), I've an issue when I'm trying to use Typehead with the trigger on focus.

If my input field has a placeholder with an accent (i.e : Spécialité), typehead is triggered after page loaded.
If I delete accent, the typehead is properly triggered when field got focus.
I'm okay to add a proper Plunkr, but Plunkr does not seems to work anymore on IE 11 (or I've an issue with company proxy or anything else. So maybe you won't be able to test it on IE.

This is working properly with others broswers.
The issue can be related to IE, but maybe something can be done to prevent this behavior when it's being use on IE11.

P.S : It seems that your plunkr does not work for Typehead on Focus, Stackblitz does.

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/PKt3WMju4U6QMALv4QFQ?p=preview
https://stackblitz.com/edit/angular-zcnwgg?file=app/typeahead-focus.html

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5.2.1

ng-bootstrap: 1.1.2

Bootstrap: 4.0.0

**Comment by pkozlowski-opensource** [comment]
@divdavem here is another IE11 mystery to investigate - from the description it _sounds_ like the `focus` event is triggered if there is a placeholder with certain characters??? Sounds like a bug in a browser, if you could please narrow it down, we could open an issue in the appropriate repo... Thnx!

**Comment by divdavem** [comment]
I have discussed about this issue with @pkozlowski-opensource

We do not want to introduce ugly code in ng-bootstrap just to work around a very strange bug in an old browser.

Here is a work-around that can be done to support this use case on IE 11:
- ignore the `text$` argument in the `search` function passed to `[ngbTypeahead]`
- create a similar observable based on `keydown` events instead of `input` events

Compared to `input` events (when this type of events works properly), `keydown` events have several drawbacks for this use case:
- some keydown events do not lead to a change in the input (they should be ignored)
- the updated input value has to be read asynchronously, because when the keydown event is raised, the value of the input has not been updated yet

@FrenchTastic I have forked your stackblitz example to show how this can be done: https://stackblitz.com/edit/angular-zcnwgg-ye6qqz?file=app%2Ftypeahead-focus.ts There are probably other ways to achieve the same result. This is just an example.

**Comment by pkozlowski-opensource** [comment]
@divdavem thnx for confirming that this is a bug in IE. I agree that we don't want to work-around it given that:
* IE11 market share is relatively low;
* a work-around exists in the user land.

@FrenchTastic sorry, but it seems like working-around it on your side will be less ugly that trying to "fix" it on our end...

**Comment by FrenchTastic** [comment]
@pkozlowski-opensource Ok, I totally understand, and hope that IE11 marketshare will continue to drop.

Thanks you guys, and thanks @divdavem for this workaround. I will try to see if downsides worth the cost of IE11 users, or find another way.

**Comment by dedeibel** [comment]
What a bug… also happens with umlauts: üäö
