### ISSUE TITLE
ERROR TypeError: Cannot read property 'isEventFrom'

### ISSUE THREAD

**Issue by vlafargue** [ng-bootstrap/ng-bootstrap#2343]
### Bug description:

Hello world. since i update the version of ng boostrap from 1.0.0 to 1.1.2 I have an error in my web console.

![image](https://user-images.githubusercontent.com/26387042/39292393-55e5e926-4936-11e8-934d-f5437c6bf424.png)

### Link to minimally-working plunker that reproduces the issue:

I have issue on this piece of code:

`    <div ngbDropdown class="dropdown" #myDropGlobal="ngbDropdown">
`and
`    <div ngbDropdown class="dropdown">
`
wich seems good.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5

ng-bootstrap: 1.1.2

Bootstrap: 4.0.0-beta

**Comment by andrewlistopadov** [comment]
I have the same. Before minification it looks like
`NgbDropdown.prototype._isEventFromToggle = function ($event) {
     return this._toggle ? this._toggle.isEventFrom($event) : false; 
};`
but after minification 
`t.prototype._isEventFromToggle = function(t) {
    return this._anchor.isEventFrom(t)
}`

**Comment by vlafargue** [comment]
Ok, after looking the code, if think the change to make are:

From this code:
`  NgbDropdown.prototype._isEventFromToggle = function ($event) { return this._anchor.isEventFrom($event); };
`
To this code:
```
  NgbDropdown.prototype._isEventFromToggle = function ($event) {
    return this._anchor ? this._anchor.isEventFrom($event) : false;
```

**Comment by pkozlowski-opensource** [comment]
@vlafargue we need a minimal reproduce scenario in a plunker / stackblitz. Please provide one or it is not actionable and will be closed. You can start by modifying this stackblitz: https://stackblitz.com/edit/angular-tqqjmj?file=app/dropdown-basic.html

> <div ngbDropdown class="dropdown" #myDropGlobal="ngbDropdown">and
<div ngbDropdown class="dropdown">
wich seems good.

Please note that you _must_ use one of the NgbDropdownToggle _or_ NgbDropdownAnchor directives _inside_ `ngbDropdown` so we know where to position a dropdown menu window: https://ng-bootstrap.github.io/#/components/dropdown/api.

**Comment by andrewlistopadov** [comment]
@vlafargue  just dowgrade to version 1.0.0. It works fine cause it has check on undefined.

**Comment by pkozlowski-opensource** [comment]
@andrewlistopadov downgrading version without understanding the root cause is _not_ the approach you can recommend long-term as you would be stuck in a particular version of the library.

If you want to help and believe that you are facing the same issue, please provide a minimal reproduce scenario as indicated in the issue template and my previous comment.

**Comment by vlafargue** [comment]
Ok, now I understand the problem. Witth the last version the ngbDropdown directive was working without NgbDropdownAnchor or Toggle. Thanks for the hand.

**Comment by MariMax** [comment]
@pkozlowski-opensource thanks for the clarification, in our case ngbDropdownToggle was available only after ngbDropdown was created, **wrong** code snippet bellow
```
      <div ngbDropdown>
        <button ngbDropdownToggle *ngIf="showButton()">Btn</button>
        <ul ngbDropdownMenu>
          <li *ngFor="let item of items">
            <button (click)="actionOnItem(item)">{{item.name}}</button>
          </li>
        </ul>
      </div>```

**Comment by pmanexoriant** [comment]
Is there any progress on this issue ?? Getting same problem

**Comment by shawnrmoss** [comment]
We were running into the exact same issue because we had *ngIf="condition" on our ngbDropdownToggle elements.

We had to keep the newer version v 1.1.2 because we also update our angular packages.

Our fix was to replace *ngIf with [style.display]="condition ? 'inline': 'none'".

This solution worked for us.

**Comment by r-winkler** [comment]
For me, the ngbDropdownToggle directive was missing on the button.

**Comment by BhoomiInfo** [comment]
I ran into the same issue today

https://stackblitz.com/edit/angular-tqqjmj-flhcmt?file=app%2Fdropdown-basic.html

https://angular-tqqjmj-flhcmt.stackblitz.io/

**Comment by WilliamRADFunk** [comment]
I had a similar issue @BhoomiInfo. Sometimes it's necessary to have the ngbDropdown directive on a wrapper element like

```
<div class="btn-group" ngbDropdown>
    <button class="btn" ngbDropdownToggle></button>
    <div ngbDropdownMenu>
        <!-- Your menu stuff -->
    </div>
</div>
```

Putting it on a button, as the wrapper like in your example code, seems to be the source of your pain.

Note: I've also observed that if you are toggling from within your component controller code (not referring to your example code), ngbDropdownAnchor might be a better substitute instead of ngbDropdownToggle.

Hope this helps. Good luck to you.

**Comment by BhoomiInfo** [comment]
@WilliamRADFunk  Thanks for the suggestion

I used   *ngIf with [style.display]="condition ? 'inline': 'none'".  as suggested by @shawnrmoss  and it worked.
