### ISSUE TITLE
tab-set: Issues with dynamically generated tabs

### ISSUE THREAD

**Issue by AbakumovAlexandr** [ng-bootstrap/ng-bootstrap#2355]
### Bug description:
See the Stackblitz below.
1. When adding multiple tabs, their content is displayed one below the other.
2. Can't switch between tabs.
3. When clicking on Close (x) button in tab titles in the example, the app gets reloaded.

### Link to minimally-working plunker that reproduces the issue:
https://stackblitz.com/edit/ng-bootstrap-tab-set-issues

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5.0.2 (also tested in 5.2.10)

ng-bootstrap: 1.1.2

Bootstrap: 4.0.0 (also tested in 4.1.1)

**Comment by pkozlowski-opensource** [comment]
This is because you are giving _all_ the tabs the _same_ `id` - it must be unique. I guess this is due to the confusion with the Angular syntax - you need to _bind_ to the `id` _property_ instead of giving it _literal_ value of `tab.id`: just change `id="tab.id"` to `id="{{tab.id}}"` and things will work properly.

Here is a working stackblitz: https://stackblitz.com/edit/ng-bootstrap-tab-set-issues-pdqznh?file=app/app.component.html

Closing as a support request.

**Comment by AbakumovAlexandr** [comment]
@pkozlowski-opensource , thank you! This resolves issues 1 and 2. However, this one:

> 3. When clicking on Close (x) button in tab titles in the example, the app gets reloaded.

is still happening. Any feedback on this is highly appreciated.

**Comment by stout01** [comment]
See related issue here: #1909

**Comment by AbakumovAlexandr** [comment]
@stout01 thank you! That addresses the last issue left after the @pkozlowski-opensource answer.
