### ISSUE TITLE
ng add with @ng-bootstrap/ng-bootstrap

### ISSUE THREAD

**Issue by bastienmoulia** [ng-bootstrap/ng-bootstrap#2361]
When a new angular 6 project is created, why we have to use `ng add @ng-bootstrap/schematics` instead of `ng add @ng-bootstrap/ng-bootstrap`?

I see the change in #2289 but don't understand it.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 6

ng-bootstrap: 2

Bootstrap: 4

**Comment by pkozlowski-opensource** [comment]
Adding a schematic to the `@ng-bootstrap/ng-bootstrap` package would mean that we must dependencies for:
* typescript
* parts of CLI

I don't think this would be great so for now published the schematic under `@ng-bootstrap/schematics`. Would love suggestion on how to solve it better...

**Comment by bastienmoulia** [comment]
The repo for @angular/material use a folder with another package.json file.
It's not perfect but easier to maintain.
https://github.com/angular/material2/tree/master/src/lib

**Comment by unstephenk** [comment]
Tried `ng add @ng-bootstrap/schematics` but got this error.
`npm WARN bootstrap@4.1.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.`
`npm WARN bootstrap@4.1.1 requires a peer of popper.js@^1.14.3 but none is installed. You must install peer dependencies yourself.`

What is the point of using schematics if I still have to add other dependencies? I thought the `ng add` was suppose to do this.

**Comment by newaeonweb** [comment]
I have the same warning, using: `ng add @ng-bootstrap/schematics`.
```Tried ng add @ng-bootstrap/schematics but got this error.
npm WARN bootstrap@4.1.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.1.1 requires a peer of popper.js@^1.14.3 but none is installed. You must install peer dependencies yourself.
``` 

I can't understanding the warning because the website say's: 

> Angular - specific widgets built from ground and using Bootstrap 4 CSS. APIs that makes sense in the Angular ecosystem. No dependencies on 3rd party JavaScript.

So we need `jquery` and `popper` or not?

**Comment by lizzymendivil** [comment]
I got the same error...
no make sense.
I prefer using this: npm install --save @ng-bootstrap/ng-bootstrap

npm WARN bootstrap@4.1.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.1.1 requires a peer of popper.js@^1.14.3 but none is installed. You must install peer dependencies yourself.

**Comment by alvaro450** [comment]
@lizzymendivil @newaeonweb schemstics are awesome and give us a lot of power and flexibility but ultimately it is not magic and it is code a library owner has to write.

You can run ng add <library> —force and that should add the library regardless of missing peer deps. The schematics library looks at the package.json file of the library you are adding and if there are any peer dependencies listed but not installed on your project then it gives you that error, when you add the —force flag it ignores the warnings, same as if you were to do npm install <library>.

Hopefully this explains why you get what you are getting and how you can go around it. You may still have to install the peer dependencies manually after ng add is done.

**Comment by newaeonweb** [comment]
@pkozlowski-opensource Thanks Bro.

**Comment by tobi-or-not-tobi** [comment]
There has been several tickets at bootstrap side of this, including https://github.com/twbs/bootstrap/issues/23557, https://github.com/twbs/bootstrap/issues/23204 and https://github.com/twbs/bootstrap/issues/24078. 

It's not clear to me whether a separate bootstrap-css package is around the corner.

**Comment by malikfaizanhaider** [comment]
**Should I add bootstrap.js or bootstrap.min.js to my project?**

No, the goal of ng-bootstrap is to completely replace JavaScript implementation for components. Nor should you include other dependencies like jQuery or popper.js. It is not necessary and might interfere with ng-bootstrap code.

[Link](https://ng-bootstrap.github.io/#/getting-started)

**Comment by OrangeDog** [comment]
There is a [bootstrap-css-only](https://www.npmjs.com/package/bootstrap-css-only) available.

**Comment by Santhosh742** [comment]
After add ng add @ng-bootstrap/schematics , I am getting this error while run the application ng serve

Error: Failed to compile entry-point @ng-bootstrap/ng-bootstrap (module as esm5) due to compilation errors:        
node_modules/@ng-bootstrap/ng-bootstrap/rating/rating.js:148:43 - error NG1006: Cannot combine @Input decorators with query decorators

148         "starTemplate": [{ type: Input }, { type: ContentChild, args: [TemplateRef,] },],
                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/@ng-bootstrap/ng-bootstrap/rating/rating.module.js:12:51 - error NG6001: The class 'NgbRating' is listed in the declarations of the NgModule 'NgbRatingModule', but is not a directive, a component, or a pipe. Either remove it from the NgModule's declarations, or add an appropriate Angular decorator.

12         { type: NgModule, args: [{ declarations: [NgbRating], exports: [NgbRating], imports: [CommonModule] },] 
},
                                                     ~~~~~~~~~

  node_modules/@ng-bootstrap/ng-bootstrap/rating/rating.js:14:5
    14 var NgbRating = /** @class */ (function () {
           ~~~~~~~~~
    'NgbRating' is declared here.
node_modules/@ng-bootstrap/ng-bootstrap/rating/rating.js:14:5 - error NG6003: Appears in the NgModule.exports of NgbRatingModule, but could not be resolved to an NgModule, Component, Directive, or Pipe class.

Is it missing an Angular annotation?39m

14 var NgbRating = /** @class */ (function () {
       ~~~~~~~~~
node_modules/@ng-bootstrap/ng-bootstrap/rating/rating.module.js:7:5 - error NG6002: Appears in the NgModule.imports of NgbRootModule, but itself has errors

7 var NgbRatingModule = /** @class */ (function () {
      ~~~~~~~~~~~~~~~
node_modules/@ng-bootstrap/ng-bootstrap/rating/rating.module.js:7:5 - error NG6003: Appears in the NgModule.exports of NgbRootModule, but itself has errors

7 var NgbRatingModule = /** @class */ (function () {
      ~~~~~~~~~~~~~~~
node_modules/@ng-bootstrap/ng-bootstrap/rating/rating.module.js:7:5 - error NG6002: Appears in the NgModule.imports of NgbModule, but itself has errors

7 var NgbRatingModule = /** @class */ (function () {
      ~~~~~~~~~~~~~~~
node_modules/@ng-bootstrap/ng-bootstrap/rating/rating.module.js:7:5 - error NG6003: Appears in the NgModule.exports of NgbModule, but itself has errors

7 var NgbRatingModule = /** @class */ (function () {
      ~~~~~~~~~~~~~~~


Can you please help me.

**Comment by yogeshpawar1958** [comment]
i got same error
