### ISSUE TITLE
DatePicker Error: ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by IConstructor** [ng-bootstrap/ng-bootstrap#2408]
I am facing the following console error which appears when I am trying to go to next/prev months with a help of keyboard arrows.
ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'focused: true'. Current value: 'focused: false'.
at viewDebugError (core.js:9775)
at expressionChangedAfterItHasBeenCheckedError (core.js:9753)
at checkBindingNoChanges (core.js:9920)
at checkNoChangesNodeInline (core.js:13974)
at checkNoChangesNode (core.js:13942)
at debugCheckNoChangesNode (core.js:14771)
at debugCheckDirectivesFn (core.js:14673)
at Object.eval [as updateDirectives] (NgbDatepicker.html:3)

Bootstrap version 4, Angular 5. ng-bootstrap - 2
plunker - http://plnkr.co/edit/yzCMpNMb15oOQf5tJCn6

Do you have any assumptions why this is happening and whether it can be fixed?

**Comment by pkozlowski-opensource** [comment]
Thnx for the plunk @IConstructor - I can reproduce it now. It happens when a keyboard arrow moves to the day that is "disabled" (not part of the current month). 

@maxokorokov @benouat some more focus-related joy :-)

**Comment by pkozlowski-opensource** [comment]
This seems to happen only if you import `BrowserAnimationsModule`

**Comment by IConstructor** [comment]
@pkozlowski-opensource , you are right. The issue is I cannot remove the importing because it supports other components.

**Comment by ovgeorgescu33** [comment]
Try to manually call detectChanges() method of ChangeDetectorRef in your component, on date/day change event.
https://angular.io/api/core/ChangeDetectorRef

**Comment by divdavem** [comment]
I have started investigating the problem with @maxokorokov 

We have reproduced a similar issue in the following stackblitz:
https://stackblitz.com/edit/angular-bcqst5?file=src%2Fapp%2Fapp.component.html

In Chrome, the focusout event, which changes the data model, is called synchronously when the node is removed from the DOM (when removeChild is called), during the change detection of the keydown event, when there should be no change of the data model. This leads to the ExpressionChangedAfterItHasBeenCheckedError error. This does not happen in Firefox (unlike Chrome removeChild does not trigger focusout).

**Comment by divdavem** [comment]
Note that this error only happens with `BrowserAnimationsModule` because the value that is changed in the data model in the `focusout` event listener is no longer part of the data model when the `BrowserAnimationsModule` is not used.
Without `BrowserAnimationsModule`, the view containing a reference to the changed part of the data model is destroyed immediately, and, as a consequence, it is not checked during the second change detection that is supposed to trigger `ExpressionChangedAfterItHasBeenCheckedError`.
With `BrowserAnimationsModule`, even though the DOM element is destroyed immediately, the view structure and its data model are destroyed a bit later, probably because this is needed when animating DOM elements, and the second change detection of the key event includes the part of the data model that is changed in the `focusout` event listener, leading to the `ExpressionChangedAfterItHasBeenCheckedError` exception.
