### ISSUE TITLE
ngbd-pagination-advanced' and angular6

### ISSUE THREAD

**Issue by pcouas** [ng-bootstrap/ng-bootstrap#2425]
Hi,

I have following error message with angular6 and <ngbd-pagination-advanced>

[code]
Uncaught Error: Template parse errors:
'ngbd-pagination-advanced' is not a known element:
1. If 'ngbd-pagination-advanced' is an Angular component, then verify that it is part of this module.
2. If 'ngbd-pagination-advanced' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
    <hr>
[/code]

 "dependencies": {
  "@angular/core": "6.0.3",
"@ng-bootstrap/ng-bootstrap": "^2.0.0",
"bootstrap": "^4.1.1",

ng-bootstrap is compatible with angular6 ?

**Comment by pkozlowski-opensource** [comment]
> ng-bootstrap is compatible with angular6 ?

YEs, of course. Version 2.0.0 of ng-bootstrap is fully compatible with angular6 

In any case it sounds like a setup problem on your side and we would need a minimal reproduce scenario to follow up on this, see:
* https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help
* https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#you-think-youve-found-a-bug

Here is a working stackblitz  demonstrating advanced usage of pagination: https://stackblitz.com/angular/vmrjymjaonl - it was forked from our demo page: https://ng-bootstrap.github.io/#/components/pagination/examples

You can compare your setup with the one in stackblitz to see what is wrong with your setup (or use it as a starting point to reproduce a bug if you believe that problem is on the ng-bootstrap side).

**Comment by pcouas** [comment]
Hi
Your sample is not very clear, i search an sample with loading and Json File. Your sample are empty without loading datas

**Comment by pkozlowski-opensource** [comment]
Please ask support questions like this one on SO: https://github.com/ng-bootstrap/ng-bootstrap#getting-help
