### ISSUE TITLE
NgbModalRef.result.then() callback does not trigger change detection

### ISSUE THREAD

**Issue by AbakumovAlexandr** [ng-bootstrap/ng-bootstrap#2431]
I have crated a test app with all components being `ChangeDetectionStrategy.OnPush`. The app demostrates getting some data from `NgbModal` when a user closes the modal.

### Bug description:
When code in `NgbModalRef.result.then()` callback updates model of a component which opened the modal, those changes are not picked up by the change detection.
When I'm doing the same when modal component is created by `ngComponentOutlet` directive, it works fine.

### Link to minimally-working plunker that reproduces the issue:

[StackBlitz](https://stackblitz.com/edit/ng-bootstrap-data-from-modal-test)

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 6.0.3
ng-bootstrap: 2.0.0
Bootstrap: 4.1.1

**Comment by AbakumovAlexandr** [comment]
@giampierobono , I don't think it's true. Promises in Angular are handled by zone.js and actually are instances of `ZoneAwarePromise` type.

Usually, you need to handle changes with `Promise`\`Obsevable` manually using `ChangeDetectorRef` or other means when you do network operations or communicating with a 3rd party JS code running outside Angular zone.

**Comment by benouat** [comment]
@AbakumovAlexandr I think you are mixing several notions in here: Zone, Promise/Observable and OnPush

---

In your Stackblitz, it is **normal** that the binding is not updated when using `modalService`. Your host component being declared as `OnPush`, you are not updating any `@Input` on it, there is no way anything would be refreshed here... it's normal.

So the promise is executed in the zone, as expected, but then, the component template is not refreshed because it is not supposed to, as expected (because of `OnPush`)

To me the real issue here would be more: _why is it refreshing the `OnPush` host with `ngComponentOutlet`_ ?

**Comment by pkozlowski-opensource** [comment]
@giampierobono and @benouat are correct here (thnx both for helping out with the issues!),

@AbakumovAlexandr as @benouat pointed out you seem to confuse role of zones and its interplay with `OnPush` components. Here is a gist of what is happening:
* zone will pick up events (user interactions, timers, promise resolution, XHR coming back etc.) that are "interesting" from UI update point of view. When such event is detected a change detection process will kick-in.
* change detection process runs from the root component and change-detects all components unless it bumps into an `OnPush` component. In case of `OnPush` components change detection will be run if an only if one of the 2 conditions is fulfilled:
  * an `@Input` of a given component changed
  * an "interesting event" originated from a  component's _template_ (ex. `(click)="doSth()"`.

All this can be seen in action in this simplified stackblitz: https://stackblitz.com/edit/angular-l4mfnc?file=src%2Fapp%2Fapp.component.ts

Going to close this one as things works as expected.
