### ISSUE TITLE
Do not render .popover-header (title) node if title is not set

### ISSUE THREAD

**Issue by milasevicius** [ng-bootstrap/ng-bootstrap#2454]
### Bug description:

Do not render .popover-header (title) node if title is not set, because if it has some styling applied (margin or padding), UI will not look good.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular:
6.0.0
ng-bootstrap:
2.1.0
Bootstrap:
4.0.0

**Comment by jnizet** [comment]
I tried to reproduce the issue, but couldn't: https://stackblitz.com/edit/angular-ydtxe8?file=app/popover-basic.html.

As you can see, the popover header is in the DOM even though no title is set, but the bootstrap CSS takes care of that because it has a CSS rule that makes it `display: none` when it's empty:

```
.popover-header:empty {
    display: none;
}
```

Please provide a stackblitz reproducing the issue, and show what the issue is, possibly by making a screenshot obtained from this repro and showing what doesn't look right.

**Comment by milasevicius** [comment]
You are right, closing.
