### ISSUE TITLE
typeahead adds <div aria-live> element to body but does not remove it

### ISSUE THREAD

**Issue by dominikg** [ng-bootstrap/ng-bootstrap#2457]
### Bug description:
The first time a typeahead component is created, an element `<div aria-live="polite" aria-atomic="true" class="sr-only"></div>` gets added to body.

This element never gets removed, even if the typeahead component is destroyed.

### Link to minimally-working plunker that reproduces the issue:
Your demo itself shows the issue:

1. open https://ng-bootstrap.github.io/#/components/tooltip/examples
2. check that the div is not present in the bottom of body element
3. navigate to typeahead 
4. check that it was added
5. navigate back to tooltip
6. check that it is still present

### Version of Angular, ng-bootstrap, and Bootstrap:
Angular: 6.0.5
ng-bootstrap: 2.1.0
Bootstrap: 4.1.1

### Additional information
Introduced in https://github.com/ng-bootstrap/ng-bootstrap/commit/f65b8a434960d755ab7ef1fb567c59a47cf105fd#diff-4b999ef7b06784feb23d420f3d909d1a

**Comment by pkozlowski-opensource** [comment]
@dominikg out intention is to keep this element around and not re-create it every time. It should be destroyed when Angular application gets destroyed.

Is presence of this element posing any particular problems for you?
/cc @maxokorokov since you are working on this part

**Comment by dominikg** [comment]
It just confused me while i was debugging an application and thought i'd let you know.
It also keeps the latest content e.g. "1 result available" indefinetly.

If this is a multi-purpose element that is just lazily created it is ok for me. Now that i know what it is.

**Comment by maxokorokov** [comment]
Thanks for reporting it! 
I'd say that for now it is working as designed :)

We add the `<div>` element in question and remove it when application is destroyed.
There is a PR to optimize this a little bit to make sure we always have only one div element: https://github.com/ng-bootstrap/ng-bootstrap/pull/2458

So, I wouldn't consider it a bug, unless you have a specific use case that breaks things for you

**Comment by valentinabojan** [comment]
Hi! I see that on https://ng-bootstrap.github.io/#/components/typeahead/examples, when using a typeahead, there is a new element appearing in the DOM saying the number of results:
```
<div id="ngb-live" aria-live="polite" aria-atomic="true" class="sr-only">3 results available</div>
```
However, this element is not rendered on the page (most probably because of some css attributes). 
On my application, this element is always displayed. Is there a way to not have this information/element in the DOM? (i.e some property that I can use). Thank you!

**Comment by maxokorokov** [comment]
@valentinabojan it's due to the `class="sr-only"`; it should be hidden. 

I don't think you're adding Bootstrap CSS properly / have a very custom bootstrap CSS build. I suggest you fix this, not try to hide the element.

Otherwise just add `display: none;`  for `sr-only`. We won't remove it, because it is there for a11y support.

**Comment by Hitsaa** [comment]
I have posted the solution [here](https://github.com/ng-bootstrap/ng-bootstrap/issues/4560#issuecomment-2205309705). please check.
https://github.com/ng-bootstrap/ng-bootstrap/issues/4560#issuecomment-2205309705
