### ISSUE TITLE
Can not set initial date value with reactive form

### ISSUE THREAD

**Issue by MuhammadAsifAdnan** [ng-bootstrap/ng-bootstrap#2474]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
Can not set initial date value with reactive form. I've set the form controller to a NgbDateStruct object.
Looks like if I do not use the [(ngModel)] directive there is no other way to set the initial value of the date input field?
### Link to minimally-working plunker that reproduces the issue:

You can fork a plunker from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.
Please note that we can _not_ act on bug reports without a minimal reproduction scenario in plunker. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.0.0

ng-bootstrap: 1.0.0-alpha.28

Bootstrap: 4.0.0-alpha.6

**Comment by pkozlowski-opensource** [comment]
@MuhammadAsifAdnan there is no info nor reproduce scenario to help us understand what is your problem. Please follow the issue template to report problems - otherwise it is not actionable and will be closed. 

Side note: you seem to be using _very_ old (almost one year old!), _alpha_ version of this library so, as with any _alpha_ level software I would expect bugs here and there... 

If you want to see any progress on this one please provide a _minimal_ reproduce scenario using plunker / stackblitz with the _latest_ version of ng-bootstrap.

**Comment by MuhammadAsifAdnan** [comment]
https://stackblitz.com/edit/angular-8wqwz7

**Comment by MuhammadAsifAdnan** [comment]
alright, i fixed that, i converted the date string to date pickers date object and used the patchValue() method to update the field.
