### ISSUE TITLE
Typeahead CSS: .dropdown-menu width fails to be applied.

### ISSUE THREAD

**Issue by PreLu** [ng-bootstrap/ng-bootstrap#2526]
Hi all,
from the example you provide in:

- https://ng-bootstrap.github.io/#/components/typeahead/examples

the width of the dropdown is automatically set accordingly to the text width of the results being displayed. 

Since there's no css part in your examples (apart from the one hardcoded into the .ts) I tried to apply a basic static width to the dropdown-menu class (100%) in order to have a constant width (same as the whole search input):

`.dropdown-menu {
    width: 100%;
}`

But the style is completely ignored.

**Comment by pkozlowski-opensource** [comment]
> the width of the dropdown is automatically set accordingly to the text width of the results being displayed.

Correct. This is standard behaviour of dropdowns in Boootstrap 4.

> Since there's no css part in your examples (apart from the one hardcoded into the .ts) I tried to apply a basic static width to the dropdown-menu class (100%) in order to have a constant width (same as the whole search input):

> .dropdown-menu { width: 100%; }

> But the style is completely ignored.

But Bootstrap CSS already has the following rule:

```css
.dropdown-menu.show {
    display: block;
    width: 100%;
}
```

so your override would have no effect. You might want to apply styling to a different (parent) element. In any case ng-bootstrap don't force any styles nor prevents any styling. You've got full flexibility, check this as an example: https://stackblitz.com/edit/angular-rasmxd?file=app/dropdown-basic.html 

Anyway, since this is CSS related support question please ask it on the dedicated support forum: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help

**Comment by SimoneCafiero** [comment]
Hi Pawel,
as far as I know, unless you specify:

`import {Component, ViewEncapsulation} from '@angular/core';

@Component({
  selector: 'ngbd-typeahead-template',
  templateUrl: 'src/typeahead-template.html',
  styleUrls: ['src/typeahead-template.css'],
  encapsulation: ViewEncapsulation.None
})`

within the Angular component the width is not applied. The downside is that, by defining the encapsulation scope to _None_ it is like you apply the CSS rule at the application scope. And probably that is not great.
