### ISSUE TITLE
Bootstrap used in the demo is outdated

### ISSUE THREAD

**Issue by maxkorz** [ng-bootstrap/ng-bootstrap#2589]
Accordion component:

ng-bootstrap:
![image](https://user-images.githubusercontent.com/25089646/43888872-60fcf8ee-9bcb-11e8-93b6-500e2fb99d2c.png)
Notice rounded edges between the cards

bootstrap:
![image](https://user-images.githubusercontent.com/25089646/43888857-569a6b52-9bcb-11e8-8494-b29a10d5fcda.png)

[Round-less cards in accordion were implemented in bootstrap v4.1.3](https://github.com/twbs/bootstrap/commit/c0246e926f0e9e955f34b34286f97cc201582ba1#diff-6b6e15249bae4734567a50cb138fe848). 

But it looks like current demo is running on [Bootstrap 4.0.0](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/package.json#L58)

**Comment by pkozlowski-opensource** [comment]
This is intentional. We want to make sure that we test and work with bootstrap `^4.0.0` - we don't want to force our users to migrate to the latest Bootstrap 4.x version.

We will bump up minimal Bootstrap dependency as soon as there are bugs that _force_ us and our users to update Bootstrap version. But this would be a breaking change for us and would require a major release.

Closing for now as won't fix.
