### ISSUE TITLE
ngb-tab: Issues in dynamically generated tabs with ngSwitch

### ISSUE THREAD

**Issue by itsmesuresh** [ng-bootstrap/ng-bootstrap#2591]
### Bug description:

When switching between dynamically generated tabs with ```ngSwitch``` the **default** case tab **content** does not get rendered when selecting the **second** time. From the Stackblitz demo when selecting the tabs you can see, 1st and 2nd tab content get rendered properly but 3rd and 4th tab content get only rendered the first time.

### Link to minimally-working plunker that reproduces the issue:
https://stackblitz.com/edit/dynamic-ng-tab?file=app%2Fapp.component.ts

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5.0.2

ng-bootstrap: 1.1.2

Bootstrap: 4.0.0

**Comment by pkozlowski-opensource** [comment]
It is because `<ng-template>` content gets inserted in some different place (in the tabset's view). If you keep `ngSwitch` and `ngSwitchCase` in different views (as you do) you are effectivelly loosing connection between `ngSwitch` and `ngSwitchCase` directives.

You should keep `ngSwitch` and `ngSwitchCase` in the same view, ex.: https://stackblitz.com/edit/dynamic-ng-tab-13mpfd?file=app/app.component.html

Closing as a support request.

BTW, would highly suggest upgrading to Angular 6 and ng-bootstrap 2.2.x.

**Comment by itsmesuresh** [comment]
Hi @pkozlowski-opensource,

Thanks for your quick response.
