### ISSUE TITLE
tabs: tabChange event does not fire when a tab is changed automatically

### ISSUE THREAD

**Issue by ghost** [ng-bootstrap/ng-bootstrap#2622]
### Bug description:
According to documentation: 
> A tab change event fired right before the tab selection happens.

However, the event does not fire when a tab is changed because the plugin is forced to select another tab. Cases that I can think of:
1. Selecting the initial tab
2. Selecting a new tab when a user deletes an active tab

My use-case: I display some dynamic data in tabs, and I need to run some code every time I display a new tab. But `(tabChange)` output doesn't fire when I remove an active tab, and it also doesn't fire on the initial load (when the first available tab is selected automatically)

### Link to minimally-working plunker that reproduces the issue:
https://stackblitz.com/edit/angular-hd6ykc?file=app%2Ftabset-basic.ts

### Version of Angular, ng-bootstrap, and Bootstrap:
Angular: 6.1.3
ng-bootstrap: 3.0.0

**Comment by maxkorz** [comment]
I think so, yes. 👍 

> another event (working names: tabChanged / tabActivated)
> not sure about the initial display since there is no change here technically speaking

when tabs are initialized, `the selected/active tab is changed` / `the first tab is activated`, logically speaking

**Comment by maxokorokov** [comment]
Since version `5.2.0` there is a new `NgbNav` set of directives that fix this issue. `NgbNav` is meant to replace the `NgbTabset` component (completely deprecated in version `6.0.0`) as a more flexible alternative.

I suggest you migrate to it and please read about the nav selection here → https://ng-bootstrap.github.io/#/components/nav/overview#basic-usage
