### ISSUE TITLE
Popover opens over button with floating html content

### ISSUE THREAD

**Issue by ImNightwing** [ng-bootstrap/ng-bootstrap#2626]
### Bug description:
Popover opens over button with left-top with floating dynamic html
### Link to minimally-working plunker that reproduces the issue:
https://angular-a5funs.stackblitz.io

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 6.1.3

ng-bootstrap: 3.0.0

Bootstrap: 4.1.3

**Comment by m-przybylski** [comment]
Working on that issue.

**Comment by m-przybylski** [comment]
I did some investigations and this is what I found:
Popover apply position in 2 places. The first one is just after element has been added to DOM and the second time is when component is stable (CD has nothing to do any more). But still this is not enough because browser is some edge cases is not able to apply all the styles to the element, so placement is wrongly applied.

![screen shot 2018-10-05 at 12 29 30](https://user-images.githubusercontent.com/1764395/46530544-616f4100-c89a-11e8-8ff0-89490721ddd1.png)

IMO to avoid that is to wait till next frame and than calculate proper position of the element

**Comment by fbasso** [comment]
#2972 has fixed the issue. In the stackblitz example, there is a width issue (see screenshot above), but here it's a matter of html/bootstrap markup inside the popover content.

This issue can be closed.

![image](https://user-images.githubusercontent.com/1152930/52415241-c061f280-2ae6-11e9-9676-49933e10f795.png)

**Comment by maxokorokov** [comment]
Closed in #2972

**Comment by fbasso** [comment]
To be complete about this issue, the popover width has a  'constraint' because of its container. Adding container="body" solve the width problem:

![image](https://user-images.githubusercontent.com/1152930/52416036-f43e1780-2ae8-11e9-884e-fadea27795b9.png)
