### ISSUE TITLE
Bug(datepicker) Number of weeks must be auto configured or have a possibility to receive date.

### ISSUE THREAD

**Issue by NudeFox** [ng-bootstrap/ng-bootstrap#2670]
![image](https://user-images.githubusercontent.com/17131070/44859768-734b3c00-ac7d-11e8-9f87-00b86162b5cc.png)
Like shown above, if we need to show the outside days, the last row will be redundant. What we could do now is to specify the number of weeks, but if set to 5 it will cut some current month days. 
Current structure allows us only to check if this day is hold by the currentMonth so then we could or hide every day that is not in this month or show much more than needed.

**Comment by maxokorokov** [comment]
I wouldn't say it's a bug, because this is done to avoid changing widget/popup height when navigating between months. Also it looks more consistent when having multiple month view.

I would even prefer to remove the existing `collapse` value for the `[outsideDays]` input and leave it at `visible | hidden`.

You have, however, the complete control on how each individual day is displayed. So I'd say you have to hide those days by using a custom template and set the height of those days to 0 if necessary. They are not focusable anyway.

**Comment by NudeFox** [comment]
@maxokorokov Thanks for reply, we have a custom template for days, but not for the month. Maybe you could advise how can i make a check that all days in a week row are not in the current month. As the only possibility is to check if only 1 day belongs to current month.

**Comment by maxokorokov** [comment]
@NudeFox, played with it, but it turns out to be quite complex...

Here is a workaround: https://stackblitz.com/edit/angular-yyrkua

I'll have to think how to simplify it from the API point of view
