### ISSUE TITLE
Documentation request for angular 6 bootstrap pagination implementation with data

### ISSUE THREAD

**Issue by IntreXonReborn** [ng-bootstrap/ng-bootstrap#2672]
The examples at https://ng-bootstrap.github.io/#/components/pagination/examples are just not enough.
I do not understand how I would display elements page to page, whether I can control the number of elements to display, etc.

**Comment by benouat** [comment]
Sorry for the long time silence here, I've just discovered your issue today.

Let me try to clarify that a bit.

The tree important pieces to play with in order to operate pagination are:

1. `collectionSize`: Number of items in collection. i.e. the total number of items the pagination should handle
2. `pageSize`: Number of items per page. i.e. the number of items a page should contain.
3. `page`: The current page

All of this being already documented in the [Api](https://ng-bootstrap.github.io/#/components/pagination/api) documentation tab

**BUT** what you have to keep in mind, is that this widget is **just a display widget**. It can only display information related to pagination. It **won't** actually **perform** the pagination itself.

In order to do the pagination, you will need to use an `*ngFor` somewhere in you page that will also use the same information from `collectionSize`, `pageSize` and `page`

The expression inside this `*ngFor` could be something like:

```html
<tr *ngFor="let item of items | slice: (page-1) * pageSize : (page-1) * pageSize + pageSize">
</tr>
```

and pagination element would be:

```html
<ngb-pagination 
  [(page)]="page"
  [pageSize]="pageSize"
  [collectionSize]="items.length"></ngb-pagination>
```

Hope it helps ! I will certainly use this answer to create an overview page on the documenation itself.
Nonetheless I am closing this issue for now.
