### ISSUE TITLE
ngbAccordion doesnt open panels from activeIds array when coming from another page with router

### ISSUE THREAD

**Issue by kernyden** [ng-bootstrap/ng-bootstrap#2675]
hey, mates, pls can u help me in understanding why i cant display activeIds on ngbaccordion on another page while i using router(i have accordion with title name of projects, im going from accordion with click on title project, on main page, to another on another page) ? i try to catch em on OnInit, AfterView** hooks with "this.acc.activeIds = this.arr.map((el, i) => `ngb-panel-${i}`);" but nothing happens. It works(panels are open) only when i reload page, although acc.activeIds already have had  array with panels to open. I think im doing smth wrong or doesnt understand how to do with it.

**Comment by benouat** [comment]
Hi there would you mind creating a reproducible scenario of what you want to achieve in a Stackblitz or Plunkr

> But before fixing a bug we need to reproduce and confirm it. In order to reproduce bugs we will systematically ask you to provide a minimal reproduction scenario using http://plnkr.co.

> A minimal reproduce scenario using http://plnkr.co/ allows us to quickly confirm a bug (or point out coding problem) as well as confirm that we are fixing the right problem. The best part is that you do not need to create plunks from scratch - you can fork one from our [demo page](
https://ng-bootstrap.github.io/#/components).

**Comment by kernyden** [comment]
@benouat thx, also have done, stackblitz goes to reload page when i come back to previous path, but any way with click on project and go to second-page route mine acc.activeIds dont have open state. How i can fix this? any hook cant help me or provide directive to html as [activeIds], i tried(

**Comment by benouat** [comment]
To prevent stackblitz reloading the page you should always use the hash mode of the router

```typescript
RouterModule.forRoot(route, { useHash: true })
```

**Comment by kernyden** [comment]
@benouat thx, updated stackblitz
https://stackblitz.com/edit/angular-7g3yp5?file=src%2Fapp%2Fapp-routing.module.ts

**Comment by kernyden** [comment]
@benouat hey, i need some help with it, can u orient me on time, its very important issue for me

**Comment by pkozlowski-opensource** [comment]
@kernyden I'm sorry but the code in your stackblitz is non-obvious to me so I'm having hard time reproducing the issue. To be honest, I don't even see what the issue is...

Could you please provide more context?
* what steps should I take to reproduce (where to click and in which order);
* what is the observed vs. expected behaviour?

**Comment by kernyden** [comment]
@pkozlowski-opensource hi, u need to click on one of the acc panels on main-page(which u like to), then u will see that panels on next route(second-page)) are just closed, why - i dont know:( . Then if u go back to main page - panels are closed too, but i want to see em are opened

**Comment by pkozlowski-opensource** [comment]
There were 2 problems in your stackblitz:
* you were missing `id`s on panels (ex. ``);
* `activeIds` is an `@Input` to be used from a _template_ (https://ng-bootstrap.github.io/#/components/accordion/api)

When you fix those 2 issues things start to work as expected (at least based on my understanding of your use-case): https://stackblitz.com/edit/angular-aclycd?file=src%2Fapp%2Facc-list%2Facc-list.component.ts

Closing as a support request.

**Comment by kernyden** [comment]
@pkozlowski-opensource thx so much, fixed my problem, sorry for wasting ur time,very glad to have a helpful and vanilla framework equal to technical support;)

**Comment by hillin** [comment]
From future: this is a gotcha which we stumbled upon recently. The first time a ngbAccordion is loaded, it assigns the ids `ngb-panel-0`, `ngb-panel-1` ... `ngb-panel-{{n}}` to the panels by default (if they don't have ids assigned manually); but when you take a detour to another page and come back again, these panels will have ids `ngb-panel-{{n+1}}` ... `ngb-panel-{{2n + 1}}`, so you can't manipulate the panels with the old ids any more. The solution is to manually specify ids for the panels.

Since the documentation also exploits the default ids in the examples, I think this pitfall deserves a line in the documentation.
