### ISSUE TITLE
Error In NgbModalRef

### ISSUE THREAD

**Issue by mayank12psingh** [ng-bootstrap/ng-bootstrap#2708]
I am using NgbModalRef but facing error.

Can't resolve all parameters for NgbModalRef: (?, ?, ?, ?).

I have gone through other documentation they said it's a version problem,I  am working on latest version.
Here is snap shot of my version.
![error bootstrap](https://user-images.githubusercontent.com/41679796/45413980-016cec80-b698-11e8-8b2e-db36961a2ac7.png)

Snap shot of my error.
![error bootstrap-2](https://user-images.githubusercontent.com/41679796/45414111-46911e80-b698-11e8-81dd-269633d9111b.png)

**Comment by maxokorokov** [comment]
Hey,

If you think that it's a bug, unfortunately, we'll need the minimal reproduction scenario with StackBlitz or Plunker, you can clone one of the demos from https://ng-bootstrap.github.io/#/components/modal/examples

Also please check the way you import the ng-bootstrap library and dependencies between your modules as it looks like a some sort of DI problem.

If you are unsure if this is a bug or not than please use an appropriate support channel: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help

**Comment by maxkorz** [comment]
@mayank12psingh I think the problem is that you have `@angular/core: ^6.0.3` in your `package.json`. It means that you have `@angular/core >=6.0.3 <7.0.0` (most likely you have version `6.1.7` installed).
And you have `@ng-bootstrap/ng-bootstrap: ^2.2.0`, which means that you're not using the latest version (`^3.0.0`).

`@ng-bootstrap 2.x.x` can work only with Angular `6.0.x`: https://github.com/ng-bootstrap/ng-bootstrap#dependencies

You should update your dependencies and see if that solves the problem.

**Comment by pkozlowski-opensource** [comment]
Closing for now as we haven't heard back with a reproduce scenario.
