### ISSUE TITLE
Why forRoot method will be remove from all module in 4.0

### ISSUE THREAD

**Issue by patelhub** [ng-bootstrap/ng-bootstrap#2720]
forRoot  function is useful in lazy load  Angular application.
e.g. if I import NgbModalModule  in appModule and lazyLoadModule(lazy load for some path), this will inject two instance of "NgbModal" service for root module and lazyLoadModule.

may be, There is no problem if you add forChild(without providers) and remove forRoot.
I want only one instance of service through out application(including lazyload modules).

**Comment by pkozlowski-opensource** [comment]
With Angular `^6.1.0` we don't need `.forRoot()` any more as we can achieve the same behaviour with the newly introduced `@Injectable({providedIn: 'root'})`. This simplifies usage of our library as users don't have to think of adding `.forRoot()` _and_ it makes providers tree-shakable - all good benefits.

> if I import NgbModalModule in appModule and lazyLoadModule(lazy load for some path), this will inject two instance of "NgbModal" service for root module and lazyLoadModule.

This is intended - each lazy loaded module should have its own instance of the `NgbModal` service (so it can access appropriate component factory resolver).

Closing as a support request since the changes are intended. Feel free to comment if this is causing any real-life issues in your application.

**Comment by intellix** [comment]
@pkozlowski-opensource does this mean that importing NgbModalModule into both AppModule and LazyModule will cause it to jump from 10kb (modal) to 50kb (entire lib)?

I'm seeing it happen here when trying to debug why my app grows every version of Angular to the point where I'm importing all of:
 - 200kb of Core
 - 130kb of RX
 - 50kb of NgbBootstrap etc
