### ISSUE TITLE
Accordion title is overflowing when using a long text

### ISSUE THREAD

**Issue by shabbir-dhangot** [ng-bootstrap/ng-bootstrap#2724]
### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: Latest

ng-bootstrap: Latest

Bootstrap: Latest

**Comment by pkozlowski-opensource** [comment]
It is a bug in Bootstrap CSS (https://github.com/twbs/bootstrap/issues/26954) that is already fixed in their master branch (https://github.com/twbs/bootstrap/pull/27010). The fix will be part of the next Bootstrap CSS release.

Some background: Bootstrap's accordion is using `<button>` elements with `.btn` CSS class for accordion panel titles: https://getbootstrap.com/docs/4.1/components/collapse/#accordion-example

The `.btn` CSS class [used to have](https://github.com/twbs/bootstrap/pull/27010/commits/ab4008c637106c16f884911443f272f83e4494a0) the `white-space: nowrap;` property thus preventing text from wrapping.

You can wait for the next Bootstrap release (4.2) to have it fixed or modify CSS on your side. Closing it here as it is not actionable on our side - it is pure Bootstrap CSS issue.
