### ISSUE TITLE
Using unescaped '#' characters in a data URI body is deprecated

### ISSUE THREAD

**Issue by dm-grinko** [ng-bootstrap/ng-bootstrap#2812]
[Deprecation] Using unescaped '#' characters in a data URI body is deprecated and will be removed in M71, around December 2018. Please use '%23' instead. 

It is definitely due to ngb-carousel b/c when I remove this part of code the warning message is disappeared. 
```
            <ngb-carousel [interval]="100000" *ngIf="getImagesCount(p).length > 1">
                    <ng-template ngbSlide *ngFor="let item of getImagesCount(p)">
                      <img *ngIf="p['image' + item]" [src]="p['image' + item]" style="width: 100%;">
                    </ng-template>
            </ngb-carousel>
```

**Comment by maxokorokov** [comment]
Can't see the relation between a URI and ng-bootstrap components. It's you who fetch the data and generate URLs for carousel to use. Maybe the issue is in `p['image' + item]` ?

if you believe that we've got a bug in this library than please provide a minimal reproduce scenario in a stackblitz: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#you-think-youve-found-a-bug

Everything looks fine here: https://ng-bootstrap.github.io/#/components/carousel/examples
