### ISSUE TITLE
Dropdown component not working in Firefox

### ISSUE THREAD

**Issue by andreas-aeschlimann** [ng-bootstrap/ng-bootstrap#2873]
The second example of dropdowns does not work in Firefox 63.0.3 (tested on Mac OS 10.14), while it seems to be working in Chrome.

**How to reproduce**:
Use Firefox, go to https://ng-bootstrap.github.io/#/components/dropdown/examples.
Click the second example "Manual and custom triggers", click the button "Toggle dropdown". In Firefox, nothing happens on button click.

**Comment by benouat** [comment]
@andreas-aeschlimann Thank you for reporting this behaviour. Nonetheless this is not a bug.

I would suggest that the issue is the other way around, Firefox has the normal behaviour. Chrome should not open on click.

The demo has been crafted to use [NgbDropdownAnchor](https://ng-bootstrap.github.io/#/components/dropdown/api#NgbDropdownAnchor) instead of NgbDropdownToggle.

[NgbDropdownToggle](https://ng-bootstrap.github.io/#/components/dropdown/api#NgbDropdownToggle) is the one listening to `click` events, NgbDropdownAnchor is not.

**Comment by andreas-aeschlimann** [comment]
Thanks for your reply, I actually thought it was an issue of Firefox, not of Chrome. Good to know!
