### ISSUE TITLE
Pagination component is not responsive (doesn't wrap)

### ISSUE THREAD

**Issue by talynone** [ng-bootstrap/ng-bootstrap#2877]
### Bug description:
When pagination has enough pages to extend beyond the available width of the screen it doesn't wrap. I tried adding 

`class="d-flex flex-wrap justify-content-center"`

to the ngb-pagination html tag but that had no effect. It needs to be added the ul tag that has the pagination class applied to it to have an effect. As a hacky work-around in my style.scss Sass I use an extend on the .pagination class to include those other classes:
```
@import "~bootstrap/scss/bootstrap";

.pagination
{
  @extend .d-flex, .flex-wrap, .justify-content-center;
}
```
If you remove the above class extend in the stackblitz's style.scss example linked below you can see the default behavior.

For those who wish to not implement Sass, the following in style.css should also work:

```
.pagination
{
  display: -webkit-box;      /* OLD - iOS 6-, Safari 3.1-6 */
  display: -moz-box;         /* OLD - Firefox 19- (buggy but mostly works) */
  display: -ms-flexbox;      /* TWEENER - IE 10 */
  display: -webkit-flex;     /* NEW - Chrome */
  display: flex;             /* NEW, Spec - Opera 12.1, Firefox 20+ */
  justify-content: center;
  -webkit-justify-content: center;
  flex-wrap : wrap;
  -webkit-flex-wrap: wrap;
}
```

### Link to minimally-working StackBlitz that reproduces the issue:
https://stackblitz.com/edit/bootstrap4paginationflex

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 7.0.4

ng-bootstrap: 4.0.0

Bootstrap: 4.1.3

**Comment by pkozlowski-opensource** [comment]
> When pagination has enough pages to extend beyond the available width of the screen it doesn't wrap.

@talynone this is not what I'm seeing... What is the browser that you are using? Could you please share screen-shoots of the expected vs. actual rendering?

**Comment by talynone** [comment]
@pkozlowski-opensource  I'm using Chrome x64 Version 70.0.3538.102 on Windows 10. You have to comment out the ".pagination" override in style.scss to see it without my fix. 

Expected Rendering:
<img width="960" alt="ng bs4 pagination - way it should look" src="https://user-images.githubusercontent.com/2554644/48964533-5f526600-ef5e-11e8-8bb3-c32de6791d16.png">

Actual Rendering:
<img width="960" alt="ng bs4 pagination - way it does look" src="https://user-images.githubusercontent.com/2554644/48964549-d851bd80-ef5e-11e8-8b32-064806e319ab.png">

**Comment by talynone** [comment]
You think it worse to vertically scroll a bit over side scrolling for pages and pages and pages and pages? We'll have to agree to disagree there?

And in the case of a center justification you can't even scroll left. 

This was brought up specifically because a user complained about the side scrolling. Also restricted size is a mask/patch on the issue not a fix, just because it's just "wide enough" for a particular screen doesn't mean it will adapt properly for other resolutions.

Any time a UI element has to break out of its contain to be visible is an enormous design no-no.

And as far as Bootstrap itself fixing the issue, there's nothing for them to fix because the ul element is exposed in Bootstrap so a user can apply the style directly which is what they recommend in their issue list, however this doesn't apply to the ng bootstrap component since in ng bootstrap the ul element is encapsulated away from direct access in html.

**Comment by pkozlowski-opensource** [comment]
> And as far as Bootstrap itself fixing the issue, there's nothing for them to fix because the ul element is exposed in Bootstrap so a user can apply the style directly which is what they recommend in their issue list, however this doesn't apply to the ng bootstrap component since in ng bootstrap the ul element is encapsulated away from direct access in html.

Agree. We either need to expose the same flexibility or propose sth else. As such I'm going to re-open this issue. Having said this I believe that @benouat suggestion is best in this case:

> In that specific case, I would myself use the Advanced pagination with the option Restricted size with rotation

**Comment by benouat** [comment]
Ok, let's think about what we could do here, even though I **strongly** disagree with

> there's nothing for them to fix

I do believe that they **should** fix it. If we were talking about aligning items (such as what you can do by adding `justify-content-*`) here they don't have anything to do. You stick your extra class, `.pagination` being `display: flex` it's working.

BUT for `flex-wrap`, to me it's 100% a bug. They **should** add this, it does not make sense to not have it (for all the reason that have been mentioned, that I agree with). `.pagination` is `display: flex` and all sub `.pagination-link` won't shrink because their width is somehow limited by paddings => hence my feeling that `flex-wrap: wrap` should be part of initial implementation...

Nonetheless they do not plan to do that, and won't fix it. 😞 

https://github.com/twbs/bootstrap/issues/23504
<img width="776" alt="image" src="https://user-images.githubusercontent.com/1152740/49220503-add88800-f3d6-11e8-98be-f4c297eaa5c5.png">

https://github.com/twbs/bootstrap/issues/21505

So what could we do ?
1. Change `<ngb-pagination>` to be `<ul ngbPagination>` ? this would be a non backward compatible change...
2. Open a new `@Input() class` to propagate classNames from the host to the underlying `<ul>` ? then anyone would open issues to do the same on all other widgets... I am not in favour of that...
3. Simply use your workaround ?

I guess you could now understand why I decided to close this issue yesterday, obvious and reasonable choice would be 3 ... Maybe I am totally wrong.

---

PS: @talynone see @**mdo** comment going into the same direction I suggested... long pagination should be displayed differently 😃

**Comment by benouat** [comment]
This issue is old and not moving that much, hence I'll close it as won't fix anything.
---
As a final thought anyone can always do the CSS trick by defining some `flex-wrap` in their code by creating such a selector: `ngb-pagination.pagination { ... }`.

**Comment by Syed-Saad-Qamar** [comment]
I'm case I faced the pagination width issue that exceeds the same like that
[](https://user-images.githubusercontent.com/1152740/49165467-93000800-f331-11e8-98ca-4dd1c847e384.png)

I fixed that by adding `[maxSize]="5"`

**Comment by zag2me** [comment]
Came here from a google search as I had same issue when upgrading 3 to 5, just in case others get here I added:

.pagination {
  flex-wrap: wrap;
}

to my custom css.
