### ISSUE TITLE
Accordion long ngbPanelTitle not word-wrapping when reducing browser size

### ISSUE THREAD

**Issue by troddick** [ng-bootstrap/ng-bootstrap#2954]
### Bug description:
Having a long ngbPanelTitle, then resizing browser window to mimic mobile widths, the title extends beyond container, rather than word-wrapping. Seems the newer version uses an h5 tag with an inner button tag whereas older version of ng-bootstrap (2.0) uses an anchor tag with an inner span (this version does the word-wrap. I'd like to keep the newer version, but have the word-wrap happen when browser window size decreases.
working properly: https://angular-kakf4g.stackblitz.io

### Link to minimally-working StackBlitz that reproduces the issue:
https://brllapxyybyp.angular.stackblitz.io

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 6.1.8

ng-bootstrap: 3.2.0

Bootstrap: 4.0.0

Thanks!
Tonia

**Comment by benouat** [comment]
Hi @troddick,

Thanks to report this issue.
As a matter of fact, since you opened it, we landed a fix via #2915 into master that is not yet part of a release (should land on release 4.0.2) which is fixing your issue
 
Here is a screen-capture demonstrating the awaited behaviour:

<img width="459" alt="image" src="https://user-images.githubusercontent.com/1152740/51526402-8cbe7180-1e32-11e9-9f0c-d6ca5a33d116.png">

Hence, I will close this issue.

**Comment by benouat** [comment]
In the coming days. Should be tomorrow or the day after 👍

**Comment by benouat** [comment]
@troddick 4.0.2 containing this fix has landed!
