### ISSUE TITLE
ngbTabTitle custom class

### ISSUE THREAD

**Issue by alainbelez** [ng-bootstrap/ng-bootstrap#2967]
i can't seem to find out how to add custom class to `ngbTabTitle`. i would like to add a button far to the right just like this picture, and i can't seem to figure out to add classes on .nav-item
![image](https://user-images.githubusercontent.com/6648110/51191441-5ad37980-191f-11e9-8d69-d2913bbf499e.png)

**Comment by maxokorokov** [comment]
Since version `5.2.0` there is a new `NgbNav` set of directives that fix this issue. `NgbNav` is meant to replace the `NgbTabset` component (completely deprecated in version `6.0.0`) as a more flexible alternative.

I suggest you migrate to it → https://ng-bootstrap.github.io/#/components/nav/overview
