### ISSUE TITLE
Consider testing ng-bootstrap 5.x through Angular 8.x

### ISSUE THREAD

**Issue by mendeza** [ng-bootstrap/ng-bootstrap#2987]
Does it make sense to test [NGB v5](https://github.com/ng-bootstrap/ng-bootstrap/milestone/73) through [Angular v8](https://github.com/angular/angular/blob/master/CHANGELOG.md)?

**Comment by maxokorokov** [comment]
@mendeza we have currently two dependencies: bootstrap and angular, so whenever we bump any of them, we **have** to bump major ng-bootstrap version. 

We try to minimise the impact whenever possible and not bump versions needlessly (ex. currently we still test against bootstrap 4.0.0, but fix, if there are issues with 4.1.x). On the other hand, after adding a bootstrap toast component and moving to 4.2.x, we won't have much choice, but release a major version.

Also if there are breaking changes because of, say, typescript version in Angular 8 or yet another bootstrap version is released with new features we need to support - we won't be able to do much, but bump a major version.

So, I think at the moment we won't be able to commit to this. If you're have ivy support in mind, I guess, it's a different question.
