### ISSUE TITLE
Type 'FormGroup' does not satisfy the constraint 'ObservableInput<any>'.   Property '[Symbol.iterator]' is missing in type 'FormGroup' but required in type 'Iterable<any>

### ISSUE THREAD

**Issue by KsAkira10** [ng-bootstrap/ng-bootstrap#3007]
![image](https://user-images.githubusercontent.com/12545124/52428195-a2958d00-2ae8-11e9-887d-2d3b0d1dedb3.png)

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: v6.1.10
ng-bootstrap: v4.0.2
Bootstrap: v4.2.1
rxjs: v6.4.0

after upgrade version to current release.

**Comment by maxokorokov** [comment]
Hey @KsAkira10!

- ng-bootstrap `4.0.2` requires Angular `7.0.0` → https://github.com/ng-bootstrap/ng-bootstrap#dependencies
- regardless of it, the issue you're having is in **your code**, most likely due to typescript version change

Check if you changed `typescript` version or one of your `tsconfig.ts` files and either downgrade to supported ng-bootstap version for Angular 6 or update to Angular 7. Cleaning node_modules/npm cache also might help

Please feel free to reopen if you still have any issues after this.

**Comment by KsAkira10** [comment]
Hey @maxokorokov!

This is error occurs because of the rxjs. Where "from<any>" changed to "from<Promise<any>>"

sorry that hahaha

thank you to pay attention!
