### ISSUE TITLE
NgbTabset: Can I disable the selection of the active tab by default?

### ISSUE THREAD

**Issue by AlexZanel** [ng-bootstrap/ng-bootstrap#3194]
I want no tab to be active by default.
Or could I do this by hiding the tab, which is active by default?

**Comment by benouat** [comment]
Hello @AlexZanel !

I am not sure to understand what you are trying to achieve.
If none of the tab would be selected, it means that visually the placeholder containing the tab content would be empty. Hence, to me, what you describe looks like a simple menu...

Menu that could be dynamically upgraded/enhanced into being a tabset as soon as one of the links is clicked. Because Bootstrap re-uses same styling for both things (menu and tabset) I would almost be imperceptible that we moved from one to another.

**Comment by benouat** [comment]
@AlexZanel any update on this topic? was my comment helpful? It's been almost over a month, I would like to be able to move on...

**Comment by pkozlowski-opensource** [comment]
Closing this issue for now a we haven't heard back from @AlexZanel
