### ISSUE TITLE
Samples for server side pagination

### ISSUE THREAD

**Issue by PrabakarKaruppasamy** [ng-bootstrap/ng-bootstrap#3200]
Suggest some samples for server side pagination with ng-bootstrap

**Comment by benouat** [comment]
Hey @PrabakarKaruppasamy !

Could you please elaborate a bit more about _server-side_ aspect of it ? Did you have a look at our [pagination overview](https://ng-bootstrap.github.io/#/components/pagination/overview) ? Did you want to use _SSR_ (Server Side Rendering) and use our widget in here ?

**Comment by PrabakarKaruppasamy** [comment]
@benouat 

I want it server side rendering. That means I need to send a page number(ex, 1 or 2 or 3), page size(10 or 20 or 30) and the collection items also i need to set it from server.

**Comment by benouat** [comment]
Then I am afraid I won't have any helpful solution for you.

There is nothing special in any of our widget in order to use them with SSR. Unfortunately, we don't have _(yet?)_ any example, nor sample to demonstrate that...

Once you've set it up in the client-side part, you have access via `@Input` bindings to `page` and `pageSize` which both correspond to `page number(ex, 1 or 2 or 3)` and `page size(10 or 20 or 30)`.
For the collection items, as stated in the documentation overview, it's not related at all to the pagination itself.

Closing as not really an issue, and we won't provide any relative help in the closest, nor mid-term future.
Sorry for that.
