### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by jijishthomas** [ng-bootstrap/ng-bootstrap#3240]
### Bug description:
While importing 
import { NgbdPopoverTriggers } from './popover-triggers';

I'm getting error
Cannot find module './popover-triggers'.

I face this issue when importing all other components

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 6

ng-bootstrap:3

Bootstrap:4

**Comment by benouat** [comment]
Hey @jijishthomas !

It's not clear to me. What are you trying to do ?

The thing you are trying to import here is from our demo codebase. It's not part of ng-bootstrap...

Do you get this error trying to open a demo into Stackblitz ? Are you trying to use that demo in your application ? If yes, why, and how ?

I need more info in order to provide you some help!

**Comment by jijishthomas** [comment]
i need to trigger a popover from a controller/class

how can i do this?

**Comment by benouat** [comment]
@jijishthomas keep in mind that we usually don't do any support request via issues. Please have a look [here](https://ng-bootstrap.github.io/#/getting-started#getting-help)

---

Nonetheless, from your very generic description _i need to trigger a popover from a controller/class_, I can only see  2 types of answers:

+ You have an `<ngb-popover>` defined somewhere in one of your templates, and you want to access the popover instance from the correspondant component typescript class. To do that, you could use the **exportAs** feature:
 ```html
 <ngb-popover #myPopover="ngbPopover"></ngb-popover>
 <!-- later somewhere in your template, you can use this variable as an argument to any component class methods -->
 <button type="button" (click)="doSthg(myPopover)"></button>
 ```

+ You want to open an arbitrary popover from an arbitrary component class and/or service (a bit in the way you would do with modal) → **it's not doable**!

I will then close this issue because of the no-support via issues policy but I hope my explanations might help!

**Comment by benouat** [comment]
@jijishthomas Sorry my snippet of pseudo code here was a bit confusing.

Let me show you another way, or a more proper way at least, to do what you want to achieve.

```html
<select class="custom-select mb-5"
  ngbPopover="What a great tip!"
  [autoClose]="false"
  triggers="manual"
  #pop="ngbPopover"
  popoverTitle="Pop title"
>
  <option>One</option>
  <option>Two</option>
  <option>Three</option>
  <option>Four</option>
</select>

<button type="button" class="btn btn-outline-secondary mr-2" (click)="pop.open()">
  Open popover from template reference
</button>

<button type="button" class="btn btn-outline-secondary mr-2" (click)="open()">
  Open popover from component
</button>

<button type="button" class="btn btn-outline-primary mr-2" (click)="pop.close()">
  Close popover
</button>
```

```typescript
import {Component, ViewChild} from '@angular/core';
import {NgbPopover} from "@ng-bootstrap/ng-bootstrap";

@Component({
  selector: 'ngbd-popover-triggers',
  templateUrl: './popover-triggers.html'
})
export class NgbdPopoverTriggers {
  @ViewChild("pop") private popover: NgbPopover;

  open() {
    this.popover.open();
  }
}
```
