### ISSUE TITLE
Continuous overwrite class on "ngb-popover-window".

### ISSUE THREAD

**Issue by harshkoralwala** [ng-bootstrap/ng-bootstrap#3309]
Hello,

I want to integrate ng bootstrap popover in my angular 7 application.

My package.json looks like:
"@ng-bootstrap/ng-bootstrap": "^4.1.3",
"bootstrap": "^4.0.0",

In browser's developer tools i can see continuous flicker effect for "ngb-popover-window" element's class attribute.

Refer below image which is as of popover open state.

![Screenshot from 2019-07-24 15-01-11](https://user-images.githubusercontent.com/33347464/61782645-0952fc80-ae24-11e9-956a-b23b8a9dbfa6.png)

As result i can see continuously class "popover bs-popover-right" is overwrite/flicker effect.

My html looks like...
  `  <button type="button" class="btn btn-outline-secondary mr-2" placement="right"
                    ngbPopover="Vivamus sagittis lacus vel augue laoreet rutrum faucibus."
                    popoverTitle="Popover on right">
                    Popover on right
                  </button>`

So what is reason for it?how can i solve it?

Thank you in advance.

**Comment by fbasso** [comment]
Thank you @harshkoralwala  for reporting a potential bug.

My first idea is that you maybe have something triggering change detection over the time while the popover is open. See #3241 or #3290 for example. In this case, the first thing to do is to understand the origin of this change detection and see if it's valid (it can cause performance issue, not only for popover).

Otherwise, according to our documentation, if [You think you've found a bug](https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug), could you please reproduce your scenario in a minimalist Stackblitz in order for us to start working on it ?

**Comment by harshkoralwala** [comment]
Hello @fbasso,

Thank you for your reply.
I  looked for change detection in my project, I Found **setInterval** is continuously executing on my component.
I just removed that code and now my popover issue solved.

Thank you.
