### ISSUE TITLE
ARIA hidden element must not contain focusable elements

### ISSUE THREAD

**Issue by stabback** [ng-bootstrap/ng-bootstrap#3319]
This library is a great example of accessible software.  Thanks for the whole team for your attention to these things.  The following may not be resolvable, but I don't see it raised as a bug yet.  

### Bug description:
After opening a modal, axe-core reports [ARIA hidden element must not contain focusable elements](https://dequeuniversity.com/rules/axe/3.2/aria-hidden-focus).

When a modal is open, `aria-hidden="true"` is applied to the app-root.  All focusable elements in the page are nested and hidden, but still tabable.

As the focus trap _should_ prevent a user from activating any of these controls this may be a false positive.  If it is, a note in the documentation about this may be all that's needed / possible.

A programatic solution may be to look for all focusable elements in the DOM on modal open and store a reference to them.  Apply `tabindex="-1"` to these elements, and on modal close reset tabindex to its previous state per element.  Any changes to the hidden elements will not be tracked though, which is pretty error prone.  This solution feels janky.

### Link to minimally-working StackBlitz that reproduces the issue:
Any of the StackBlitz's on the modal demo page work: https://ng-bootstrap.github.io/#/components/modal/examples

Steps:
1. Ensure you have a means to run an axe scan on an interacted website. I use the [axe-core chrome extension](https://chrome.google.com/webstore/detail/axe/lhdoppojpmngadmnindnejefpokejbdd).
2. Open any of the StackBlitz pages, then open the run in a new window
3. Open the modal
4. Run the scan

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 8.1.3
ng-bootstrap:5.0.0
Bootstrap: 4.3.1

**Comment by fbasso** [comment]
Thanks for reporting @stabback !

Indeed, the focus trap is here to prevent focus outside the modal when it's open, and true, I found nothing mentioning it (so maybe it's something to add in the documentation).

Regarding the solution of adding tabindex, I'm not sure it's a good idea. It will be a redundant feature with the focus-trap, and a heavy one to implement.

**Comment by benouat** [comment]
Hey @stabback 

Sorry to be very very late to the conversation here. I was reviewing @IAfanasov' work on the topic in #3703 

I am confused, and I don't think there is any issue in here regarding the modal.
Here is a screen capture of the markup generated:

![image](https://user-images.githubusercontent.com/1152740/84371053-617c2400-abd9-11ea-9237-5ebe86b62e3c.png)

We are indeed adding `aria-hidden="true"` to the application root, _but pay attention_, that **both** the backdrop and the modal itself are appended to the body and hence, they don't belong the app root in terms of DOM nodes.

Hence, all focusable nodes (that are trapped by focus trap) are not in a DOM parent on which there is `aria-hidden="true"`

So, yes we probably still have focusable elements inside the application by the time a modal is opened, but none of them should ever gain focus (because of focus trap).

I'll close the issue, as for now we won't change anything soon regarding that.
As @fbasso said, dynamically changing tabIndexes on all focusable elements would definitely add a huge overhead in DOM read/write. So it would not be an option here.
---

**Sidenotes**: I understand there is this Axe rules, but I have never seen what we put in place being an issue with screen readers (at least in not in Jaws), and we battle tested this solution at least 3 previous frameworks in my past experiences.
