### ISSUE TITLE
Use your datetime picker with my own JS and CSS

### ISSUE THREAD

**Issue by fallais** [ng-bootstrap/ng-bootstrap#3352]
You say in the documentation that the goal of ng-bootstrap is to completely replace them, fine, but, we it comes to the navbar for example, it is a pain.. Boostrap is bootstrap and should be treated as a library of the project (I mean my project). Your library can be see as a wrapper I guess ?

Moreover, I need to control my own JQuery versions in my project..

Is there a way to use your library, especially the datetime picker (which is great BTW), by including boostrap normally ? I mean, with `npm install bootstrap --save` ?

Thanks a lot

**Comment by benouat** [comment]
Hello @fallais,

It's not clear what you want to achieve.

If you just want to use our datepicker widget with standard raw bootstrap (CSS+jQuery) then the answer is **no you can't do that**.

Our library has a vital dependency on angular. We say that you don't need jQuery with our library, because we replaced all the _original_ jQuery code by some _angular_ components/directives.

Then for your last point, our dependence on bootstrap is standard, nothing custom. People have to `npm install bootstrap --save`. We simply only the use the CSS artefact of it.

Ideally we would love to have a simple dependency on `npm install bootstrap-css` but unfortunately for us, this **does not exist**. It might exist one day, just no now.

Hope my explanation are clear!

**Comment by fallais** [comment]
Hello @benouat , yes it is clear.

Problem is, if I move to **ng-bootstrap**, which is tempting.. the bootstrap navbar is broken for example. And I totally rely on ng-bootstrap dependency. I mean I cannot control the JQuery version anymore. What if I use stuff that needs JQuery ?

Fact is I really need a powerful datetime picker, and yours is surely the best I could find.. I am a bit stuck.

**Comment by benouat** [comment]
> Problem is, if I move to ng-bootstrap, which is tempting ...  I mean I cannot control the JQuery version anymore

I would strongly not recommend to use ng-bootstrap with any  jQuery bootstrap plugin.
Options are:
+ either to stick with `bootstrap CSS` + `bootstrap jQuery`
+ or `bootstrap CSS` + `Angular` + `ng-bootstrap`

Mixing would be a very very bad idea

> the bootstrap navbar is broken for example

Why? and how ?

**Comment by fallais** [comment]
I was talking about using something that needs JQuery, I don't know what, a color picker for example, le'ts imagine there is one that is cool and that works with a specific version of JQuery.

For the navbar, it does not collapse anymore if I move to ng-bootstrap, I heard that there is a trick, but   I feel like it is not normal to trick because it should be bootstrap basic feature.

Hope I am clear. And thanks for helping me :)

**Comment by benouat** [comment]
> I was talking about using something that needs JQuery, I don't know what, a color-picker

Again, if you decide to use `ng-bootstrap` I would **strongly** recommend to not use **any** jQuery plugin!

Using `ng-bootstrap` means your entire world should be angular-based somehow. So if you want to use any external widget, you **should not** look for a jQuery color-picker, but you **should** look for an angular color-picker 

For the navbar, yes, with ng-bootstrap you have a bit of _plumbing_ angular code to be written. But nothing hard. It's just an `*ngIf` 🤣

**Comment by benouat** [comment]
Closing as not really an actual issue.
