### ISSUE TITLE
Navbar ngbDropdown is appearing at the end of the document

### ISSUE THREAD

**Issue by ahmadakra** [ng-bootstrap/ng-bootstrap#3359]
### Bug description:
I managed to minimally reproduce it on stackblitz, the dropdown appears at the end of the document without any "transform: translate" style applied to it.
I also noticed that when I remove the "navbar" class from the parent div, the dropdown appears in the correct place.

Thanks for your help.

### Link to minimally-working StackBlitz that reproduces the issue:
https://stackblitz.com/edit/angular-rj8cz6?file=app/dropdown-basic.html

### Versions of Angular, ng-bootstrap and Bootstrap:
Angular: 8.2.4
ng-bootstrap: 5.1.1
Bootstrap: 4.3.1

**Comment by fbasso** [comment]
Thanks for your comment @ahmadakra.

It is because the dropdown has a 'special' behavior inside a navbar, as it is done in Bootstrap (https://getbootstrap.com/docs/4.3/components/dropdowns/#menu-alignment). The positioning is static, that's why you don't see the transform style.

So in this situation, either you should remove `container="body"` (best to get responsive behavior for small screen), or you should get the dynamic behavior back by adding `display="dynamic"`

See https://ng-bootstrap.github.io/#/components/dropdown/examples#navbar and https://ng-bootstrap.github.io/#/positioning#dropdown for more information.
