### ISSUE TITLE
Better handling for progress bar with max=0

### ISSUE THREAD

**Issue by devoto13** [ng-bootstrap/ng-bootstrap#3386]
### Bug description:

Currently progress bar with the max value of 0 fills for the width necessary for the label to display. This is not consistent behavior and it will be better to make max=0 a special case and always fill either 0% or 100%. 

I think 100% will be a more sensible behavior because of cases like value=42 and max=0. In this case progress bar will [trim value to 0](https://github.com/ng-bootstrap/ng-bootstrap/blob/75f09660671577cd7988e6d93332b7749f76db25/src/progressbar/progressbar.ts#L74), but 100% will make some sense in this situation unlike 0%.

### Link to minimally-working StackBlitz that reproduces the issue:

https://stackblitz.com/edit/angular-mc1mw9

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 8.2.0

ng-bootstrap: 5.1.0

Bootstrap: 4.3.1

**Comment by maxokorokov** [comment]
> Currently progress bar with the max value of 0 fills for the width necessary for the label to display

Well, from what I see `style="width: ..."` is not set at all when `max === 0` → this looks like a bug and should be fixed.

**Comment by devoto13** [comment]
The real question is what value should be displayed in this case. 
It may be as well worth throwing the error when max=0 as a not intended usage of the component.

**Comment by maxokorokov** [comment]
I don't think it should fail with an error, it should just render the component correctly. 

What's wrong with having `max === 0`? When max is 0, you just can't go beyond 0. Looks pretty consistent to me.

This issue from my point of view is that:
```html
[value]="10" [max]="0" [showValue]="true"
```

Gives:
![Screen Shot 2019-10-04 at 14 24 31](https://user-images.githubusercontent.com/8074436/66207327-c8dcee00-e6b2-11e9-9b9e-9fb31a60879a.png)

- `NaN` instead of `0`
- doesn't apply `style="width:..."`

Let's discuss changing default behaviour in #3390

**Comment by maxokorokov** [comment]
Also should update the docs, saying that max SHOULD be a positive value

**Comment by maxokorokov** [comment]
Ok, on reflection and playing with standard progree, I think we should do what `<progress>` does and fallback `max` to default value which is `100` in bootstrap.

Left a comment in the review: https://github.com/ng-bootstrap/ng-bootstrap/pull/3400#pullrequestreview-303128262
