### ISSUE TITLE
hover over on accordion header?

### ISSUE THREAD

**Issue by chr1soscl** [ng-bootstrap/ng-bootstrap#3387]
This is a question, how can I detect a hover over the accordion header? I want to display a button only when the user is hover overing the header panel.

**Comment by maxokorokov** [comment]
Please use an appropriate support channel in future → https://github.com/ng-bootstrap/ng-bootstrap#getting-help

This might help:

- take a look at this demo → https://ng-bootstrap.github.io/#/components/accordion/examples#header
- since BS 4.3 there is also this option → https://getbootstrap.com/docs/4.3/utilities/stretched-link/
- probably CSS hover will be enough
