### ISSUE TITLE
ng-bootstrap doesn't work in Angular 8

### ISSUE THREAD

**Issue by Master-Antonio** [ng-bootstrap/ng-bootstrap#3389]
Hi guys, ng-bootstrap doesn't work in Angular 8.
I followed the instructions of https://ng-bootstrap.github.io/#/getting-started but without result.
This is my app.module.ts
```
import {BrowserModule} from '@angular/platform-browser';
import {NgModule} from '@angular/core';
import {HttpClientModule} from '@angular/common/http';
import {ReactiveFormsModule} from '@angular/forms';
import {FormsModule} from '@angular/forms';
import {NgbModule} from '@ng-bootstrap/ng-bootstrap';

import {AppComponent} from './app.component';
.......... other imports ......

@NgModule({
  declarations: [
    ............
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    ReactiveFormsModule,
    HttpClientModule,
    FormsModule,
    NgbModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})

export class AppModule {
}

```

Thanks so much for your help.

**Comment by devoto13** [comment]
@Master-Antonio Please follow the issue template instead of removing it and provide the necessary information: versions of Angular, ng-bootstrap and bootstrap packages, minimal reproduction of the issue and the error you're receiving. Without this information it is impossible to help you as ng-bootstrap does work with Angular 8 for a lot of people.

**Comment by Master-Antonio** [comment]
Ah sorry so much. My fault.
Can you delete this issue that i create one new ....
