### ISSUE TITLE
Feature request: Allow tabset header to be placed below the content

### ISSUE THREAD

**Issue by cloakedch** [ng-bootstrap/ng-bootstrap#3404]
It would be great if there was a way to relocate the tabs of a tabset to the bottom of the component. Currently they are always at the top.

**Comment by peterblazejewicz** [comment]
Folks,
This could be probably fairly quickly done using template/container mix. 
PoC (without required CSS changes). Remarks?

https://gist.github.com/peterblazejewicz/b1439a1068eac97562cd53358cdcfaa0

![image](https://user-images.githubusercontent.com/14539/66349679-b6381280-e959-11e9-80fb-f233c2f15447.png)

**Comment by maxokorokov** [comment]
I think this is yet another issue that should be fixed by #2693

**Comment by maxokorokov** [comment]
Since version `5.2.0` there is a new `NgbNav` set of directives that fix this issue. `NgbNav` is meant to replace the `NgbTabset` component (completely deprecated in version `6.0.0`) as a more flexible alternative.

I suggest you migrate to it → https://ng-bootstrap.github.io/#/components/nav/overview
