### ISSUE TITLE
Dismissing one of stacked modals dismisses keyboard/backdrop events for all modals

### ISSUE THREAD

**Issue by kshitizsingh93** [ng-bootstrap/ng-bootstrap#3515]
## Bug description:

When using stacked modals to prevent dismissal of first level modal, dismissing the second level modal by keyboard/backdrop disables the keyboard/backdrop for first modal too.

### Link to minimally-working StackBlitz that reproduces the issue:
https://stackblitz.com/edit/angular-dhs8oz

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 8.2.14

ng-bootstrap: 5.1.4

Bootstrap: 4.4.1

**Comment by masoudDaliriyan** [comment]
I guess this behavior because of the returned Promise in `modalService.open` don't resolve when dismissing  modal, thus first opened modal can't be closed 

 @pkozlowski-opensource @maxokorokov 
 I don't know why in `components/modal/modal-ref.ts` the promise is resolved when the modal is closed and rejected when the modal is dismissed.

I changed to resolve the promise when is dismissing in `components/modal/modal-ref.ts` at `_dismiss` method   and the bug going to fixed


I try to make PR for this issue

**Comment by kshitizsingh93** [comment]
I think promise rejection is the intended way to dismiss a modal, so we can distinguish between a negative result and no result. The first opened modal can still be dismissed by calling activeModal.dismiss.

My guess was the keyboard and backdrop event listeners are detached before 'beforeDismiss' is called.

**Comment by benouat** [comment]
I don't think we do anything special about keyboard events in here. We rely on rxjs `fromEvent`, so we don't detach anything before `beforeDismiss` is called.... weird o_O

**Comment by kshitizsingh93** [comment]
I tinkered a little bit more and discovered that you can dismiss the first modal by calling activeModal.dismiss() and dismiss the second modal by keyboard/backdrop any number of times before this bug appears, this only happens once you dismiss the first modal by keyboard/backdrop.

I haven't looked under the hood but shouldn't that point to slightly different implementation of the keyboard/backdrop events?

**Comment by eddietisma** [comment]
This is a new bug introduced with [this ](https://github.com/ng-bootstrap/ng-bootstrap/commit/cbf2b3c463308c476eb3b0131576aa7f6994d106#diff-8fb1cd1cc4cf9a5207c30f1474b6c8b9)change.

I'm pretty sure it has to do with unsubscribing the dismissEvent using `takeUntil` - disregarding whether it returned true or not.
