### ISSUE TITLE
Suggestion: expose the ngbAutofocus directive seperately?

### ISSUE THREAD

**Issue by GillesVercammen** [ng-bootstrap/ng-bootstrap#3658]
We have a small reusable button component and another reusable modal component.
The modal component makes use of the reusable button component and we want to take advantage of the autofocus directive that ng-bootstrap provides.

To do this we add directive conditionally in the button component like this:
` [attr.ngbAutofocus]="autoFocus ? '' : null"`

But to use this directive here, we need to import the full NgbModalModule in our button ngModule.
Ideally i think it should be nice to only be able to import the needed directive instead of the full NgbModalModule. 

What do you think about this?

**Comment by benouat** [comment]
Hello @GillesVercammen 

I am afraid you've over engineered a bit how `ngbAutofocus` is working.
There is absolutely no piece of code behind it (i.e. it's not at all a directive) It's just a simple HTML attribute that we use internally to perform a querySelector upon in order to focus the element if any...

https://github.com/ng-bootstrap/ng-bootstrap/blob/9000108190938ef7916ae1c4edd481d3515d8a3b/src/modal/modal-window.ts#L102-L108

What probably misleading for you, is the `ngb` prefix here. We used it, as we could not use the standard default `autofocus` attribute for that, but nonetheless, wanted to expose the exact same 
behaviour

Hope it helps 😃 

--- 

So as there is nothing to export, I'll gently close the issue.
