### ISSUE TITLE
Bootstrap 5 support

### ISSUE THREAD

**Issue by maxokorokov** [ng-bootstrap/ng-bootstrap#3667]
An issue to track Bootstrap 5 support on our side:
- [ ] Check what are breaking changes / new features
- [ ] Build with `alpha` version of Bootstrap
- [ ] Popper 2 as a dependency (#3579)
- [ ] Versioning on our side (BS 4.4 LTS or not?)
- [ ] Drop IE support in our code. Impact?

cc @benouat @fbasso

**Comment by bastienmoulia** [comment]
For your first point:

## Breaking changes
### Popovers
- Renamed `.arrow` to `.popover-arrow`
### Tooltips
- Renamed `.arrow` to `.tooltip-arrow`

## New features
### Modals
- New sizes for fullscreen (`fullscreen`, `fullscreen-sm-down` ...)
### Icons
- Use bootstrap icons by default for datepicker and timepicker

## Docs and E2E
### Badges
- Removed and replaced `.badge` modifier classes with background utility classes (e.g., use `.bg-primary` instead of `.badge-primary`)
### Forms
- A lot of changes in the classes

Using https://deploy-preview-29925--twbs-bootstrap.netlify.com/docs/5.0/migration/

**Comment by fbasso** [comment]
Regarding popper 2, I started to implement it through this PR : #3671

Some issues there, but it can be a good starting point.

**Comment by GeertJohan** [comment]
Bootstrap 5 has hit Alpha.
https://blog.getbootstrap.com/2020/06/16/bootstrap-5-alpha/

**Comment by Stajor** [comment]
Bootstrap 5 alpha-3 in progress
https://github.com/twbs/bootstrap/projects/22

When is the alpha version of ng-bootstrap coming out?

**Comment by maxokorokov** [comment]
See #3899 from now on
