### ISSUE TITLE
Tooltip inside table with pagination is not working

### ISSUE THREAD

**Issue by juliandamass** [ng-bootstrap/ng-bootstrap#3675]
### Bug description:
Using tooltip inside table which using pagination from ng-bootstrap is not working, tooltip wont show

### Stackblitz link:
https://stackblitz.com/edit/ng-bootstrap-table-example

**Comment by pkozlowski-opensource** [comment]
Note: this is a problem in our example since each change-detection re-renders the entire table.

**Comment by juliandamass** [comment]
Hi, thank you for your response, any update for this?

**Comment by juliandamass** [comment]
Hello, any progress?

**Comment by jnizet** [comment]
@juliandamass As Pawel explained, this is just a bug in the example (not in tooltips) because the array of countries is recomputed at each change detection, instead of being computed only when required. 

If you fix the example (using the same strategy as the one used in the other table examples, i.e. recomputing the countries and storing them in a property each time the page or the number of items per page changes), then thetooltips wll work. Here's a modified stackblitz fixing the bug: https://stackblitz.com/edit/ng-bootstrap-table-example-exdgze?file=app%2Ftable-pagination.ts

I will create a PR to fix the example.

**Comment by juliandamass** [comment]
This is what I'm looking for, thank'a a lot @jnizet 
Appreciate for your response @pkozlowski-opensource @jnizet
