### ISSUE TITLE
docs: range selection in a popup example's stackblitz goes to a 404 page

### ISSUE THREAD

**Issue by tonivj5** [ng-bootstrap/ng-bootstrap#3696]
### Bug description:
The link to stackblitz does't work

### Link to minimally-working StackBlitz that reproduces the issue:
https://ng-bootstrap.github.io/#/components/datepicker/examples#rangePopup click in stackblitz button, it goes to [404 page](https://ng-bootstrap.github.io/stackblitzes/datepicker/rangePopup/stackblitz.html) 
![image](https://user-images.githubusercontent.com/7110786/79999669-79c6a100-84bc-11ea-848d-a782cf8c902c.png)

### Versions of Angular, ng-bootstrap and Bootstrap:

I think it doesn't matter :laughing:

**Comment by fbasso** [comment]
This is because range-popup has been 'camelCased' instead of keeping the dash.

The url exposed is `https://ng-bootstrap.github.io/stackblitzes/datepicker/rangePopup/stackblitz.html`
The right one is `https://ng-bootstrap.github.io/stackblitzes/datepicker/range-popup/stackblitz.html`

We need to investigated why this url is built this way.
