### ISSUE TITLE
toast duplication when click multiple times

### ISSUE THREAD

**Issue by salah-yousef** [ng-bootstrap/ng-bootstrap#3723]
Hello 
I have a question 
how to prevent toast duplication when click open toast more than one time quickly 
I think it is important feature should be implemented 
thanks ..

**Comment by jnizet** [comment]
This question should be asked on Stackoverflow rather than here. 
A simple solution would be to emit an event from an RxJS Subject every time the user clicks to on your button. You would apply the debounceTime operator on this Subject and subscribe to the resulting observable in order to open a toast every time it emits an event. The debounceTime operator will eliminate clicks that are too close from each other

See https://rxjs-dev.firebaseapp.com/api/operators/debounceTime.

**Comment by salah-yousef** [comment]
Its a feature request not a question 
It's a feature that should be handled in the configuration object not rxjs as you suggested

**Comment by jnizet** [comment]
I fear this feature request will be rejected then. As the documentation explains, the toast component is just that: a component. It's your responsibility to provide a service that deals with displaying toasts whenever and however you want it done. And RxJS has all you need to implement this debounce functionality that you want i that service.

**Comment by benouat** [comment]
Hey @salah-yousef !
As @jnizet explained it, `NgbToast` component is just that. You have to manage them yourself.

---

> RxJS has all you need to implement this debounce functionality that you want i that service

You should investigate this.

Closing for now. Don't hesitate to ask StackOverflow also as mentioned. There are plenty of nice people wiling to help each others.
