### ISSUE TITLE
Forms in ngb-tabset

### ISSUE THREAD

**Issue by gbubemismith** [ng-bootstrap/ng-bootstrap#3739]
The ng-template that holds the content limits the use of the tabset. For example, If i have a form in the ng-template I can't access my template reference variable outside the ng-template. Why can't a div hold the tabset content instead of an ng-template.

**Comment by benouat** [comment]
Hey @gbubemismith 

There are various design considerations behind this decision.
The most important one is we don't want to have in the DOM all the nodes that are linked to the not active tab. Only usage of `<ng-template>` can provide that.

Have you also notice that nab-tabset is being [deprecated](https://ng-bootstrap.github.io/#/components/tabset/examples) in favour of nab-nav ? You should give it a try, maybe your issue would vanish with them. As it is only a set of directives, instead of components, you can achieve much more things. The API is much nicer!

Closing for now, as we won't change anything now regarding this.
Also, as mentioned in our documentation, we do not use issues as support channel. Please use Stack Overflow for that.
