### ISSUE TITLE
ngModel is not updating changes from .ts file

### ISSUE THREAD

**Issue by gvsakhil** [ng-bootstrap/ng-bootstrap#3740]
### Bug description:
When I add (selectItem)="addSourceFromSuggestions($event)" its not changing the value of ngModel from ts file

```
<input (selectItem)="addSourceFromSuggestions($event)" type="text" [(ngModel)]="sourceName"
              class="form-control" placeholder="Enter New Source" #newTabIp [ngbTypeahead]="search" id="searchSource">
```

### Link to minimally-working StackBlitz that reproduces the issue:

https://stackblitz.com/edit/ng-bootstrap-input

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 9.1.1

ng-bootstrap: 6.0.2

Bootstrap: 4.3.2

**Comment by IAfanasov** [comment]
Well, I see your code tries to update 'sourceName' twice. First with `addSourceFromSuggestions` and than with `[(ngModel)]="sourceName"`. So, the `[(ngModel)]="sourceName"` happens after `addSourceFromSuggestions`  and the value get overriden. You solution could be to use only one way binding `[ngModel]="sourceName"` or use the setTimeout inside the `addSourceFromSuggestions` so that source name updated after the ngModel binding happen. setTimeout is obviously smell and better avoid it.

**Comment by IAfanasov** [comment]
and this is not a support forum (: better to use stackoverflow for such questions. if you set proper tags in stackoverflow people will get notified anyway (:

**Comment by gvsakhil** [comment]
Whooo cool thanks @IAfanasov I didnt notice that settimeout can make that work... I thought its some bug may be with package so I reported here... Thanks for ur time :)
