### ISSUE TITLE
Popover not working in nested ngFor

### ISSUE THREAD

**Issue by clabough** [ng-bootstrap/ng-bootstrap#3742]
### Bug description:

When using the Popover in a situation where there's an ngFor inside an ngFor, the popover is not showing when clicking the button to cause it to show. The popovers do show if used within the first ngFor.

### Link to minimally-working StackBlitz that reproduces the issue:

https://stackblitz.com/edit/angular-fheky9

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 9.0.7

ng-bootstrap: 6.1.0

**Comment by jnizet** [comment]
Hi @clabough 

The bug is in your code: `getDateRangeArray()` always returns a brand new array of new objects, which means that at each change detection, you return a new array and force Angular to re-create DOM nodes.

If you fix this issue, everything works as expected. See https://stackblitz.com/edit/angular-fheky9-7njghy?file=src%2Fapp%2Fpopover-basic.ts.

**Comment by clabough** [comment]
Thanks. Confirmed in my real code that I was regenerating the array each change cycle. Fixed now.
