### ISSUE TITLE
Set minDate to last 100 years

### ISSUE THREAD

**Issue by beejay141** [ng-bootstrap/ng-bootstrap#3760]
Hi, the documentation is not clear on how to set minDate. kindly help

**Comment by jnizet** [comment]
It's an [input](https://ng-bootstrap.github.io/#/components/datepicker/api#NgbDatepicker), so you use an attribute of the component to set it. It's of type [NgbDateStruct](https://ng-bootstrap.github.io/#/components/datepicker/api#NgbDateStruct), so you need to pass an object which implements this interface, i.e. have three attributes day, month and year.
Since you want to pass an Angular expression of type object as input, you need to surround the `minDate` attribute in square brackets:

    [minDate]="{ year: 1920, month: 1, day: 1 }"

See this simple demo: https://stackblitz.com/edit/angular-czkfqa?file=src/app/datepicker-basic.html

Please, next time, ask such questions on StackOverflow rather than opening an issue.

**Comment by beejay141** [comment]
works, thanks alot

**Comment by jnizet** [comment]
Closing the issue, because I think the documentation is clear enough
