### ISSUE TITLE
Provide a ready to use toast service as shown in the examples

### ISSUE THREAD

**Issue by reda-alaoui** [ng-bootstrap/ng-bootstrap#3785]
### Bug description:

Provide a ready to user toast service as shown in the examples

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 9

ng-bootstrap: 6.1.0

Bootstrap: 4.5.0

**Comment by benouat** [comment]
Hey @reda-alaoui 

Sorry for the long time no response... but I am afraid that we won't bless your request.
We did not want on purpose to add this code to our bundle. This is why we created this Overview example.

The size of code to properly embed this use case as part of our public API is not worth it. Even though it could be worth it, because of modern tree-shakable ability for example, it always has been our philosophy in the project → we provide bare minimal widgets as part of the library, and usage use-cases as part of documentation.

Hence, I'll close this issue as won't fix. Again sorry.
