### ISSUE TITLE
developer console not letting me select an option from the drop down menu

### ISSUE THREAD

**Issue by jamalmehmood** [ng-bootstrap/ng-bootstrap#3818]
whenever ngbDropdownMenu overlaps with the developer console, it automatically focuses on the top of the screen. Please see the attached gif. Also, the selection also doesn't occur during this scenario.

![YRsOEhburF](https://user-images.githubusercontent.com/12895771/88175463-50deb500-cc3f-11ea-8c2a-e5f59c4acef2.gif)

**Comment by benouat** [comment]
Hey @jamalmehmood!
Thanks for the gif, it clearly shows something is not right, **but** without any version numbers, and without a minimal reproducible scenario in StackBlitz we can not assess if the problem is from our side or your side!

Please, reproduce the case in a minimal scenario in StackBlitz, otherwise we can't look a the issue.

**Comment by maxokorokov** [comment]
Closing as no response, please reopen if necessary.
