### ISSUE TITLE
not possible validate "ngbDatepicker" through W3C validator

### ISSUE THREAD

**Issue by mattia0123** [ng-bootstrap/ng-bootstrap#3820]
As title, seems not possible to pass validation with W3C since "ngbDatepicker" is a forbidden element

```
<input class="form-control" id="dateFrom" [formControlName]="'dateFrom'" 
name="dateFrom" ngbDatepicker #d1="ngbDatepicker" aria-describedby="dateFrom"> 
```
And here the W3C error:

`Error: Attribute ngbdatepicker not allowed on element input at this point.`

    "@angular/cli": "~9.0.3",
    "@ng-bootstrap/ng-bootstrap": "^6.0.3",
    "bootstrap": "^4.4.1",

**Comment by jnizet** [comment]
Hi!

You get the same error for `formControlName`, and for basically all attributes that are not specified in the HTML specifications. 

The whole principle of Angular is to "enrich" the HTML with custom attributes and elements that trigger the instanciation of directives and components. If you want your templates to pass W3C validation, I'm afraid you should not use Angular at all.

**Comment by mattia0123** [comment]
> Hi!
> 
> You get the same error for `formControlName`, and for basically all attributes that are not specified in the HTML specifications.
> 
> The whole principle of Angular is to "enrich" the HTML with custom attributes and elements that trigger the instanciation of directives and components. If you want your templates to pass W3C validation, I'm afraid you should not use Angular at all.

I am also of the opinion that w3c should not be used to validate html generated form angular. 
Despite this, my customer allows the development of SPA in Angular as long as they are validated on W3C (it seems to be his essential standard). 
Fortunately I got ridpf all the angular custom attributes, even the attributes binded to  the plugins directives. 
I just missing this one  to pass the validation. 
Any suggestions? 
would be highly appreciated. 

Thanks 
(I tried also on stack overflow without luck)

**Comment by benouat** [comment]
Hey @mattia0123 

I am afraid we won't be of any help here. 😞 We don't have any suggestions as we would even recommend people to **not** use W3C validation for templates.

Almost all validators are broken, because AFAWK any character could be used as valid in any attributes names if you strictly follow [HTML specifications](https://www.w3.org/TR/2011/WD-html5-20110525/syntax.html#attributes-0) (from W3C itself too....)

Closing for now.

**Comment by nicco88** [comment]
@benouat I have this problem too, because we must work with the validator as a requirement. What I just did is clone the project and add the [custom data attribute](https://www.w3.org/TR/2011/WD-html5-20110525/elements.html#custom-data-attribute) `data-ngbDatepicker` as selector. With `data-` it has no validation errors. Don't know if it could be a viable solution it's possible to work on...
