### ISSUE TITLE
Failed to parse Source map

### ISSUE THREAD

**Issue by ak274** [ng-bootstrap/ng-bootstrap#3828]
In Angular 10 application after installing the package it start giving following warnings in `dev `environment  as I have enabled the source map for debugging purposes. 

```
WARNING in D:/projects/luna/sola-luna/lunaWebApp/sola-luna/node_modules/@ng-bootstrap/ng-bootstrap/__ivy_ngcc__/fesm2015/ng-bootstrap.js    
Module Warning (from D:/projects/luna/sola-luna/lunaWebApp/sola-luna/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map: "ng:/@ng-bootstrap/ng-bootstrap/accordion/accordion-config.ts" URL is not supported

WARNING in D:/projects/luna/sola-luna/lunaWebApp/sola-luna/node_modules/@ng-bootstrap/ng-bootstrap/__ivy_ngcc__/fesm2015/ng-bootstrap.js    
Module Warning (from D:/projects/luna/sola-luna/lunaWebApp/sola-luna/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map: "ng:/@ng-bootstrap/ng-bootstrap/accordion/accordion.module.ts" URL is not supported
```

and so on...

**Comment by maxokorokov** [comment]
We would need reproduction steps for this, please. We haven't seen this issue before.

If you have a **minimal** Angular CLI project to clone (starting with empty an one, adding ng-bootstrap and reproducing the issue with sourcemaps), it would be helpful. Otherwise not much we can do.

Also please use the template, it's not cleat which version you're using, etc.

**Comment by benouat** [comment]
Closing as no feedback. Don't hesitate to re-open with proper information if needed
