### ISSUE TITLE
ngb-accordion not rendering with innerHtml.

### ISSUE THREAD

**Issue by MixonZ** [ng-bootstrap/ng-bootstrap#3875]
### Bug description:

ngb-accordion not rendering with innerHtml. No exceptions in console.
I'm migrating from ng-bootstrap 1.1.2 version to  7.0.0. Was working in older version.

### Link to minimally-working StackBlitz that reproduces the issue:

https://stackblitz.com/edit/ngb-accordion-problem?file=src%2Fapp%2Fapp.component.html

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 10.0.9

ng-bootstrap: 7.0.0

Bootstrap: 4.5.3

**Comment by pkozlowski-opensource** [comment]
> ngb-accordion not rendering with innerHtml. No exceptions in console.
> I'm migrating from ng-bootstrap 1.1.2 version to 7.0.0. Was working in older version.

Did it really work before??? Angular is _not_ processing directives / components on `innerHTML` so this sounds _very_ unlikely - probably something else was going on. 

I'm going to close this one as a support request since Angular does _not_ process markup injectected via `innerHTML` so there is not much we can do here on the library lelvel.
