### ISSUE TITLE
ngb-pagination  style and event

### ISSUE THREAD

**Issue by weiwangwang** [ng-bootstrap/ng-bootstrap#3942]
Hello.I am a novice, please ask everyone, how to set the trigger event or set the style for a page alone?It would be better if you could provide me with a small demo.Sincere thanks.

**Comment by weiwangwang** [comment]
@maxokorokov

**Comment by maxokorokov** [comment]
@weiwangwang please take a look at the [Getting Help](https://github.com/ng-bootstrap/ng-bootstrap#getting-help) section, I'd suggest using StackOverflow for these kind of questions.

Otherwise first take a look at the docs and demos we have:
- https://ng-bootstrap.github.io/#/components/pagination/overview#customization
- https://ng-bootstrap.github.io/#/components/pagination/examples#customization

You can alway use purely CSS
