### ISSUE TITLE
How can I use popupClass in Typeahead?

### ISSUE THREAD

**Issue by AI-Marvel** [ng-bootstrap/ng-bootstrap#4058]
### Bug description:
I want to change the background color of the typeahead pop-up box, but the document mentioned popupClass, but there is no method to use it. I wrote the following code according to my own understanding, but it didn't work。

app.component.html
`<input id="typeahead-template" type="text" placeholder="Search" (selectItem)="itemSelected($event)" [(ngModel)]="model" [ngbTypeahead]="search" [resultTemplate]="rt" popupClass="myclass"/>`

app.component.css
`.myclass{
  background-color: rgb(4, 4, 53);
}`

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular:11

ng-bootstrap:9.1

Bootstrap:4.6

**Comment by jnizet** [comment]
Since the custom class is used in the template of the typeahead, and not in your component's template, your component must have its view encapsulation set to `None`(see example here: https://stackblitz.com/edit/angular-t7mngq-hw24m6?file=src%2Fapp%2Ftypeahead-basic.ts), or the custom class must be defined in the global stylesheet (see example here, where the class is defied in the index.html head: https://stackblitz.com/edit/angular-t7mngq-5tr97v?file=src%2Findex.html).
