### ISSUE TITLE
Unable to open modal using just typescript

### ISSUE THREAD

**Issue by Sauravsam85** [ng-bootstrap/ng-bootstrap#4069]
I want to apologize in advance if this does not qualify as an issue but I just wanted to get some help with an issue in calling a modal window.

I am able to call modal window successfully when doing so through HTML:

<button type=button class="btn btn-custom" (click)="open(addQualmodal)"> > </button>

<ng-template #addQualmodal let-c="close" data-backdrop="static" tabindex="-1" keyboard="false" let-d="dismiss">
  <div class="modal-header">
    <h4 class="modal-title">Qualifier Add</h4>
    <button type="button" class="close" data-dismiss="modal" (click)="d('Close click')">&times;</button>
  </div>
</ng-template>

TS file
open(name:any) {
    this.modalService.open(name, { centered: true, scrollable: true, backdrop: 'static', keyboard: false, size: 'xl' });
  }

But I need to open a modal window through an event from another control on screen, which allows me to call the function but the modal opens but does not get set to the actual template but just the text is shown.

Trying to open like this:
this.open('addQualmodal');

Am I missing something?

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 8

ng-bootstrap: 5.3.1

Bootstrap: 4.3.1

**Comment by jnizet** [comment]
In your first snippet, `addQualmodal` is a template variable referencing the ng-template. Its type is `TemplateRef`. So that's what the typeof `name` should be too, instead of `any`.

In your second snippet, you're passing a string. A string and a template are very different things. Pass the template variable to your event handler, as you're doing in your first snippet. Or better, use a component rather than a template (as shown in https://ng-bootstrap.github.io/#/components/modal/examples#component.

Closing, because this whould be a Stackoverflow question (which should come with more code).
