### ISSUE TITLE
Using multiple carousel on a single page causing slides incremental count instead of resetting for each slider.

### ISSUE THREAD

**Issue by sarfarazansari** [ng-bootstrap/ng-bootstrap#4104]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
Am using multiple carousel on a single page. And would like to display the slides length and current slide number.
but am facing a weird issue the slides count getting incremental for all the carousels.
for eg: at my first carousel I have 10 slides and on other carousel I've 12 slides and length is vary for each carousel.
but when I try to get the active slide for the second carousel the count of active slide got incremented by first carousel.
while it should be starts with 0 for each carousel.

for more details check my screenshots.

![image](https://user-images.githubusercontent.com/3416989/119814491-14877f80-bf08-11eb-873e-ef0d2f670d98.png)
![image](https://user-images.githubusercontent.com/3416989/119814854-852e9c00-bf08-11eb-94c9-cd4ec813e3b0.png)
![image](https://user-images.githubusercontent.com/3416989/119814885-8e1f6d80-bf08-11eb-8a2e-4e7bd58bef3d.png)
![image](https://user-images.githubusercontent.com/3416989/119814908-95467b80-bf08-11eb-8c1b-f244397de181.png)

Expected behaviour should be:
each carousel slides should start from 0 to N.

### Versions of Angular, ng-bootstrap and Bootstrap:

"@angular/core": "~10.0.5",

"@ng-bootstrap/ng-bootstrap": "^8.0.4",

"bootstrap": "^4.6.0",

**Comment by jnizet** [comment]
Hi @sarfarazansari 

I tried to figure out what the problem is, but I couldn't understand.
If you're referring to the slide IDs, then it's perfectly normal (and documented) for them to be incremental. Those IDs are not supposed to contain the slide number. They're just unique identifiers, across the whole HTML document.

If you're referring to the text "29 of 28" on the second carousel, then this is not generated by ng-bootstrap, but by your own code, that we know nothing about. So this problem is in your hands.

Please clarify. The issue template asks for a reproduction in a stackblitz, and you haven't provided one. That doesn't help us helping you.

**Comment by sarfarazansari** [comment]
@jnizet I was expecting there should be some way by which we can Identify the active id for each carousel.
but I was looking it should reset to 0 for each while it is somehow calculating the whole document items.
I got your point that ID should be unique.
but what if we have multiple carousels on a single page and if we have to perform action by knowing current carousel count.
I guess I've to use some other carousel library.

**Comment by jnizet** [comment]
No need to use another library. Only to generate your own IDs and map them to the corresponding slide number. 

See https://stackblitz.com/edit/angular-fmr6vf?file=src%2Fapp%2Fcarousel-basic.ts for a complete example.

**Comment by sarfarazansari** [comment]
@jnizet that works fantastic thank you so much.
