### ISSUE TITLE
Change NgbModal size after open

### ISSUE THREAD

**Issue by jantvb** [ng-bootstrap/ng-bootstrap#4281]
I have a modal that initially has a size, but I want the modal to change size when I change a certain value in the form.

I have this in my component .ts file that open the modal:
const modalRef = this.modalService.open(ModalFormComponent, { size : 'xl', scrollable: true });

If in the modal an information changes the modal size needs to change to lg

**Comment by Grilly** [comment]
This a not recommended solution because it is using internal APIs of NgbModal, but the only solution I found:

In the modal create an Output...
```javascript
@Output() setNewModalSize = new EventEmitter<string>();
```
...and trigger that Output
```javascript
changeSize() {
  this.setNewModalSize.emit('YOUR_NEW_SIZE');
}
```

Then in the component that opened the modal you use this code:
```javascript
const modal = this.ngbModal.open(MyComponent);
modal.componentInstance.setNewModalSize
  .pipe(
    tap((size: string) => {
      // _windowCmptRef is an internal API this is why we need to use modal as any to circumvent TypeScript type checking
      (modal as any)._windowCmptRef.instance.size = size;
    }),
    // TODO do not forget to unsubscribe
  ).subscribe();
```

So we are able to communicate outside of the modal but we have no API so set the size of the modal after it was opened.

I am open for better solutions.
