### ISSUE TITLE
[Offcanvas] scroll bar is missing when use components as content.

### ISSUE THREAD

**Issue by harris2012** [ng-bootstrap/ng-bootstrap#4397]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:

scroll bar is missing when use components as content.

### Link to minimally-working StackBlitz that reproduces the issue:

https://stackblitz.com/edit/angular-k99n8b

as we can see, scroll bar is missing, content in offcanvas can not scroll.

![20221013182902](https://user-images.githubusercontent.com/12846977/195573466-ae1d4f8c-c645-441f-83be-cbc9230a8b27.png)

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 14.2.6
ng-bootstrap: 13.0.0
Bootstrap: 5.2.0

**Comment by jnizet** [comment]
Hi @harris2012 

Good catch. 
This is due to the fact that the header and body of the offcanvas are wrapped into the element of the custom component.
I'm not sure if there's a way to avoid that, but it can be wored around by setting some styles on the custom component, ad shown in this stackblitz: https://stackblitz.com/edit/angular-k99n8b-6urydg?file=src%2Fapp%2Foffcanvas-component.ts

```
  styles: [
    `
    :host {
      height: 100%;
      display: flex;
      flex-direction: column;
    }
  `,
  ]
```

**Comment by harris2012** [comment]
wow, it works, thanks a lot.
