### ISSUE TITLE
NgbModal is getting frozen, unable to close or make changes

### ISSUE THREAD

**Issue by sushilkar** [ng-bootstrap/ng-bootstrap#4406]
### Bug description:
```
import { NgbModal, ModalDismissReasons } from '@ng-bootstrap/ng-bootstrap';
```
and trying to load a modal. It was working with angular 13.x, but when upgraded to angular 14.x and when started using 13.x ng-bootstrap (https://www.npmjs.com/package/@ng-bootstrap/ng-bootstrap/v/13.1.0#dependencies) it was giving issues. The modal was getting frozen after loading, it wasn't able to close or go back to web app. 

Note: 12.x ng-bootstrap also didn't help. Downgrading to 11.x somehow resolve the issue. 

Ngbmodal setup is something similar to 
https://stackblitz.com/edit/ng-modal-demo?

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular:
14.2.7
ng-bootstrap:
13.x and 12.x 

Bootstrap:
5.2

**Comment by jnizet** [comment]
You need to post a reproduction of the problem. Without that, we can't really know what's happening.

**Comment by Depechie** [comment]
Not sure if this is the same issue, but we have a similar problem.
With the new version the grey backdrop is being displayed before the modal itself. Although both components have the fixed z-index 1050.
The only thing we noticed, is that this happens when the angular/material is also added.
There is also some mentioning on stack overflow: https://stackoverflow.com/questions/72066640/bootstrap-modal-dialog-is-disabled-in-a-project-where-material-modules-are-added

**Comment by maxokorokov** [comment]
Closing as no response, please reopen if necessary with a reproduction scenario.

**Comment by maliniFrenzy** [comment]
Hi,
Mine is similar .
Draggable doesn't work if it the modal content has iframe in it.

**Comment by aeroabrar-31** [comment]
> Hi, Mine is similar . Draggable doesn't work if it the modal content has iframe in it.

Hey, did you got the solution for this?
