### ISSUE TITLE
Problem with install on angular 14.2.0

### ISSUE THREAD

**Issue by hosseinGanjyar** [ng-bootstrap/ng-bootstrap#4454]
### Bug description:
When I want to install, have got error:
```
Found: @angular/common@14.2.12
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^14.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^15.0.0" from @ng-bootstrap/ng-bootstrap@14.0.0
npm ERR! node_modules/@ng-bootstrap/ng-bootstrap
npm ERR!   @ng-bootstrap/ng-bootstrap@"*" from the root project
```

### App version:
**Angular:**
```
"@angular/animations": "^14.2.0",
"@angular/cdk": "^13.3.0",
"@angular/common": "^14.2.0",
"@angular/compiler": "^14.2.0",
"@angular/core": "^14.2.0",
"@angular/forms": "^14.2.0",
"@angular/material": "^13.3.0",
"@angular/platform-browser": "^14.2.0",
"@angular/platform-browser-dynamic": "^14.2.0",
"@angular/router": "^14.2.0",
```

**ng-bootstrap:** _14.0.0_

**Bootstrap**: _5.2.2_

*Please don't reply that it's a duplicate of other issue, because I've wrote all of relevant issues.

**Comment by maxokorokov** [comment]
Could you actually please **read** the supported versions table I referenced in https://github.com/ng-bootstrap/ng-bootstrap/issues/4340#issuecomment-1370859644 ?

You should use `ng-bootstrap 13`.

```sh
➜  Angular ng version | grep CLI        
Angular CLI: 14.2.10
➜  Angular ng new -s -t --minimal cli142
? Would you like to add Angular routing? No
? Which stylesheet format would you like to use? CSS
CREATE cli142/README.md (1061 bytes)
CREATE cli142/.gitignore (548 bytes)
CREATE cli142/angular.json (3146 bytes)
CREATE cli142/package.json (784 bytes)
CREATE cli142/tsconfig.json (863 bytes)
CREATE cli142/.browserslistrc (600 bytes)
CREATE cli142/tsconfig.app.json (287 bytes)
CREATE cli142/.vscode/extensions.json (130 bytes)
CREATE cli142/.vscode/launch.json (301 bytes)
CREATE cli142/.vscode/tasks.json (531 bytes)
CREATE cli142/src/favicon.ico (948 bytes)
CREATE cli142/src/index.html (292 bytes)
CREATE cli142/src/main.ts (372 bytes)
CREATE cli142/src/polyfills.ts (2338 bytes)
CREATE cli142/src/styles.css (80 bytes)
CREATE cli142/src/assets/.gitkeep (0 bytes)
CREATE cli142/src/environments/environment.prod.ts (51 bytes)
CREATE cli142/src/environments/environment.ts (658 bytes)
CREATE cli142/src/app/app.module.ts (314 bytes)
CREATE cli142/src/app/app.component.ts (1450 bytes)
✔ Packages installed successfully.
    Successfully initialized git.
➜  Angular cd cli142 
➜  cli142 git:(master) ng add @ng-bootstrap/ng-bootstrap
Global setting: enabled
Local setting: disabled
Effective status: disabled
ℹ Using package manager: yarn
✔ Found compatible package version: @ng-bootstrap/ng-bootstrap@13.0.0.
✔ Package information loaded.

The package @ng-bootstrap/ng-bootstrap@13.0.0 will be installed and executed.
Would you like to proceed? Yes
✔ Packages successfully installed.
UPDATE package.json (923 bytes)
✔ Packages installed successfully.
Option "name" is deprecated: Use the "project" option instead.
UPDATE src/app/app.module.ts (385 bytes)
UPDATE angular.json (3252 bytes)
UPDATE src/polyfills.ts (2567 bytes)
```

This works perfectly fine in `package.json`:

```
"@angular/animations": "^14.2.0",
"@angular/common": "^14.2.0",
"@angular/compiler": "^14.2.0",
"@angular/core": "^14.2.0",
"@angular/forms": "^14.2.0",
"@angular/localize": "^14.2.0",
"@angular/platform-browser": "^14.2.0",
"@angular/platform-browser-dynamic": "^14.2.0",
"@angular/router": "^14.2.0",
"@ng-bootstrap/ng-bootstrap": "13.1.1",
"@popperjs/core": "^2.10.2",
"bootstrap": "^5.2.0",
"rxjs": "~7.5.0",
"tslib": "^2.3.0",
"zone.js": "~0.11.4"
```

**Comment by BojanKogoj** [comment]
That would mean we use Bootstrap 5, which is not what we want right now. Only `--legacy-peer-deps` save you here.

**Comment by tien-ekn** [comment]
Hi @maxokorokov , thank you for your work.

| ng-bootstrap | Angular | Bootstrap CSS | Popper |
| ------------ | ------- | ------------- | ------ |
| 13.x.x       | 14.1.0  | 5.2.0         | 2.10.2 |

Does the above table mean `ng-bootstrap` only works with Angular having specific patch version `14.1.0` and does not work with any other patch version like `14.0.0` or `14.2.0` ?

If `ng-bootstrap` does in fact work with other patch versions (i.e any Angular having `semver`  `^14.x.x`),
I think we can adjust the just the peer dependencies at https://github.com/ng-bootstrap/ng-bootstrap/blob/13.1.1/src/package.json#L43-L48.

To be more specific, changing the peer dependencies version from `^14.1.0` to `^14.x`, because using `^14.1.0` means telling npm that ng-bootstrap only works with `14.1.0`.

I'd like to quote from npm document (https://docs.npmjs.com/cli/v9/configuring-npm/package-json#peerdependencies):

> Trying to install another plugin with a conflicting requirement may cause an error if the tree cannot be resolved correctly. For this reason, make sure your plugin requirement is as broad as possible, and not to lock it down to specific patch versions.
>   
>   Assuming the host complies with [semver](https://semver.org/), only changes in the host package's major version will break your plugin. Thus, if you've worked with every 1.x version of the host package, use "^1.0" or "1.x" to express this. If you depend on features introduced in 1.5.2, use "^1.5.2".

**Comment by hosseinGanjyar** [comment]
@maxokorokov I read **supported versions table** but as you've seen my issue already, I used of **angular v14.2** and your table has no support for this specific version. **_V13_** of your library is just designed for **angular _v14.1.0_** !!!

@tien-ekn I appreciate you, and also have request from @maxokorokov to enjoy us and alter package.json.

**Comment by maxokorokov** [comment]
@tien-ekn, I see how the table can be confusing indeed. We should put `"minimal required versions"` in the description and maybe `^/~/>=` symbols. I think it might have been changed accidentally.

On the other hand `package.json` is correct, and using `14.2.0` is absolutely possible. We can't put `^14.0.0`, instead of `^14.1.0`, because we do depend on features introduced in angular core `14.1.0`.

The original issue was about using ng-bootstrap `14.0.0` with angular common `14.2.2`, which is not possible as I've already explained before.
