### ISSUE TITLE
Add support for Angular 16

### ISSUE THREAD

**Issue by saerx** [ng-bootstrap/ng-bootstrap#4498]
### Bug description:

I'm sure it is in the works, but thought I would add the request for a pre-release version of ng-bootstrap that supports Angular 16 now that the latter has been released.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 16 

Bootstrap: any

**Comment by abrahampe** [comment]
There is a PR on the road [feat: upgrade to Angular 16](https://github.com/ng-bootstrap/ng-bootstrap/pull/4501)

**Comment by ramonleenders** [comment]
> There is a PR on the road [feat: upgrade to Angular 16](https://github.com/ng-bootstrap/ng-bootstrap/pull/4501)

It hasn't been updated since creating the PR not replied upon. Is this still in active development? Would have thought it would be a bit quicker to release, since it is a pretty straight forward upgrade Angular wise? Got a project which I'd want to update to Angular 16, but this is a bit in its way due to CI/CD.

**Comment by GabrielMJin** [comment]
i updated my project, and it stopped picking up the lib

**Comment by abrahampe** [comment]
> i updated my project, and it stopped picking up the lib

So I did! I had to rollback to NG 15 again :-(

**Comment by md13381** [comment]
The problem is probably angular-builders hasnt been updated yet, which is probably delaying things

**Comment by klexas** [comment]
Manually installing via npm for example and not the ng builder works with some manual importing. But it's really frustrating as out of the box, its not compatible.

**Comment by klexas** [comment]
> Thanks for this! So is 14.2 compatible with Angular 16?

It is compatible, but you need to -force the install. 

I didn't see a `-force` option on the `ng add` so I had to use the `npm install` option - same packages, just a bit finer grain control. 

Forcing the packages (just ignores the version <16 warnings) I can confirm works perfectly.

**Comment by detobel36** [comment]
The new version on the master branch
Release version (14.2.0) is not compatible yet

**Comment by ClaasWilke** [comment]
I think it is a bit confusing that the issue was close althoug ng-bootstrap 14.2.0 is still not fully compatible with Angular 16. Building Angular projects with --force or --legacy-peer-dep is no real option for your CI/CD when handling multiple dependencies or working with dependency management tools like Renovate.

**Comment by pbarranis** [comment]
I don't see how any professional developer would be confused.  This is being tracked the same way every issue I've worked on in the last 20+ years across a half dozen companies, from Fortune 500s to SMBs, was tracked.  The developers do the work on the master/dev branch, and the issue is tracked against that progress.  Once the changes are committed to master, it's marked closed.  But the only way users see the result in a deployment is when that branch gets published in some form.

In this case, the issue was tagged against Milestone 15, which tells you that it will be published/deployed in v15.  You should star or watch that milestone as appropriate for you and your team.

Keep in mind that this is GitHub, not UserVoice.  On UserVoice and similar sites, PMs track public-facing issues separately of the system the devs actually use to get work done.  On GitHub you're seeing what the devs see (for most companies, anyways), so you get real-time insight into progress.  As developers, we know how useful that info is, but it requires understanding to know that there's a delay after work is completed before deployment/publishing happens.

Obviously, for whatever reason, this commit didn't make the cut for 14.2.  That's unfortunate, but it is what it is.  We all should be incredibly grateful for the hard work of the developers who provide this excellent project for free.  If you're unhappy with it, jump in and help.  I'm sure it would be a valuable learning experience.

FWIW, I worked around this issue in my project by overriding the versions that NPM pulls by putting the following section in my package.json.  Maybe there's a downside to this that I don't understand; I only dabble in front-end code, so I'm a n00b when it comes to Angular and NPM.  Maybe this will help someone else.  It only took me 15 mins of googling to find this solution, and it has so far worked fine in production.

    "overrides": {
      "@angular/common": "^16.0.0",
      "@angular/core": "^16.0.0",
      "@angular/forms": "^16.0.0",
      "@angular/localize": "^16.0.0"
    },

**Comment by amerikan** [comment]
> I don't see how any professional developer would be confused. This is being tracked the same way every issue I've worked on in the last 20+ years across a half dozen companies, from Fortune 500s to SMBs, was tracked. 

The problem is that not everyone has 20+ years like you, many are just starting on their developer journey and sometimes don't have the guidance. I, however, do appreciate you taking the time to share how releases work, I'm sure that will help many as they grow as developers. 👍🏼

**Comment by mpastor-stratio** [comment]
Hi... what about release candidate?... meanwhile...

**Comment by saerx** [comment]
Thanks very much devs for the new version release 👍

**Comment by Drelaky** [comment]
When I enter this code: 
ng add @ng-bootstrap/ng-bootstrap

how to solve my problem?

Then I get this error message:

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: karma-jasmine-html-reporter@2.0.0
npm ERR! Found: jasmine-core@5.0.0
npm ERR! node_modules/jasmine-core
npm ERR! dev jasmine-core@"~5.0.0" from the root project
npm ERR!
npm ERR! Failed to resolve the dependency:
npm ERR! peer jasmine-core@"^4.0.0" from karma-jasmine-html-reporter@2.0.0
npm ERR! node_modules/karma-jasmine-html-reporter
npm ERR! dev karma-jasmine-html-reporter@"~2.0.0" from the root project
npm ERR!
npm ERR! Conflicted codependency: jasmine-core@4.6.0
npm ERR! node_modules/jasmine-core
npm ERR! peer jasmine-core@"^4.0.0" from karma-jasmine-html-reporter@2.0.0
npm ERR! node_modules/karma-jasmine-html-reporter
npm ERR! dev karma-jasmine-html-reporter@"~2.0.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict or try again.
npm ERR! this command with --force or --legacy-peer-deps.
npm ERR! to accept an incorrect (and potentially incorrect) dependency resolution.
npm ERR!
npm ERR! For the full report, see C:\Users\Drelaky\AppData\Local\npm-cache\resolve-report.txt.

npm ERR! The full log of the run can be found at:
npm ERR!     C:\Users\Drelaky\AppData\Local\npm-cache\_logs\2023-05-28T13_50_15_849Z-debug-0.log
✖ Installation of packages failed, see above.

![image](https://github.com/ng-bootstrap/ng-bootstrap/assets/53569746/308b9fb6-4d77-496b-9e42-022d5b3f52b1)
![image](https://github.com/ng-bootstrap/ng-bootstrap/assets/53569746/93cd4f97-8aa6-48f4-8384-da5a7abd7082)
![image](https://github.com/ng-bootstrap/ng-bootstrap/assets/53569746/ed7115b6-b7b5-4fb2-af72-ddaab40fb7e8)
