### ISSUE TITLE
Add `items` to the `NgbAccordion`

### ISSUE THREAD

**Issue by vladkasianenko** [ng-bootstrap/ng-bootstrap#4505]
``` typescript
  @ViewChild('accordion', { static: true }) accordion: NgbAccordionDirective;

  private _activeTab: string;

  @Input()
  set activeTab(value: string) {
    this._activeTab = value;

    if (!!this.accordion && !!value) {
      this.accordion.toggle(value);
    }
  }

  get activeTab(): string {
    return this._activeTab;
  }
```

Gives me this error (I changed the name of some properties):
![image](https://github.com/ng-bootstrap/ng-bootstrap/assets/14053728/bde54ad1-8daf-4605-9f61-1cf82b5d4fad)

However, in the `NgbCarousel` there's a property `slides` which  is extremely useful.
``` typescript
    @ViewChild('carousel', { static: true }) carousel: NgbCarousel;

    private _activeTab: string;

    @Input()
    set activeTab(value: string) {
        this._activeTab = value;

        if (!!this.carousel?.slides && !!value) {
            this.carousel.select(`slide-${value}`);
        }
    }

    get activeTab(): string {
        return this._activeTab;
    }
```

As you can see, here I'm validating `slides` property: `!!this.carousel?.slides`.

Would it be possible to create something similar at the `NgbAccordion`: `!!this.accordion?.items`?

**Comment by maxokorokov** [comment]
Hmm, `slides` is not a part of a public API, so you shouldn't really depend on it.

For the accordion, it looks more like a bug to me, because of the issue with this unsafe thing:

https://github.com/ng-bootstrap/ng-bootstrap/blob/c52438414368d7806a4b327975ed683d8ea3625e/src/accordion/accordion.directive.ts#L453

`this._items` is `undefined`, but I can't reproduce it easily on my side. It seems you're setting `[activeTab]` too early, before the `@ViewChildren` in the accordion actually gets the list of items.

When are you doing it? Would you have a stackblitz?

---

1. I think I'll first add checks to ensure all these never fail even though accordion is not finished initialising:

```ts
accordion.toggle('one');
accordion.collapse('one');
accordion.expand('one');
accordion.expandAll();
accordion.collapseAll();
accordion.isExpanded('one');
```

2. Will think of exposing `get items(): NgbAccordionItem[]`
