### ISSUE TITLE
SSR does not apply bootstrap styles

### ISSUE THREAD

**Issue by kewur** [ng-bootstrap/ng-bootstrap#4659]
### Bug description:

When rendering with ssr, ngbootstrap does not apply bootstrap styles. on client with the browser everything looks fine however, Once rendered with "ng serve" view page source, copy content into a file called index.html and open with a browser. the button doesn't have the correct style applied.

adding the bootsrap.min to the index.html does fix this issue.

### Link to minimally-working StackBlitz that reproduces the issue:

not a StackBlitz but I have a project here

 https://github.com/kewur/ngbootstrap-ssr-notloading-style 

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 17.0.8

ng-bootstrap: 16.0.0

Bootstrap: 5.3.2

**Comment by jnizet** [comment]
Hi @kewur.

That's quite expected. The HTML page file needs CSS and JS files to work as expected. So just saving the index.html file and opening this file won't apply the styles defined in these non-existent files.

Besides, this doesn't have anything to do with ng-bootstrap.

**Comment by kewur** [comment]
interesting, so bootstrap isn't ssr compatible?

**Comment by jnizet** [comment]
Bootstrap is SSR compatible, like any othr CSS solution. But SSR-compatible does't mean that styles are magically applied to a page even when you save a page on the disk without its associated stylesheets and then open that page.
SSR consists in rendering a page on the server so that a browser, or a bot, can load the page and get HTML that is ready to read or crawl. But of course, browsers and bots, when they see a HTML page which links to a CSS stylesheet (which is also served by the web server), do download the CSS as well:

```
  Browser or bot                              Web server
  ______________                              __________

     1 ---------- GET index.html ---------------->

       <----------send bach index.html content --- 2

     3 read html, 
       find link to styles.css

     4 ---------- GET styles.css ---------------->

       <--------- send back styles.css content --- 5

     6 render styled page
