### ISSUE TITLE
Typeahead onSelect callback

### ISSUE THREAD

**Issue by AlexKhymenko** [ng-bootstrap/ng-bootstrap#606]
Is it possible to add typeaheadOnselect callback?

**Comment by pkozlowski-opensource** [comment]
Sure, this would be trivial to implement (wouldn't expect it to be more than 5 LOC). But I thought that it is not needed since we can use the ngModelChange event to know where the model gets changed. 

@AlexKhymenko as stated above this would be very easy to do but I don't want to duplicate the existing functionality. So could you tell us more about your use case and evaluate if `ngModelChange` wouldn't be enough?

**Comment by AlexKhymenko** [comment]
The problem comes ngModelChange fires on every user input. So when user pust 'al' it fill fire ngModelChange on every letter 'a' then 'l' before I even select Alabama.
The use case that i'm facing is when user selects for example Alabama he should go to Alabama page.

**Comment by pkozlowski-opensource** [comment]
Oh right! I was kind of assuming "no edit" mode, sorry for the noise. We should add this for the next alpha.

**Comment by AlexKhymenko** [comment]
Thank YOU! Very much!

**Comment by AlexKhymenko** [comment]
I'm not sure that its a good idea to name it ('select') cause input has its own select event(but it do different thing) and it could lead to unforeseen consequences .

**Comment by pkozlowski-opensource** [comment]
Grr, you are right @AlexKhymenko ! How about `itemSelect` or `selectItem`? Any other suggestions?

**Comment by AlexKhymenko** [comment]
selectItem is the best choice(to my mind). Another one is typeaheadOnSelect(but this one is not good with naming style you use across the whole app).

**Comment by pkozlowski-opensource** [comment]
@AlexKhymenko thnx. Here is the PR: #612

**Comment by AlexKhymenko** [comment]
@pkozlowski-opensource Thank You!!
