### ISSUE TITLE
Page refreshes when clicking on drop down menu

### ISSUE THREAD

**Issue by kolkov** [ng-bootstrap/ng-bootstrap#720]
### Bug description:
When I click on dropdown menu my page with youtube videos in iframes refreshes.

### Version of Angular, ng-bootstrap, and Bootstrap:
Angular 2 2.0.0-rc.6, ng-bootstrap 1.0.0-alpha.4, bootstrap 4.0.0-alpha.4

**Comment by pkozlowski-opensource** [comment]
> Link to minimally-working plunker that reproduces the issue

This is essential. No reproduce = we can't do much about it.

**Comment by kolkov** [comment]
@pkozlowski-opensource Where I can find working plunker with last ng-bootstrap? Thanks!

**Comment by jnizet** [comment]
@kolkov You can start from this plunkr: http://plnkr.co/edit/Z23tWp?p=info

**Comment by kolkov** [comment]
Thanks!
[plunker with dropdown navbar](https://plnkr.co/edit/jP2aDq83kDjENkvgL6M0)

**Comment by jnizet** [comment]
I have no idea what is the root cause of this, but here's what I can tell:
- the problem only shows up when there is an ngb-dropdown, and is caused by the document click listener used to close dropdown when we click outside
- even if the listener does nothing, the problem happens
- the problem does happens for any URL, not just youtube
- the problem doesn not happen if `src="theUrl"` is used instead of `[src]="trustSrcUrl(theUrl)`

**Comment by kolkov** [comment]
Maybe it somehow related with each other ...?
https://github.com/ng-bootstrap/ng-bootstrap/issues/687

**Comment by Quinn-L** [comment]
I think this is a quirk with Angular2 not ng-bootstrap. In my experience, inlining functions with bindings do not play well together.
What's happening is the document click event causes Angular to do a full view check. Since binding a function is technically returning a "new" object, Angular decides to refresh/recreate the iframe (its actually only the iframe changing, not the full page in your example). 
In this [updated plunker](https://plnkr.co/edit/6gC282X4dVwGidb5n0FN?p=preview), I changed your iframe `src` binding to a cached property.

**Comment by kolkov** [comment]
Аnd what are our next steps?

**Comment by pkozlowski-opensource** [comment]
> Аnd what are our next steps?

What @kolkov says. The issue at hand is not specific to dropdown but can be demonstrated with _any_ binding that triggers Angular dirty check. Just don't use a function when binding to video URL.

Closing as not related to this project. Thnx for tracking this @Quinn-L !

**Comment by kolkov** [comment]
@pkozlowski-opensource Very good, but the problem remains. In the first version AngularJS everything worked as it should. Maybe you should open a new issue on the Angular 2?

**Comment by kolkov** [comment]
@pkozlowski-opensource Thanks! I will raise the issue in the Angular 2.

**Comment by kolkov** [comment]
This Solution from Angular 2:

> Use pure pipe instead

```
@Pipe({ name: 'safe' })
export class SafePipe implements PipeTransform {
  constructor(private sanitizer: DomSanitizer) {}
  transform(url) {
    return this.sanitizer.bypassSecurityTrustResourceUrl(url);
  }
}
```
https://plnkr.co/edit/9JPA5r0gjTwfVckohihp?p=preview

**Comment by jbistis** [comment]
Does anyone have a fix for this?

**Comment by h0m36r0wn** [comment]
It seems this issue haven't resolved yet, but for the sake of the others you could   try adding type="button" attribute in your button :)
