### ISSUE TITLE
Range selection support in Datepicker

### ISSUE THREAD

**Issue by tonystar** [ng-bootstrap/ng-bootstrap#753]
We would like to use and help to maintain Datepicker component, but what is blocking us — range selection support. Attached is a sketch what we are looking for. Do you have any plans for this feature? Or any ideas how to implement with existing component?

<img width="429" alt="screenshot 2016-09-17 11 02 23" src="https://cloud.githubusercontent.com/assets/5911853/18606936/68cbacb2-7cc6-11e6-9820-196e0abb4db4.png">

**Comment by pkozlowski-opensource** [comment]
I think that you can implement a range Datepicker with the building blocks we've got in place. Some hints to implement:
* you would create a new control (implement `ControlValueAccessor`)
* you could stick 2 datepickers as part of your control
* you would have to provide a custom template to a day cell to mark it as "in range"

I would expect it to not take more than 1 day of dev with tests etc. 

We will be putting more demos on our website and probably will have some examples with range datepicker. But not planning to have a specific date-range-picker, no. I think that there are just too many UI variations for this so we would rather focus on providing basic building blocks and flex points so people can craft they own range pickers.

I'm going to keep it open so we can add more examples to our demo page.

**Comment by pkozlowski-opensource** [comment]
@tonystar don't hesitate to come up with a more detailed question if you bump into any roadblocks. We would be keen on adding necessery APIs / flex points so your use-case is covered. And of course would very much appreciate contributions to the datepicker (or any other component).

**Comment by tonystar** [comment]
Wow! Such comprehensive answer! I will invite our developers in this discussion and let's work together on the demo! We are adopting the ng-bootstrap from time it was created and looking forward for the new opportunities!

**Comment by PEsteves8** [comment]
I had the same question and I'm glad you're focused on the basic blocks that would allow developers to implement everything they might need. 

I actually did a variation of ng2-bootstrap that allowed me to selected multiple ranges (as long as the developer doesn't use the single date option). It has a lot of customization, like number of datepickers, default month selection controls removed, etc.

Here's the demo(the code needs serious refactoring):

https://pesteves8.github.io/dayselector/

Now to be honest, I would prefer to use the ng-bootstrap library (instead of the ng2-bootstrap) so I'll see if I can follow your advice to implement the same functionality, hopefully in less time that my first attempt.
I'll let you know if I run into any issues with the library :) .

**Comment by pkozlowski-opensource** [comment]
@PEsteves8 thnx for the info. Actually this is excellent timing to jump on datepicker-related use-cases as @maxokorokov is planning on exercising all the flex points of datepicker to make sure that you can cover all common use-cases (range picking being one of them). 

> I'll see if I can follow your advice to implement the same functionality, hopefully in less time that my first attempt. I'll let you know if I run into any issues with the library :) .

That would be awesome! I can promise that we will be _very_ reactive as datepicker use-cases are extremely important to us! Basically we want to get quickly to the point where one can cover use-cases seen on top / well-known web sites (booking, kayak, airbnb etc.). I think that we are not far from this goal :-)

**Comment by PEsteves8** [comment]
Thanks for the response. :) By the way, there isn't any easy way of removing the default month and year controls from the component (or at least disabling them as inputs), is there? Since they're fairly easy to create separately and that would make more sense for those developers who want to include multiple datepickers. Each of them, having their own controls would be a bit weird.

**Comment by pkozlowski-opensource** [comment]
> By the way, there isn't any easy way of removing the default month and year controls from the component (or at least disabling them as inputs), is there? Since they're fairly easy to create separately and that would make more sense for those developers who want to include multiple datepickers. Each of them, having their own controls would be a bit weird.

Currently there is the `showNavigation` option. But I agree that what would be even better is to be able to pass a custom component as navigation. I think that @maxokorokov had something on his mind for this.

**Comment by PEsteves8** [comment]
Oh, so that's what the `showNavigation` is for. Perfect. Thanks.

**Comment by PEsteves8** [comment]
Let me know if this is a library limitation. I didn't see an option to disable the days that do not belong to the month displayed (the days at the end and at the beginning). I don't want to have interaction with them. I tried to use the markDisabled like so:

```
disableDaysOutsideMonth(dateToTest: any) {
        return (date: NgbDateStruct) => {
            return date.month !== dateToTest.getMonth();
        }
    }
```
The dateToTest is naturally the month that belongs to that datepicker. The problem is that navigation stops working. Both standard navigation or using navigateTo() externally do nothing with this on.

I then tried using  a custom day template and apply a disable class or a display: none. However, they still work even if invisible.

Am I missing something obvious or is this a limitation?

**Comment by pkozlowski-opensource** [comment]
@PEsteves8 not sure I understand you correctly. Are you saying that you want that clicks on days outside of the current month do nothing? I mean, don't navigate to a previous / next month? 

> The problem is that navigation stops working.

Which navigation? The one that you can switch on / off with `showNavigation`? Sorry, it isn't very clear...

At this point I'm not sure if you are hitting a limitation or not as your last comment is not fully clear to me... Maybe you could start a plunk on which we could iterate to get to your desired functionality? Here is a simple one we could use as a starter: http://plnkr.co/edit/g044bYWfPBhRE5VxQfGf?p=preview

**Comment by maxokorokov** [comment]
@PEsteves8 I can't quickly reproduce you issue either. Especially with navigation not working

But of you want to hide completely the days that do not belong to current month and disable clicks, now you should **both** apply something like `display: none;` with a custom day template and disable them with `markDisabled`. The first will hide numbers, the second will disable mouse clicks.

```typescript
[markDisabled]='isDisabled'
...
function isDisabled(date) {
  return date.month !== currentlyDisplayedMonth;
}
```

The problem here might be getting this `currentlyDisplayedMonth` as looks like there is no easy way to do it currently. We should fix that or add something like `[showOnlyCurrentMonthDays]='true'` in the datepicker options as it might be quite a common use case.

**Comment by PEsteves8** [comment]
Sorry for not being clear and thanks for the plunker.

Here's my attempt at reproducing it. Since I want to have more than one datepicker, I feel like I have to have a specific markDisabled for each. There will be a variable that will indicate the month that is each one of them, so I created a currentMonth property that I pass in to the markDisabled function. The days get disabled, but changing months is not allowed for some reason.

Here's the plunker:

http://plnkr.co/edit/ygKSe4LygUQKqoBQ31sF?p=preview


A not related question. My previous implementation of multiple datepickers, made use of a timeOut triggered on mouseDown. If the mouse kept pressed for over 300ms, a rangeMode would be activated. Else, a normal single date toggle would run. I just realized that by making use of ngModelChange I don't have such control, as I only have the event ngModelChange, ie mouse clicks. Maybe I don't see how to make it work, because to be honest some parts of Angular are still a bit confusing for me like ControlValueAccessor, so it might have more to do with lack of knowledge.

**Comment by maxokorokov** [comment]
@PEsteves8 don't have a quick answer to your issue in the plunker, seems strange. Will have to take a deeper look. It works fine with a simple `isDisabled` function. It should be solved with the pull request above though, as you'll have the currently displayed month directly.

For your click issue, we don't plan to expose mouse events to the user just yet, but thinking about it. So I can't see an easy solution right now, maybe try handling clicks on your own in your custom day template? Will take note on your use case, it's an interesting one, though.

But stay tuned, there will be more to come to datepickers in the near future.

**Comment by PEsteves8** [comment]
Thanks. Yeah I just checked out the PR and it pretty much solves it. I'll see if the template works. If not, for now I'll just have a checkbox to activate a rangeMode.

I was really proud of the UX I did: https://pesteves8.github.io/dayselector/ xD

But for now I'm fine in accepting some limitations, and keeping things cleaner. since the code I wrote  was a chaotic mess using a previous library..

Thanks again.

**Comment by PEsteves8** [comment]
Just tried implementing the mousedown timeout system to run date selection using toggleMode or rangeMode and it works just fine. It's great that everything is really flexible. When the version with the currentMonth becomes available I'll have everything for my particular use case. Thanks.

**Comment by pkozlowski-opensource** [comment]
> It's great that everything is really flexible. When the version with the currentMonth becomes available I'll have everything for my particular use case. Thanks.

Awesome to hear this :-) I'm just sorting out last bits of AoT compilation and will cut the release then.

**Comment by PEsteves8** [comment]
Is there a planned approach at the range date mode?

With the launch of alpha-11 which includes multiple datepickers, I'll refactor my current widget (from my project) to make it so that the logic for multiple dates comes exclusively from ng-bootstap (since it's way cleaner and proper).

So, after that, only the range mode will have been implemented by me. Currently, it works like this:

- If a user clicks a date. The date gets toggled like normally.
- If a user presses a date for more than 300ms, a range mode gets activated (adding specific style to the start range date). The next date pressed will be the end range date and all the dates in between will be selected (I'm using moment and moment-range).
- If a user does range mode over an interval with holes (some dates aren't selected), the dates that aren't selected are added.
- If a user does range mode over an interval with no holes, they all get unselected.

The reason I chose this timeout version, instead of, for instance, a drag interval version. Was so that it would be possible to create a very large range, ie, a user presses a date, starting range mode, advances the datepickers for one year and clicks a date for the end range, selected one year of dates. With drag and drop that wouldn't be possible.

Anyway, I'm just mentioning this, because I'm not sure if I should assume I'll be sticking with my version or not. It will depend on how this design will end up.

**Comment by maxokorokov** [comment]
@PEsteves8, I would say you have a very elaborated example of range selection and I'm glad to hear you made it work with our current implementation. However I don't think we're gonna implement something like that as a default solution. 

The majority of use cases are pretty simple, ex. like for the booking sites. You click to select a range start and then click again to select the range end, handle styling and disable some dates along the way. This is currently doable with existing implementation (with a couple of caveats), so for now I think we would just:

- add a demo or a couple to show how to handle ranges selection
- add the mouse over info for the custom template (as on the airbnb.com for instance)
- better handle disabling dates (now it's possible to only disable a date once with `markDisabled`)

I'm not sure we want to provide a built-in range selection behind some kind of flag just yet, because there are really many ways to do it.

Thanks for the interest again and come back if you have any issues! We want to ensure that approaches as yours work fine with our implementation!

**Comment by PEsteves8** [comment]
Ok, great! I'll wait to see a first demo, because generally I would always prefer to use you code as much as possible. If I feel that keeping my approach is important I'll leave it as it is. Thanks :)
