### ISSUE TITLE
Tooltip does not show at the right postion using ChangeDetectionStrategy.OnPush

### ISSUE THREAD

**Issue by Hongbo-Miao** [ng-bootstrap/ng-bootstrap#772]
### Bug description:
When using `changeDetection: ChangeDetectionStrategy.OnPush`, the tooltip does not show at right position.
![image](https://cloud.githubusercontent.com/assets/3375461/18681771/7a429fd2-7f37-11e6-85d9-d5de58e6e35c.png)

Without `changeDetection: ChangeDetectionStrategy.OnPush`, it shows well
![image](https://cloud.githubusercontent.com/assets/3375461/18681785/8ad9d734-7f37-11e6-8d66-dbce9b153eae.png)

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/YZAJYYLw8pUq6IM6DZ1f?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:

- Angular 2.0.0
- ng-bootstrap 1.0.0-alpha.5
- Bootstrap 4 Alpha 4

**Comment by pkozlowski-opensource** [comment]
Thnx for reporting @Hongbo-Miao. This looks like a corner case for components using `OnPush` and manual triggers registration. It is easy to work-around on our end I'm doing just this in the #777

I will follow up with others in the Angular core team to see if this shouldn't be fixed in the Angular itself.
