### ISSUE TITLE
Modals and lazy-loaded NgbModule

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/ng-bootstrap#784]
Ref: http://stackoverflow.com/questions/39629827/opening-a-modal-from-a-lazy-loaded-module

We need to investigate / fix (if there is anything to fix).

**Comment by k-schneider** [comment]
Thanks for opening this!

I think the root of the problem is that the NgbModal service is intended to be an app-wide singleton?

Providers imported in lazy loaded modules are always new instances.  [The NgModules documentation covers this topic nicely.](https://angular.io/docs/ts/latest/guide/ngmodule.html#!#why-_userservice_-isn-t-shared)

I'm just not sure what the correct way of configuring a lazy loaded module would be..  If I need to import NgbModule in the lazy loaded module to have access to the component directives then it will also be importing a separate instance of the NgbModal service.

Thanks again.

**Comment by k-schneider** [comment]
The Material2 team ran into a similar issue with one of their services.  A good discussion and solution is available here:

[https://github.com/angular/material2/issues/1071](https://github.com/angular/material2/issues/1071)

**Comment by pkozlowski-opensource** [comment]
@k-schneider Yes. PRs welcomed.
