### ISSUE TITLE
Datepicker Popup - calendar focus on open

### ISSUE THREAD

**Issue by c1rus** [ng-bootstrap/ng-bootstrap#843]
Datepicker popup should show calendar with focus on input date, not current date.

Angular: 2.0.0

ng-bootstrap: 1.0.0-alpha.6

Bootstrap: 4-alpha 4

![capture1](https://cloud.githubusercontent.com/assets/11233730/19112369/c43d7d5e-8b04-11e6-974c-df8cd1dc1a1a.PNG)

**Comment by pkozlowski-opensource** [comment]
Agree. Will change in alpha.7.

**Comment by pkozlowski-opensource** [comment]
@maxokorokov shouldn't we change the logic so:
* if `startDate` is provided, use this
* if `startDate` is blank but model was provided use the model value
* if both `startDate` and model are blank use today

I could fix this issue in the `NgbInputDatepicker` but IMO it makes sense as the "global" behavior, no?

**Comment by pkozlowski-opensource** [comment]
Here is my (failed) attempt: https://github.com/pkozlowski-opensource/core/commit/27adec1152d0ed1d898c905a1a626f425adbc2cf

At this point I don't see much other choice than fix it on the input for now.

**Comment by maxokorokov** [comment]
There are two issues for me:

1. Popup always reopens with today
2. Initially `ngModel` is not taken into account, only `startDate`

I think I would do the following, unless I'm not getting it fully:

**NgbInputDatepicker**
- always reopen with the same month it was closed with (now always reopens with today)

**NgbDatepicker**
- do the `startDate` → `ngModel` → `today` priority flow initially, not when ngModel changes (looks like the issue is that ngModel is set asynchronously in this case)

Navigation and selection **should not be related by default** for me.

**Comment by pkozlowski-opensource** [comment]
@maxokorokov I hear you but IMO the current default behaviour is rather confusing. Please note that users still can control navigation by setting `startDate` or calling `navigateTo` method. The whole discussion is about what happens by default and IMO we should sensible defaults here. 

So I would still like to lobby for #844 to land. The way it is done is that we change defaults. We are not taking away any control from the users.
