### ISSUE TITLE
config firstDayOfWeek bug

### ISSUE THREAD

**Issue by baio** [ng-bootstrap/ng-bootstrap#882]
### Bug description:

Setting firstDayOfWeek - freezes (crashes) the application

```
export class DateComponent implements ControlValueAccessor {
  constructor(config: NgbDatepickerConfig) {
   //if comment this line, will work
    config.firstDayOfWeek = 0;
  }

```

### Version of Angular, ng-bootstrap, and Bootstrap:
Angular:
2.0.0

ng-bootstrap:

1.0.0-alpha.7

Bootstrap:
4.0

**Comment by pkozlowski-opensource** [comment]
Please provide a minimal reproduce scenario in plunker, see why it is important: https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

BTW, in 1.0.0-alpha.7 days / months indexes are 1-based instead of 0-based to follow the ISO 8601 standard: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CHANGELOG.md#breaking-changes

**Comment by wesleycho** [comment]
This is probably exactly what happened - I think this is safe to close.
