### ISSUE TITLE
Performance: Drop down opening slow when repeated in NgFor 

### ISSUE THREAD

**Issue by brandoncollins** [ng-bootstrap/ng-bootstrap#900]
The dropdown components open performance is affected by the # of other dropdown components on the page. I know this is not great UX, but I have a table of ~1000 items which have a dropdown component in one of the cells, similar to the example provided. 

http://plnkr.co/edit/IsdAtHkPQ4FnF8kYaRGA?p=preview

ng-bootstrap version: alpha.8

**Comment by pkozlowski-opensource** [comment]
Yeh, the global click handler (one that is used to close dropdowns on the outside clicks) is to blame here. Normally it is not an issue since in an app you would have just a limited number of dropdowns. 

As you've noticed it isn't a common scenario so you might want to roll out your own version of the dropdown directive that is tailored to your needs. We are going to look at this scenario but not as an immediate priority.

**Comment by pkozlowski-opensource** [comment]
One of the potential solutions would be to have a global service that tracks outside clicks and registers all the dropdown directives (it could probably be also useful to track outside clicks for other directives - ex.: datepicker popups). 

Here is a sketch of the solution: http://plnkr.co/edit/LvmpFxzCSRjlZCNU8Osm?p=preview
Obviously the above is very hacky (uses DOM API directly, isn't playing great with zones etc.) but that's the general idea.

**Comment by wesleycho** [comment]
In the meantime, I'd probably recommend implementing some sort of virtual scrolling to avoid having that many elements rendered at once. It seems like wasteful performance to have that many elements rendered at once.

**Comment by ngi80** [comment]
Hello, 
I have the same issue with a collapse element i applied on a 'card-block'.
Does the solution you mentioned previously could also solve my issue ?

I have a lot of card in card representing a tree of elements.

Thank you,

**Comment by thbt** [comment]
I found a way to improve the performance using the renderer and dynamically registering listener : http://plnkr.co/edit/SXEy855KQQQYXgjI5Fqc?p=preview
Should I put up a PR with this ?

**Comment by daevid66** [comment]
thbt's solution is exactly what I was about to implement, before searching. Please accept his/her pr.

**Comment by thbt** [comment]
@daevid66 I would like to do a PR but some tests are failing (while it works in the browser)
If you want to help you can check [https://github.com/thbt/ng-bootstrap/tree/dropdown-perf](my fork)

**Comment by laserus** [comment]
@wesleycho Do you have any example of *working* virtual scroll for ng2? 

As far as I know, there is nothing solid and we all are waiting for https://github.com/angular/material2/issues/823

**Comment by daBishMan** [comment]
when is this going to be merged and released please?

**Comment by PatrykTucki** [comment]
Are there any updates on this issue? Using ~30 dropdowns literally kills the app performance.

**Comment by matthiasscudlik** [comment]
I think Renderer2 should be used instead of the deprecated Rendererso that it should also work with the angular-universal approach and i suggest to use NgZone so that it runs completely outside of the angular change detection because the change detection is the performance killer here, not the event

**Comment by codepwner** [comment]
+1 I need a resolution for this issue please!

**Comment by liviu-c** [comment]
+1
Any updates on this?
Is this gonna be fixed in the near future?

**Comment by pkozlowski-opensource** [comment]
> Is this gonna be fixed in the near future?

We should have it covered in one of the next releases.

**Comment by daibertdiego** [comment]
+1

**Comment by rfrancisco** [comment]
Any news regarding this?

**Comment by liviu-c** [comment]
nothing new on this?

**Comment by kuhlschrank** [comment]
+1

**Comment by AntonLebiodkin** [comment]
+1

**Comment by rightisleft** [comment]
+1

**Comment by Rayno42** [comment]
+1

**Comment by Zak-C** [comment]
+1

**Comment by ExFlo** [comment]
+1

**Comment by germanpa** [comment]
+1

**Comment by gpsimmo** [comment]
Is there any update on this issue?!

**Comment by rpelavin** [comment]
+1

**Comment by kyrare** [comment]
+1

**Comment by Md-Aman** [comment]
+1

**Comment by rysilva** [comment]
I'd like to just echo that it's not just thousands that will cause this issue, and not always bad UX that causes this issue. We have a tabular UI where each row has two dropdowns. I don't think 50 rows warrants implementing virtual scrolling, but that's 100 dropdowns and a noticeable delay (500ms or more). With 100-200 rows, it's unusuable.

**Comment by alfazjikani** [comment]
Issue is being fixed by below work around for ngx-bootstrap dropdown.

`<table>
<tr *ngFor="let item of arr;">
...
<td class="cell-checkbox text-right vmiddle">

<span *ngIf="!item.show" class="fa fa-cog no-space dropdown-toggle pointer m-r" title="Options" (mouseleave)="item.show=false" (mouseenter)="item.show = true"></span>

<div *ngIf="item.show" class="dropdown-holder m-r" dropdown>
 <span dropdownToggle class="fa fa-cog dropdown-toggle pointer" title="Options"></span>
 <ul *dropdownMenu class="dropdown-menu">
  <li role="menuitem">
   <a class="dropdown-item pointer"> Option 1 </a>
  </li>
 </ul>
</div>

</td>
...
`
