### ISSUE TITLE
Compiling Error on Hosted Agent: Pagination typing

### ISSUE THREAD

**Issue by ialex90** [ng-bootstrap/ng-bootstrap#904]
Hi there,

I have no problems with node, but on Visual Studio and on Hosted Agent I have it.

The error is this one:
`..\@ng-bootstrap\ng-bootstrap\pagination\pagination.d.ts error TS1005: Build:'=' expected.`

not sure what's the problem, with node is working, even I updated Typescript to 2.0.3 for Visual Studio and it works, but as the hosted agent of TFS just have the 1.8.x version, and we can't updoad, not sure if that could be the problem.

Anyone else having the same? Any work around or fix from the ng-bootstrap team?

Thanks!

**Comment by pkozlowski-opensource** [comment]
Please provide complete error message as a bare minimum (line numbers). It is impossible to say anything based on just the info provided.

**Comment by ialex90** [comment]
Hope this is enough for you @pkozlowski-opensource 

`C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8\tsc.exe --project "C:\a\1\s\Development\Source\SFA.UI\UI\tsconfig.json"
UI\node_modules\@ng-bootstrap\ng-bootstrap\pagination\pagination.module.d.ts(2,31): Error TS2307: Build: Cannot find module './pagination'.
node_modules\@ng-bootstrap\ng-bootstrap\pagination\pagination.module.d.ts(2,31): error TS2307: Build: Cannot find module './pagination'. [C:xxxx\UI\UI.xproj]
Development\Source\SFA.UI\UI\node_modules\@ng-bootstrap\ng-bootstrap\popover\popover-config.d.ts(9,14): Error TS1112: Build: A class member cannot be declared optional.
node_modules\@ng-bootstrap\ng-bootstrap\popover\popover-config.d.ts(9,14): error TS1112: Build: A class member cannot be declared optional. [C:xxxx\UI\UI.xproj]
Development\Source\SFA.UI\UI\node_modules\@ng-bootstrap\ng-bootstrap\tooltip\tooltip-config.d.ts(9,14): Error TS1112: Build: A class member cannot be declared optional.
node_modules\@ng-bootstrap\ng-bootstrap\tooltip\tooltip-config.d.ts(9,14): error TS1112: Build: A class member cannot be declared optional. [C:xxxx\UI\UI.xproj]
Done Building Project "C:xxxx\UI\UI.xproj" (default targets) -- FAILED.`

**Comment by pkozlowski-opensource** [comment]
Errors related to `popover-config` and `tooltip-config` are due to TS version mismatch (we are using a feature from 2.0.x and your seem to be using an earlier version). The issue is [here](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/tooltip/tooltip-config.ts#L12). I think that we could drop optionality from this field and restore compatibility with 1.8. Will discuss with the rest of the team.

Regarding errors for pagination - I'm not sure what is going on. I've got a suspect but that's it. Are you sure that you've copied & pasted the entire error log?

In any case the root of the problem is TS version mismatch.

**Comment by ialex90** [comment]
I didn't find any advise of this dependency with TS 2.0.x in the doc, would be nice to have add it.

In the hosted agent I can't upgrade the TS version, that's handle it by MS, as far as I know, is there any way to don't add the pagination from npm? Or any work around? 

For tooltip and popover, keep us posted with the decision of the team, pls.

Thanks!

Ps: I'll check the error tmw again, if something is missing, I will update it here

**Comment by ialex90** [comment]
@pkozlowski-opensource Actually I just checked it again, and the problem with Tooltip and popover are not related to the incompatibility of TS 1.8, they are compatible with that version, the problem was I deleted the pagination.d.ts to see if that would work and I got that error.

So, brief, the only issue with TS 1.8 and ng-bootstrap it's related to the pagination. This is the whole info I got from the hosted agent.


```
Development\Source\SFA.UI\UI\node_modules\@ng-bootstrap\ng-bootstrap\pagination\pagination.d.ts (52, 14)
Development\Source\SFA.UI\UI\node_modules\@ng-bootstrap\ng-bootstrap\pagination\pagination.d.ts(52,14): Error TS1005: Build: '=' expected.

Development\Source\SFA.UI\UI\node_modules\@ng-bootstrap\ng-bootstrap\pagination\pagination.d.ts (52, 23)
Development\Source\SFA.UI\UI\node_modules\@ng-bootstrap\ng-bootstrap\pagination\pagination.d.ts(52,23): Error TS1005: Build: ';' expected.

Process 'msbuild.exe' exited with code '1'.
```

If I run it locally with TS 2.x, it works, but with 1.8 it doesn't. I thought to delete the pagination folder but module file has dependencies on it, so we can't.

**Comment by pkozlowski-opensource** [comment]
Thnx @ialex90 for the additional info. I think that we can easily restore TS 1.8 compatibility in the generated `.d.ts` files as there is nothing preventing us from doing so.

I will push a fix later today.

**Comment by pkozlowski-opensource** [comment]
The root cause of the problem discussed here is in this TS 2.0 breaking change: https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#getters-with-no-setters-are-automatically-inferred-to-be-readonly-properties

Files to be fixed:
* https://github.com/ng-bootstrap/ng-bootstrap/blob/20ad4574aea96fd9acf7f7265eacb8678cad2280/src/pagination/pagination.ts#L52
* https://github.com/ng-bootstrap/ng-bootstrap/blob/20ad4574aea96fd9acf7f7265eacb8678cad2280/src/buttons/radio.ts#L105-L107

After fixing the above we should create a minimal project based on TS 1.8 and test if there are no other issues.

**Comment by ialex90** [comment]
@pkozlowski-opensource that's a great news, thanks for the support, let us know please when you publish the fixed, waiting to publish the app, thanks! 👍
