### ISSUE TITLE
Typeahead this is undefined

### ISSUE THREAD

**Issue by sqwk** [ng-bootstrap/ng-bootstrap#917]
Using the typeahead module with a method that switches to an Observable returned by another method in the same class will return a "this is undefined" error.

    public titleOptions(search: Observable<string>): Observable<string[]> {
        console.log(this); // undefined
        let options = this.savedOptions_.getValue().map((option) => option.title);
        return search.debounceTime(200)
                     .distinctUntilChanged()
                     .switchMap(term => Observable.of(options.filter((value) => new RegExp(term, 'gi').test(value))));
    }

The examples only ever used another class or a constant, both outside the current class scope.

This can be resolved by binding `this` to the method used for `[ngbTypeahead]` in the constructor of the class: 

    constructor() {
        this.titleOptions = this.titleOptions.bind(this);
    }

While this works, it is slightly counterintuitive and should probably work without this by default?

**Comment by pkozlowski-opensource** [comment]
> While this works, it is slightly counterintuitive and should probably work without this by default?

Nope, we can't do this since here you would like to have `this` pointing to an instance of your component is inside typeahead directive we've got no access to the mentioned component instance. 

Observable chains are another source of pbs and you really don't want to go into binding default `this` in there. Best solution for now: use the `titleOptions = () => {...}` syntax as shown in our docs.

I will keep this issue open to add warning to our demo page.
