### ISSUE TITLE
API extraction script adjustements

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/ng-bootstrap#927]
2 issues spotted recently:
- [ ] - undocumented `@Input`s are showing up while they should not: https://ng-bootstrap.github.io/#/components/buttons
- [ ] - getters are documented properly, see: https://github.com/ng-bootstrap/ng-bootstrap/pull/903#discussion_r83921381

**Comment by jnizet** [comment]
I can't find where it was spotted anymore, but there's also the issue of default values not being displayed anymore. This is a nasty side-effect of this change: https://github.com/ng-bootstrap/ng-bootstrap/pull/891/commits/0bbe422927084a2bf51c5803127da25d5b474ccf

Another nasty side-effect is that the properties of config classes, which are not documented on purpose because their documentation matches with the corresponding directive property, don't appear anymore in the documentation.

I'm not quite sure what to do about this. Maybe the change should be reverted, and another marker than `@internal` should be set on members that can't be private nor internal, but shouldn't be documented.

**Comment by pkozlowski-opensource** [comment]
Yes, we need to look at the entire set of documentation assets and come up with consistent rules for extraction. I don't think that just reverting  0bbe422 is the solution as 0bbe422 helped us reduce amount of code we load to the client side (this is sth we need to take into account as well).
