### ISSUE TITLE
Ng-bootstrap collidates with angular-material2

### ISSUE THREAD

**Issue by ZuSe** [ng-bootstrap/ng-bootstrap#928]
For some components ng-bootstrap collidates with angular-material2.
As a result the component/form element gets messed up. As AM2 applies custom stylesheet to prevent such an behavior I see the problem in ng-bootstrap.  Examples here are radio buttons or check boxes.
The problem seems to be that type=radio affects ngb .

The most suitable solution here would be to have an option to tell per element if it should be ignored by ngb.
Dunno if there are others ways to prevent such an behavior.

**Comment by pkozlowski-opensource** [comment]
Please provide a reproduction scenario so we can confirm this, see: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#you-think-youve-found-a-bug

We've fixed a couple of issues around unwanted interaction of radio buttons so a reproduction sceanrio would allow us to confirm if it is fixed or not. This issue is not actionable without the reproduce scenario in plunker.

**Comment by pkozlowski-opensource** [comment]
@ZuSe haven't heard from you so going to close this one. In any case you can easily import only modules / directives you are already using as we _do_ provide NgModule for each and individual component. So if, say, you want to use only datepicker and typeahead you can do it like so:

```typescript
import {NgbModule} from '@ng-bootstrap/ng-bootstrap';

@NgModule({
  declarations: [AppComponent, ...],
  imports: [NgbDatepickerModule.forRoot(), NgbTypeaheadModule.forRoot(), ...],  
  bootstrap: [AppComponent]
})
export class AppModule {
}
```
