### ISSUE TITLE
Error: No provider for NgbModal!

### ISSUE THREAD

**Issue by keithmichelson** [ng-bootstrap/ng-bootstrap#945]
### Bug description:

Either after newest cli upgrade beta 18 or angular 2.1.0 upgrade I get this error when using a modal that worked perfectly before:
Error: No provider for NgbModal!

### Link to minimally-working plunker that reproduces the issue:
The plunk didn't example didn't have webpack

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular 2.1.0
ng-bootstrap 1.0.0-alpha.9
bootstrap 4 alpha 5

**Comment by keithmichelson** [comment]
Oh just saw this.. that's new. Made it work.
imports: [NgbModule.forRoot(), ...],

**Comment by pkozlowski-opensource** [comment]
> Oh just saw this.. that's new. Made it work.
imports: [NgbModule.forRoot(), ...],

Yep, https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CHANGELOG.md#breaking-changes

**Comment by rudradash111** [comment]
> Oh just saw this.. that's new. Made it work.
> imports: [NgbModule.forRoot(), ...],

but in angular 8 foorRoot() it depricated

**Comment by BRO-mesdocteurs** [comment]
So, has anybody reached to manage this issue in Angular 8+ ?

**Comment by shoaibrafa** [comment]
In my situation the problem was that I had added the modal component in my appcomponent.html as <mymodal></mymodal> and this gave me the error. So the soluton was to remove this tag from appcomponent and only have a button to call the open() method. 
<button class="btn btn-success btn-sm" (click)="open()">Add</button>
there is no forRoot() method in angular 8+ only NgbModal is enough to be added in app.modul.ts
