### ISSUE TITLE
Feature request: Modal instance to be accessed through promise

### ISSUE THREAD

**Issue by alex321** [ng-bootstrap/ng-bootstrap#981]
At the moment we can call **modalService.open(SomeComponent).componentInstance** to get the instance. However, the Component hasn't been fully initialised (through ngOnInit, etc.).

Would it be possible to provide it as Promise<SomeComponent> or something similar? In the same way that we can create components dynamically in angular. 

The current behavior seems slightly unintuitive as well. Cheers!

(Not needed I suppose) **Plunk: http://plnkr.co/edit/IyzT1bu5TGGd6YrsBEUt?p=preview**

**Comment by pkozlowski-opensource** [comment]
> Would it be possible to provide it as Promise or something similar?

Nope, we don't get this info from the framework.

>  In the same way that we can create components dynamically in angular.

What do you mean? We are using Angular standard mechanisms to create components...

> The current behavior seems slightly unintuitive as well.

Care to elaborate? What would be your alternative proposal?

**Comment by alex321** [comment]
I see. Well, ideally you would be able to access the component instance once it has been completely initialised i.e. after ngOnInit (and friends) were called rather than before. If angular doesn't provide that, what would be the best alternative to wait for those methods to be called except for using **setTimout**?

**Comment by pkozlowski-opensource** [comment]
> I see. Well, ideally you would be able to access the component instance once it has been completely initialised i.e. after ngOnInit (and friends) were called rather than before.

As mentioned, today Angular 2 doesn't gives us that hook. On top of this I believe that the current order of execution makes sense as otherwise it would be impossible to set inputs before `ngOnInit` is called, see: http://plnkr.co/edit/5RtETWNH2aIQczVpZySo?p=preview

> what would be the best alternative to wait for those methods to be called except for using setTimeout? I.e. what would be the preferred practice to kick of another change detection cycle.

It is super-hard for me to suggest anything without understanding your case. But in any case it would be a support question so we should move it to SO.

> Side note: I just realised that all of the components I've tried to create dynamically didn't use any of these methods - so I guess it's an angular feature request. :)

If you believe that something should be changed / added in the Angular itself feel free to open an issue in the Angular repository. 

Closing as not specific to ng-bootstrap but rather related to how Angular works.
